#include "symbol_modifier.hpp"

namespace {
  constexpr std::pair<char32_t, char32_t> make_point(char32_t point)
  {
    return std::pair<char32_t, char32_t>(point, point);
  }

  static const std::vector<std::pair<char32_t, char32_t>> characters
    {
      make_point(0x5E),
      make_point(0x60),
      make_point(0xA8),
      make_point(0xAF),
      make_point(0xB4),
      make_point(0xB8),
      {0x2C2, 0x2C5},
      {0x2D2, 0x2DF},
      {0x2E5, 0x2EB},
      make_point(0x2ED),
      {0x2EF, 0x2FF},
      make_point(0x375),
      {0x384, 0x385},
      make_point(0x1FBD),
      {0x1FBF, 0x1FC1},
      {0x1FCD, 0x1FCF},
      {0x1FDD, 0x1FDF},
      {0x1FED, 0x1FEF},
      {0x1FFD, 0x1FFE},
      {0x309B, 0x309C},
      {0xA700, 0xA716},
      {0xA720, 0xA721},
      {0xA789, 0xA78A},
      make_point(0xAB5B),
      {0xFBB2, 0xFBC1},
      make_point(0xFF3E),
      make_point(0xFF40),
      make_point(0xFFE3),
      {0x1F3FB, 0x1F3FF}
    };
}

/*
Character Name
U+005E    CIRCUMFLEX ACCENT
U+0060    GRAVE ACCENT
U+00A8    DIAERESIS
U+00AF    MACRON
U+00B4    ACUTE ACCENT
U+00B8    CEDILLA
U+02C2    MODIFIER LETTER LEFT ARROWHEAD
U+02C3    MODIFIER LETTER RIGHT ARROWHEAD
U+02C4    MODIFIER LETTER UP ARROWHEAD
U+02C5    MODIFIER LETTER DOWN ARROWHEAD
U+02D2    MODIFIER LETTER CENTRED RIGHT HALF RING
U+02D3    MODIFIER LETTER CENTRED LEFT HALF RING
U+02D4    MODIFIER LETTER UP TACK
U+02D5    MODIFIER LETTER DOWN TACK
U+02D6    MODIFIER LETTER PLUS SIGN
U+02D7    MODIFIER LETTER MINUS SIGN
U+02D8    BREVE
U+02D9    DOT ABOVE
U+02DA    RING ABOVE
U+02DB    OGONEK
U+02DC    SMALL TILDE
U+02DD    DOUBLE ACUTE ACCENT
U+02DE    MODIFIER LETTER RHOTIC HOOK
U+02DF    MODIFIER LETTER CROSS ACCENT
U+02E5    MODIFIER LETTER EXTRA-HIGH TONE BAR
U+02E6    MODIFIER LETTER HIGH TONE BAR
U+02E7    MODIFIER LETTER MID TONE BAR
U+02E8    MODIFIER LETTER LOW TONE BAR
U+02E9    MODIFIER LETTER EXTRA-LOW TONE BAR
U+02EA    MODIFIER LETTER YIN DEPARTING TONE MARK
U+02EB    MODIFIER LETTER YANG DEPARTING TONE MARK
U+02ED    MODIFIER LETTER UNASPIRATED
U+02EF    MODIFIER LETTER LOW DOWN ARROWHEAD
U+02F0    MODIFIER LETTER LOW UP ARROWHEAD
U+02F1    MODIFIER LETTER LOW LEFT ARROWHEAD
U+02F2    MODIFIER LETTER LOW RIGHT ARROWHEAD
U+02F3    MODIFIER LETTER LOW RING
U+02F4    MODIFIER LETTER MIDDLE GRAVE ACCENT
U+02F5    MODIFIER LETTER MIDDLE DOUBLE GRAVE ACCENT
U+02F6    MODIFIER LETTER MIDDLE DOUBLE ACUTE ACCENT
U+02F7    MODIFIER LETTER LOW TILDE
U+02F8    MODIFIER LETTER RAISED COLON
U+02F9    MODIFIER LETTER BEGIN HIGH TONE
U+02FA    MODIFIER LETTER END HIGH TONE
U+02FB    MODIFIER LETTER BEGIN LOW TONE
U+02FC    MODIFIER LETTER END LOW TONE
U+02FD    MODIFIER LETTER SHELF
U+02FE    MODIFIER LETTER OPEN SHELF
U+02FF    MODIFIER LETTER LOW LEFT ARROW
U+0375    GREEK LOWER NUMERAL SIGN
U+0384    GREEK TONOS
U+0385    GREEK DIALYTIKA TONOS
U+1FBD    GREEK KORONIS
U+1FBF    GREEK PSILI
U+1FC0    GREEK PERISPOMENI
U+1FC1    GREEK DIALYTIKA AND PERISPOMENI
U+1FCD    GREEK PSILI AND VARIA
U+1FCE    GREEK PSILI AND OXIA
U+1FCF    GREEK PSILI AND PERISPOMENI
U+1FDD    GREEK DASIA AND VARIA
U+1FDE    GREEK DASIA AND OXIA
U+1FDF    GREEK DASIA AND PERISPOMENI
U+1FED    GREEK DIALYTIKA AND VARIA
U+1FEE    GREEK DIALYTIKA AND OXIA
U+1FEF    GREEK VARIA
U+1FFD    GREEK OXIA
U+1FFE    GREEK DASIA
U+309B    KATAKANA-HIRAGANA VOICED SOUND MARK
U+309C    KATAKANA-HIRAGANA SEMI-VOICED SOUND MARK
U+A700    MODIFIER LETTER CHINESE TONE YIN PING
U+A701    MODIFIER LETTER CHINESE TONE YANG PING
U+A702    MODIFIER LETTER CHINESE TONE YIN SHANG
U+A703    MODIFIER LETTER CHINESE TONE YANG SHANG
U+A704    MODIFIER LETTER CHINESE TONE YIN QU
U+A705    MODIFIER LETTER CHINESE TONE YANG QU
U+A706    MODIFIER LETTER CHINESE TONE YIN RU
U+A707    MODIFIER LETTER CHINESE TONE YANG RU
U+A708    MODIFIER LETTER EXTRA-HIGH DOTTED TONE BAR
U+A709    MODIFIER LETTER HIGH DOTTED TONE BAR
U+A70A    MODIFIER LETTER MID DOTTED TONE BAR
U+A70B    MODIFIER LETTER LOW DOTTED TONE BAR
U+A70C    MODIFIER LETTER EXTRA-LOW DOTTED TONE BAR
U+A70D    MODIFIER LETTER EXTRA-HIGH DOTTED LEFT-STEM TONE BAR
U+A70E    MODIFIER LETTER HIGH DOTTED LEFT-STEM TONE BAR
U+A70F    MODIFIER LETTER MID DOTTED LEFT-STEM TONE BAR
U+A710    MODIFIER LETTER LOW DOTTED LEFT-STEM TONE BAR
U+A711    MODIFIER LETTER EXTRA-LOW DOTTED LEFT-STEM TONE BAR
U+A712    MODIFIER LETTER EXTRA-HIGH LEFT-STEM TONE BAR
U+A713    MODIFIER LETTER HIGH LEFT-STEM TONE BAR
U+A714    MODIFIER LETTER MID LEFT-STEM TONE BAR
U+A715    MODIFIER LETTER LOW LEFT-STEM TONE BAR
U+A716    MODIFIER LETTER EXTRA-LOW LEFT-STEM TONE BAR
U+A720    MODIFIER LETTER STRESS AND HIGH TONE
U+A721    MODIFIER LETTER STRESS AND LOW TONE
U+A789    MODIFIER LETTER COLON
U+A78A    MODIFIER LETTER SHORT EQUALS SIGN
U+AB5B    MODIFIER BREVE WITH INVERTED BREVE
U+FBB2    ARABIC SYMBOL DOT ABOVE
U+FBB3    ARABIC SYMBOL DOT BELOW
U+FBB4    ARABIC SYMBOL TWO DOTS ABOVE
U+FBB5    ARABIC SYMBOL TWO DOTS BELOW
U+FBB6    ARABIC SYMBOL THREE DOTS ABOVE
U+FBB7    ARABIC SYMBOL THREE DOTS BELOW
U+FBB8    ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS ABOVE
U+FBB9    ARABIC SYMBOL THREE DOTS POINTING DOWNWARDS BELOW
U+FBBA    ARABIC SYMBOL FOUR DOTS ABOVE
U+FBBB    ARABIC SYMBOL FOUR DOTS BELOW
U+FBBC    ARABIC SYMBOL DOUBLE VERTICAL BAR BELOW
U+FBBD    ARABIC SYMBOL TWO DOTS VERTICALLY ABOVE
U+FBBE    ARABIC SYMBOL TWO DOTS VERTICALLY BELOW
U+FBBF    ARABIC SYMBOL RING
U+FBC0    ARABIC SYMBOL SMALL TAH ABOVE
U+FBC1    ARABIC SYMBOL SMALL TAH BELOW
U+FF3E    FULLWIDTH CIRCUMFLEX ACCENT
U+FF40    FULLWIDTH GRAVE ACCENT
U+FFE3    FULLWIDTH MACRON
U+1F3FB    EMOJI MODIFIER FITZPATRICK TYPE-1-2
U+1F3FC    EMOJI MODIFIER FITZPATRICK TYPE-3
U+1F3FD    EMOJI MODIFIER FITZPATRICK TYPE-4
U+1F3FE    EMOJI MODIFIER FITZPATRICK TYPE-5
U+1F3FF    EMOJI MODIFIER FITZPATRICK TYPE-6
*/
