#include "mark_enclosing.hpp"

namespace unicode {
  constexpr std::pair<char32_t, char32_t> make_point(char32_t point)
  {
    return std::pair<char32_t, char32_t>(point, point);
  }

  static const std::vector<std::pair<char32_t, char32_t>> characters
    {
      {0x488, 0x489},
      make_point(0x1ABE),
      {0x20DD, 0x20E0},
      {0x20E2, 0x20E4},
      {0xA670, 0xA672}
    };
}

/*
Character Name
U+0488    COMBINING CYRILLIC HUNDRED THOUSANDS SIGN
U+0489    COMBINING CYRILLIC MILLIONS SIGN
U+1ABE    COMBINING PARENTHESES OVERLAY
U+20DD    COMBINING ENCLOSING CIRCLE
U+20DE    COMBINING ENCLOSING SQUARE
U+20DF    COMBINING ENCLOSING DIAMOND
U+20E0    COMBINING ENCLOSING CIRCLE BACKSLASH
U+20E2    COMBINING ENCLOSING SCREEN
U+20E3    COMBINING ENCLOSING KEYCAP
U+20E4    COMBINING ENCLOSING UPWARD POINTING TRIANGLE
U+A670    COMBINING CYRILLIC TEN MILLIONS SIGN
U+A671    COMBINING CYRILLIC HUNDRED MILLIONS SIGN
U+A672    COMBINING CYRILLIC THOUSAND MILLIONS SIGN
*/
