#include "symbol_modifier.hpp"

namespace {
  constexpr std::pair<char32_t, char32_t> make_point(char32_t point)
  {
    return std::pair<char32_t, char32_t>(point, point);
  }

  static const std::vector<std::pair<char32_t, char32_t>> characters
    {
      make_point(0x24),
      {0xA2, 0xA5},
      make_point(0x58F),
      make_point(0x60B),
      {0x9F2, 0x9F3},
      make_point(0x9FB),
      make_point(0xAF1),
      make_point(0xBF9),
      make_point(0xE3F),
      make_point(0x17DB),
      {0x20A0, 0x20BE},
      make_point(0xA838),
      make_point(0xFDFC),
      make_point(0xFE69),
      make_point(0xFF04),
      {0xFFE0, 0xFFE1},
      {0xFFE5, 0xFFE6}
    };
}

/*
Character Name
U+0024    DOLLAR SIGN
U+00A2    CENT SIGN
U+00A3    POUND SIGN
U+00A4    CURRENCY SIGN
U+00A5    YEN SIGN
U+058F    ARMENIAN DRAM SIGN
U+060B    AFGHANI SIGN
U+09F2    BENGALI RUPEE MARK
U+09F3    BENGALI RUPEE SIGN
U+09FB    BENGALI GANDA MARK
U+0AF1    GUJARATI RUPEE SIGN
U+0BF9    TAMIL RUPEE SIGN
U+0E3F    THAI CURRENCY SYMBOL BAHT
U+17DB    KHMER CURRENCY SYMBOL RIEL
U+20A0    EURO-CURRENCY SIGN
U+20A1    COLON SIGN
U+20A2    CRUZEIRO SIGN
U+20A3    FRENCH FRANC SIGN
U+20A4    LIRA SIGN
U+20A5    MILL SIGN
U+20A6    NAIRA SIGN
U+20A7    PESETA SIGN
U+20A8    RUPEE SIGN
U+20A9    WON SIGN
U+20AA    NEW SHEQEL SIGN
U+20AB    DONG SIGN
U+20AC    EURO SIGN
U+20AD    KIP SIGN
U+20AE    TUGRIK SIGN
U+20AF    DRACHMA SIGN
U+20B0    GERMAN PENNY SIGN
U+20B1    PESO SIGN
U+20B2    GUARANI SIGN
U+20B3    AUSTRAL SIGN
U+20B4    HRYVNIA SIGN
U+20B5    CEDI SIGN
U+20B6    LIVRE TOURNOIS SIGN
U+20B7    SPESMILO SIGN
U+20B8    TENGE SIGN
U+20B9    INDIAN RUPEE SIGN
U+20BA    TURKISH LIRA SIGN
U+20BB    NORDIC MARK SIGN
U+20BC    MANAT SIGN
U+20BD    RUBLE SIGN
U+20BE    LARI SIGN
U+A838    NORTH INDIC RUPEE MARK
U+FDFC    RIAL SIGN
U+FE69    SMALL DOLLAR SIGN
U+FF04    FULLWIDTH DOLLAR SIGN
U+FFE0    FULLWIDTH CENT SIGN
U+FFE1    FULLWIDTH POUND SIGN
U+FFE5    FULLWIDTH YEN SIGN
U+FFE6    FULLWIDTH WON SIGN
*/
