#ifndef UNICODE_LETTER_LOWERCASE_HPP_INCLUDED
#define UNICODE_LETTER_LOWERCASE_HPP_INCLUDED

namespace unicode {

// Ll
class letter_lowercase
{
/*
Character Name
U+0061    LATIN SMALL LETTER A
U+0062    LATIN SMALL LETTER B
U+0063    LATIN SMALL LETTER C
U+0064    LATIN SMALL LETTER D
U+0065    LATIN SMALL LETTER E
U+0066    LATIN SMALL LETTER F
U+0067    LATIN SMALL LETTER G
U+0068    LATIN SMALL LETTER H
U+0069    LATIN SMALL LETTER I
U+006A    LATIN SMALL LETTER J
U+006B    LATIN SMALL LETTER K
U+006C    LATIN SMALL LETTER L
U+006D    LATIN SMALL LETTER M
U+006E    LATIN SMALL LETTER N
U+006F    LATIN SMALL LETTER O
U+0070    LATIN SMALL LETTER P
U+0071    LATIN SMALL LETTER Q
U+0072    LATIN SMALL LETTER R
U+0073    LATIN SMALL LETTER S
U+0074    LATIN SMALL LETTER T
U+0075    LATIN SMALL LETTER U
U+0076    LATIN SMALL LETTER V
U+0077    LATIN SMALL LETTER W
U+0078    LATIN SMALL LETTER X
U+0079    LATIN SMALL LETTER Y
U+007A    LATIN SMALL LETTER Z

U+00B5    MICRO SIGN

U+00DF    LATIN SMALL LETTER SHARP S

U+00E0    LATIN SMALL LETTER A WITH GRAVE
U+00E1    LATIN SMALL LETTER A WITH ACUTE
U+00E2    LATIN SMALL LETTER A WITH CIRCUMFLEX
U+00E3    LATIN SMALL LETTER A WITH TILDE
U+00E4    LATIN SMALL LETTER A WITH DIAERESIS
U+00E5    LATIN SMALL LETTER A WITH RING ABOVE
U+00E6    LATIN SMALL LETTER AE
U+00E7    LATIN SMALL LETTER C WITH CEDILLA
U+00E8    LATIN SMALL LETTER E WITH GRAVE
U+00E9    LATIN SMALL LETTER E WITH ACUTE
U+00EA    LATIN SMALL LETTER E WITH CIRCUMFLEX
U+00EB    LATIN SMALL LETTER E WITH DIAERESIS
U+00EC    LATIN SMALL LETTER I WITH GRAVE
U+00ED    LATIN SMALL LETTER I WITH ACUTE
U+00EE    LATIN SMALL LETTER I WITH CIRCUMFLEX
U+00EF    LATIN SMALL LETTER I WITH DIAERESIS
U+00F0    LATIN SMALL LETTER ETH
U+00F1    LATIN SMALL LETTER N WITH TILDE
U+00F2    LATIN SMALL LETTER O WITH GRAVE
U+00F3    LATIN SMALL LETTER O WITH ACUTE
U+00F4    LATIN SMALL LETTER O WITH CIRCUMFLEX
U+00F5    LATIN SMALL LETTER O WITH TILDE
U+00F6    LATIN SMALL LETTER O WITH DIAERESIS
U+00F8    LATIN SMALL LETTER O WITH STROKE

U+00F9    LATIN SMALL LETTER U WITH GRAVE
U+00FA    LATIN SMALL LETTER U WITH ACUTE
U+00FB    LATIN SMALL LETTER U WITH CIRCUMFLEX
U+00FC    LATIN SMALL LETTER U WITH DIAERESIS
U+00FD    LATIN SMALL LETTER Y WITH ACUTE
U+00FE    LATIN SMALL LETTER THORN
U+00FF    LATIN SMALL LETTER Y WITH DIAERESIS

// JUMPING ONE GROUP
U+0101    LATIN SMALL LETTER A WITH MACRON
U+0103    LATIN SMALL LETTER A WITH BREVE
U+0105    LATIN SMALL LETTER A WITH OGONEK
U+0107    LATIN SMALL LETTER C WITH ACUTE
U+0109    LATIN SMALL LETTER C WITH CIRCUMFLEX
U+010B    LATIN SMALL LETTER C WITH DOT ABOVE
U+010D    LATIN SMALL LETTER C WITH CARON
U+010F    LATIN SMALL LETTER D WITH CARON
U+0111    LATIN SMALL LETTER D WITH STROKE
U+0113    LATIN SMALL LETTER E WITH MACRON
U+0115    LATIN SMALL LETTER E WITH BREVE
U+0117    LATIN SMALL LETTER E WITH DOT ABOVE
U+0119    LATIN SMALL LETTER E WITH OGONEK
U+011B    LATIN SMALL LETTER E WITH CARON
U+011D    LATIN SMALL LETTER G WITH CIRCUMFLEX
U+011F    LATIN SMALL LETTER G WITH BREVE
U+0121    LATIN SMALL LETTER G WITH DOT ABOVE
U+0123    LATIN SMALL LETTER G WITH CEDILLA
U+0125    LATIN SMALL LETTER H WITH CIRCUMFLEX
U+0127    LATIN SMALL LETTER H WITH STROKE
U+0129    LATIN SMALL LETTER I WITH TILDE
U+012B    LATIN SMALL LETTER I WITH MACRON
U+012D    LATIN SMALL LETTER I WITH BREVE
U+012F    LATIN SMALL LETTER I WITH OGONEK
U+0131    LATIN SMALL LETTER DOTLESS I
U+0133    LATIN SMALL LIGATURE IJ
U+0135    LATIN SMALL LETTER J WITH CIRCUMFLEX
U+0137    LATIN SMALL LETTER K WITH CEDILLA
U+0138    LATIN SMALL LETTER KRA
U+013A    LATIN SMALL LETTER L WITH ACUTE
U+013C    LATIN SMALL LETTER L WITH CEDILLA
U+013E    LATIN SMALL LETTER L WITH CARON
U+0140    LATIN SMALL LETTER L WITH MIDDLE DOT
U+0142    LATIN SMALL LETTER L WITH STROKE
U+0144    LATIN SMALL LETTER N WITH ACUTE
U+0146    LATIN SMALL LETTER N WITH CEDILLA
U+0148    LATIN SMALL LETTER N WITH CARON
U+0149    LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
U+014B    LATIN SMALL LETTER ENG
U+014D    LATIN SMALL LETTER O WITH MACRON
U+014F    LATIN SMALL LETTER O WITH BREVE
U+0151    LATIN SMALL LETTER O WITH DOUBLE ACUTE
U+0153    LATIN SMALL LIGATURE OE
U+0155    LATIN SMALL LETTER R WITH ACUTE
U+0157    LATIN SMALL LETTER R WITH CEDILLA
U+0159    LATIN SMALL LETTER R WITH CARON
U+015B    LATIN SMALL LETTER S WITH ACUTE
U+015D    LATIN SMALL LETTER S WITH CIRCUMFLEX
U+015F    LATIN SMALL LETTER S WITH CEDILLA
U+0161    LATIN SMALL LETTER S WITH CARON
U+0163    LATIN SMALL LETTER T WITH CEDILLA
U+0165    LATIN SMALL LETTER T WITH CARON
U+0167    LATIN SMALL LETTER T WITH STROKE
U+0169    LATIN SMALL LETTER U WITH TILDE
U+016B    LATIN SMALL LETTER U WITH MACRON
U+016D    LATIN SMALL LETTER U WITH BREVE
U+016F    LATIN SMALL LETTER U WITH RING ABOVE
U+0171    LATIN SMALL LETTER U WITH DOUBLE ACUTE
U+0173    LATIN SMALL LETTER U WITH OGONEK
U+0175    LATIN SMALL LETTER W WITH CIRCUMFLEX
U+0177    LATIN SMALL LETTER Y WITH CIRCUMFLEX

U+017A    LATIN SMALL LETTER Z WITH ACUTE
U+017C    LATIN SMALL LETTER Z WITH DOT ABOVE
U+017E    LATIN SMALL LETTER Z WITH CARON

U+017F    LATIN SMALL LETTER LONG S

U+0180    LATIN SMALL LETTER B WITH STROKE
U+0183    LATIN SMALL LETTER B WITH TOPBAR

U+0185    LATIN SMALL LETTER TONE SIX

U+0188    LATIN SMALL LETTER C WITH HOOK

// TODO jumping to much... order later
U+018C    LATIN SMALL LETTER D WITH TOPBAR
U+018D    LATIN SMALL LETTER TURNED DELTA
U+0192    LATIN SMALL LETTER F WITH HOOK
U+0195    LATIN SMALL LETTER HV
U+0199    LATIN SMALL LETTER K WITH HOOK
U+019A    LATIN SMALL LETTER L WITH BAR
U+019B    LATIN SMALL LETTER LAMBDA WITH STROKE
U+019E    LATIN SMALL LETTER N WITH LONG RIGHT LEG
U+01A1    LATIN SMALL LETTER O WITH HORN
U+01A3    LATIN SMALL LETTER OI
U+01A5    LATIN SMALL LETTER P WITH HOOK
U+01A8    LATIN SMALL LETTER TONE TWO
U+01AA    LATIN LETTER REVERSED ESH LOOP
U+01AB    LATIN SMALL LETTER T WITH PALATAL HOOK
U+01AD    LATIN SMALL LETTER T WITH HOOK
U+01B0    LATIN SMALL LETTER U WITH HORN
U+01B4    LATIN SMALL LETTER Y WITH HOOK
U+01B6    LATIN SMALL LETTER Z WITH STROKE
U+01B9    LATIN SMALL LETTER EZH REVERSED
U+01BA    LATIN SMALL LETTER EZH WITH TAIL
U+01BD    LATIN SMALL LETTER TONE FIVE
U+01BE    LATIN LETTER INVERTED GLOTTAL STOP WITH STROKE
U+01BF    LATIN LETTER WYNN
U+01C6    LATIN SMALL LETTER DZ WITH CARON
U+01C9    LATIN SMALL LETTER LJ
U+01CC    LATIN SMALL LETTER NJ
U+01CE    LATIN SMALL LETTER A WITH CARON
U+01D0    LATIN SMALL LETTER I WITH CARON
U+01D2    LATIN SMALL LETTER O WITH CARON
U+01D4    LATIN SMALL LETTER U WITH CARON
U+01D6    LATIN SMALL LETTER U WITH DIAERESIS AND MACRON
U+01D8    LATIN SMALL LETTER U WITH DIAERESIS AND ACUTE
U+01DA    LATIN SMALL LETTER U WITH DIAERESIS AND CARON
U+01DC    LATIN SMALL LETTER U WITH DIAERESIS AND GRAVE
U+01DD    LATIN SMALL LETTER TURNED E
U+01DF    LATIN SMALL LETTER A WITH DIAERESIS AND MACRON
U+01E1    LATIN SMALL LETTER A WITH DOT ABOVE AND MACRON
U+01E3    LATIN SMALL LETTER AE WITH MACRON
U+01E5    LATIN SMALL LETTER G WITH STROKE
U+01E7    LATIN SMALL LETTER G WITH CARON
U+01E9    LATIN SMALL LETTER K WITH CARON
U+01EB    LATIN SMALL LETTER O WITH OGONEK
U+01ED    LATIN SMALL LETTER O WITH OGONEK AND MACRON
U+01EF    LATIN SMALL LETTER EZH WITH CARON
U+01F0    LATIN SMALL LETTER J WITH CARON
U+01F3    LATIN SMALL LETTER DZ
U+01F5    LATIN SMALL LETTER G WITH ACUTE
U+01F9    LATIN SMALL LETTER N WITH GRAVE
U+01FB    LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
U+01FD    LATIN SMALL LETTER AE WITH ACUTE
U+01FF    LATIN SMALL LETTER O WITH STROKE AND ACUTE
U+0201    LATIN SMALL LETTER A WITH DOUBLE GRAVE
U+0203    LATIN SMALL LETTER A WITH INVERTED BREVE
U+0205    LATIN SMALL LETTER E WITH DOUBLE GRAVE
U+0207    LATIN SMALL LETTER E WITH INVERTED BREVE
U+0209    LATIN SMALL LETTER I WITH DOUBLE GRAVE
U+020B    LATIN SMALL LETTER I WITH INVERTED BREVE
U+020D    LATIN SMALL LETTER O WITH DOUBLE GRAVE
U+020F    LATIN SMALL LETTER O WITH INVERTED BREVE
U+0211    LATIN SMALL LETTER R WITH DOUBLE GRAVE
U+0213    LATIN SMALL LETTER R WITH INVERTED BREVE
U+0215    LATIN SMALL LETTER U WITH DOUBLE GRAVE
U+0217    LATIN SMALL LETTER U WITH INVERTED BREVE
U+0219    LATIN SMALL LETTER S WITH COMMA BELOW
U+021B    LATIN SMALL LETTER T WITH COMMA BELOW
U+021D    LATIN SMALL LETTER YOGH
U+021F    LATIN SMALL LETTER H WITH CARON
U+0221    LATIN SMALL LETTER D WITH CURL
U+0223    LATIN SMALL LETTER OU
U+0225    LATIN SMALL LETTER Z WITH HOOK
U+0227    LATIN SMALL LETTER A WITH DOT ABOVE
U+0229    LATIN SMALL LETTER E WITH CEDILLA
U+022B    LATIN SMALL LETTER O WITH DIAERESIS AND MACRON
U+022D    LATIN SMALL LETTER O WITH TILDE AND MACRON
U+022F    LATIN SMALL LETTER O WITH DOT ABOVE
U+0231    LATIN SMALL LETTER O WITH DOT ABOVE AND MACRON
U+0233    LATIN SMALL LETTER Y WITH MACRON
U+0234    LATIN SMALL LETTER L WITH CURL
U+0235    LATIN SMALL LETTER N WITH CURL
U+0236    LATIN SMALL LETTER T WITH CURL
U+0237    LATIN SMALL LETTER DOTLESS J
U+0238    LATIN SMALL LETTER DB DIGRAPH
U+0239    LATIN SMALL LETTER QP DIGRAPH
U+023C    LATIN SMALL LETTER C WITH STROKE
U+023F    LATIN SMALL LETTER S WITH SWASH TAIL
U+0240    LATIN SMALL LETTER Z WITH SWASH TAIL
U+0242    LATIN SMALL LETTER GLOTTAL STOP
U+0247    LATIN SMALL LETTER E WITH STROKE
U+0249    LATIN SMALL LETTER J WITH STROKE
U+024B    LATIN SMALL LETTER Q WITH HOOK TAIL
U+024D    LATIN SMALL LETTER R WITH STROKE
U+024F    LATIN SMALL LETTER Y WITH STROKE
U+0250    LATIN SMALL LETTER TURNED A
U+0251    LATIN SMALL LETTER ALPHA
U+0252    LATIN SMALL LETTER TURNED ALPHA
U+0253    LATIN SMALL LETTER B WITH HOOK
U+0254    LATIN SMALL LETTER OPEN O
U+0255    LATIN SMALL LETTER C WITH CURL
U+0256    LATIN SMALL LETTER D WITH TAIL
U+0257    LATIN SMALL LETTER D WITH HOOK
U+0258    LATIN SMALL LETTER REVERSED E
U+0259    LATIN SMALL LETTER SCHWA
U+025A    LATIN SMALL LETTER SCHWA WITH HOOK
U+025B    LATIN SMALL LETTER OPEN E
U+025C    LATIN SMALL LETTER REVERSED OPEN E
U+025D    LATIN SMALL LETTER REVERSED OPEN E WITH HOOK
U+025E    LATIN SMALL LETTER CLOSED REVERSED OPEN E
U+025F    LATIN SMALL LETTER DOTLESS J WITH STROKE
U+0260    LATIN SMALL LETTER G WITH HOOK
U+0261    LATIN SMALL LETTER SCRIPT G
U+0262    LATIN LETTER SMALL CAPITAL G
U+0263    LATIN SMALL LETTER GAMMA
U+0264    LATIN SMALL LETTER RAMS HORN
U+0265    LATIN SMALL LETTER TURNED H
U+0266    LATIN SMALL LETTER H WITH HOOK
U+0267    LATIN SMALL LETTER HENG WITH HOOK
U+0268    LATIN SMALL LETTER I WITH STROKE
U+0269    LATIN SMALL LETTER IOTA
U+026A    LATIN LETTER SMALL CAPITAL I
U+026B    LATIN SMALL LETTER L WITH MIDDLE TILDE
U+026C    LATIN SMALL LETTER L WITH BELT
U+026D    LATIN SMALL LETTER L WITH RETROFLEX HOOK
U+026E    LATIN SMALL LETTER LEZH
U+026F    LATIN SMALL LETTER TURNED M
U+0270    LATIN SMALL LETTER TURNED M WITH LONG LEG
U+0271    LATIN SMALL LETTER M WITH HOOK
U+0272    LATIN SMALL LETTER N WITH LEFT HOOK
U+0273    LATIN SMALL LETTER N WITH RETROFLEX HOOK
U+0274    LATIN LETTER SMALL CAPITAL N
U+0275    LATIN SMALL LETTER BARRED O
U+0276    LATIN LETTER SMALL CAPITAL OE
U+0277    LATIN SMALL LETTER CLOSED OMEGA
U+0278    LATIN SMALL LETTER PHI
U+0279    LATIN SMALL LETTER TURNED R
U+027A    LATIN SMALL LETTER TURNED R WITH LONG LEG
U+027B    LATIN SMALL LETTER TURNED R WITH HOOK
U+027C    LATIN SMALL LETTER R WITH LONG LEG
U+027D    LATIN SMALL LETTER R WITH TAIL
U+027E    LATIN SMALL LETTER R WITH FISHHOOK
U+027F    LATIN SMALL LETTER REVERSED R WITH FISHHOOK
U+0280    LATIN LETTER SMALL CAPITAL R
U+0281    LATIN LETTER SMALL CAPITAL INVERTED R
U+0282    LATIN SMALL LETTER S WITH HOOK
U+0283    LATIN SMALL LETTER ESH
U+0284    LATIN SMALL LETTER DOTLESS J WITH STROKE AND HOOK
U+0285    LATIN SMALL LETTER SQUAT REVERSED ESH
U+0286    LATIN SMALL LETTER ESH WITH CURL
U+0287    LATIN SMALL LETTER TURNED T
U+0288    LATIN SMALL LETTER T WITH RETROFLEX HOOK
U+0289    LATIN SMALL LETTER U BAR
U+028A    LATIN SMALL LETTER UPSILON
U+028B    LATIN SMALL LETTER V WITH HOOK
U+028C    LATIN SMALL LETTER TURNED V
U+028D    LATIN SMALL LETTER TURNED W
U+028E    LATIN SMALL LETTER TURNED Y
U+028F    LATIN LETTER SMALL CAPITAL Y
U+0290    LATIN SMALL LETTER Z WITH RETROFLEX HOOK
U+0291    LATIN SMALL LETTER Z WITH CURL
U+0292    LATIN SMALL LETTER EZH
U+0293    LATIN SMALL LETTER EZH WITH CURL
U+0295    LATIN LETTER PHARYNGEAL VOICED FRICATIVE
U+0296    LATIN LETTER INVERTED GLOTTAL STOP
U+0297    LATIN LETTER STRETCHED C
U+0298    LATIN LETTER BILABIAL CLICK
U+0299    LATIN LETTER SMALL CAPITAL B
U+029A    LATIN SMALL LETTER CLOSED OPEN E
U+029B    LATIN LETTER SMALL CAPITAL G WITH HOOK
U+029C    LATIN LETTER SMALL CAPITAL H
U+029D    LATIN SMALL LETTER J WITH CROSSED-TAIL
U+029E    LATIN SMALL LETTER TURNED K
U+029F    LATIN LETTER SMALL CAPITAL L
U+02A0    LATIN SMALL LETTER Q WITH HOOK
U+02A1    LATIN LETTER GLOTTAL STOP WITH STROKE
U+02A2    LATIN LETTER REVERSED GLOTTAL STOP WITH STROKE
U+02A3    LATIN SMALL LETTER DZ DIGRAPH
U+02A4    LATIN SMALL LETTER DEZH DIGRAPH
U+02A5    LATIN SMALL LETTER DZ DIGRAPH WITH CURL
U+02A6    LATIN SMALL LETTER TS DIGRAPH
U+02A7    LATIN SMALL LETTER TESH DIGRAPH
U+02A8    LATIN SMALL LETTER TC DIGRAPH WITH CURL
U+02A9    LATIN SMALL LETTER FENG DIGRAPH
U+02AA    LATIN SMALL LETTER LS DIGRAPH
U+02AB    LATIN SMALL LETTER LZ DIGRAPH
U+02AC    LATIN LETTER BILABIAL PERCUSSIVE
U+02AD    LATIN LETTER BIDENTAL PERCUSSIVE
U+02AE    LATIN SMALL LETTER TURNED H WITH FISHHOOK
U+02AF    LATIN SMALL LETTER TURNED H WITH FISHHOOK AND TAIL
U+0371    GREEK SMALL LETTER HETA
U+0373    GREEK SMALL LETTER ARCHAIC SAMPI
U+0377    GREEK SMALL LETTER PAMPHYLIAN DIGAMMA
U+037B    GREEK SMALL REVERSED LUNATE SIGMA SYMBOL
U+037C    GREEK SMALL DOTTED LUNATE SIGMA SYMBOL
U+037D    GREEK SMALL REVERSED DOTTED LUNATE SIGMA SYMBOL
U+0390    GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
U+03AC    GREEK SMALL LETTER ALPHA WITH TONOS
U+03AD    GREEK SMALL LETTER EPSILON WITH TONOS
U+03AE    GREEK SMALL LETTER ETA WITH TONOS
U+03AF    GREEK SMALL LETTER IOTA WITH TONOS
U+03B0    GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
U+03B1    GREEK SMALL LETTER ALPHA
U+03B2    GREEK SMALL LETTER BETA
U+03B3    GREEK SMALL LETTER GAMMA
U+03B4    GREEK SMALL LETTER DELTA
U+03B5    GREEK SMALL LETTER EPSILON
U+03B6    GREEK SMALL LETTER ZETA
U+03B7    GREEK SMALL LETTER ETA
U+03B8    GREEK SMALL LETTER THETA
U+03B9    GREEK SMALL LETTER IOTA
U+03BA    GREEK SMALL LETTER KAPPA
U+03BB    GREEK SMALL LETTER LAMDA
U+03BC    GREEK SMALL LETTER MU
U+03BD    GREEK SMALL LETTER NU
U+03BE    GREEK SMALL LETTER XI
U+03BF    GREEK SMALL LETTER OMICRON
U+03C0    GREEK SMALL LETTER PI
U+03C1    GREEK SMALL LETTER RHO
U+03C2    GREEK SMALL LETTER FINAL SIGMA
U+03C3    GREEK SMALL LETTER SIGMA
U+03C4    GREEK SMALL LETTER TAU
U+03C5    GREEK SMALL LETTER UPSILON
U+03C6    GREEK SMALL LETTER PHI
U+03C7    GREEK SMALL LETTER CHI
U+03C8    GREEK SMALL LETTER PSI
U+03C9    GREEK SMALL LETTER OMEGA
U+03CA    GREEK SMALL LETTER IOTA WITH DIALYTIKA
U+03CB    GREEK SMALL LETTER UPSILON WITH DIALYTIKA
U+03CC    GREEK SMALL LETTER OMICRON WITH TONOS
U+03CD    GREEK SMALL LETTER UPSILON WITH TONOS
U+03CE    GREEK SMALL LETTER OMEGA WITH TONOS
U+03D0    GREEK BETA SYMBOL
U+03D1    GREEK THETA SYMBOL
U+03D5    GREEK PHI SYMBOL
U+03D6    GREEK PI SYMBOL
U+03D7    GREEK KAI SYMBOL
U+03D9    GREEK SMALL LETTER ARCHAIC KOPPA
U+03DB    GREEK SMALL LETTER STIGMA
U+03DD    GREEK SMALL LETTER DIGAMMA
U+03DF    GREEK SMALL LETTER KOPPA
U+03E1    GREEK SMALL LETTER SAMPI
U+03E3    COPTIC SMALL LETTER SHEI
U+03E5    COPTIC SMALL LETTER FEI
U+03E7    COPTIC SMALL LETTER KHEI
U+03E9    COPTIC SMALL LETTER HORI
U+03EB    COPTIC SMALL LETTER GANGIA
U+03ED    COPTIC SMALL LETTER SHIMA
U+03EF    COPTIC SMALL LETTER DEI
U+03F0    GREEK KAPPA SYMBOL
U+03F1    GREEK RHO SYMBOL
U+03F2    GREEK LUNATE SIGMA SYMBOL
U+03F3    GREEK LETTER YOT
U+03F5    GREEK LUNATE EPSILON SYMBOL
U+03F8    GREEK SMALL LETTER SHO
U+03FB    GREEK SMALL LETTER SAN
U+03FC    GREEK RHO WITH STROKE SYMBOL
U+0430    CYRILLIC SMALL LETTER A
U+0431    CYRILLIC SMALL LETTER BE
U+0432    CYRILLIC SMALL LETTER VE
U+0433    CYRILLIC SMALL LETTER GHE
U+0434    CYRILLIC SMALL LETTER DE
U+0435    CYRILLIC SMALL LETTER IE
U+0436    CYRILLIC SMALL LETTER ZHE
U+0437    CYRILLIC SMALL LETTER ZE
U+0438    CYRILLIC SMALL LETTER I
U+0439    CYRILLIC SMALL LETTER SHORT I
U+043A    CYRILLIC SMALL LETTER KA
U+043B    CYRILLIC SMALL LETTER EL
U+043C    CYRILLIC SMALL LETTER EM
U+043D    CYRILLIC SMALL LETTER EN
U+043E    CYRILLIC SMALL LETTER O
U+043F    CYRILLIC SMALL LETTER PE
U+0440    CYRILLIC SMALL LETTER ER
U+0441    CYRILLIC SMALL LETTER ES
U+0442    CYRILLIC SMALL LETTER TE
U+0443    CYRILLIC SMALL LETTER U
U+0444    CYRILLIC SMALL LETTER EF
U+0445    CYRILLIC SMALL LETTER HA
U+0446    CYRILLIC SMALL LETTER TSE
U+0447    CYRILLIC SMALL LETTER CHE
U+0448    CYRILLIC SMALL LETTER SHA
U+0449    CYRILLIC SMALL LETTER SHCHA
U+044A    CYRILLIC SMALL LETTER HARD SIGN
U+044B    CYRILLIC SMALL LETTER YERU
U+044C    CYRILLIC SMALL LETTER SOFT SIGN
U+044D    CYRILLIC SMALL LETTER E
U+044E    CYRILLIC SMALL LETTER YU
U+044F    CYRILLIC SMALL LETTER YA
U+0450    CYRILLIC SMALL LETTER IE WITH GRAVE
U+0451    CYRILLIC SMALL LETTER IO
U+0452    CYRILLIC SMALL LETTER DJE
U+0453    CYRILLIC SMALL LETTER GJE
U+0454    CYRILLIC SMALL LETTER UKRAINIAN IE
U+0455    CYRILLIC SMALL LETTER DZE
U+0456    CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
U+0457    CYRILLIC SMALL LETTER YI
U+0458    CYRILLIC SMALL LETTER JE
U+0459    CYRILLIC SMALL LETTER LJE
U+045A    CYRILLIC SMALL LETTER NJE
U+045B    CYRILLIC SMALL LETTER TSHE
U+045C    CYRILLIC SMALL LETTER KJE
U+045D    CYRILLIC SMALL LETTER I WITH GRAVE
U+045E    CYRILLIC SMALL LETTER SHORT U
U+045F    CYRILLIC SMALL LETTER DZHE
U+0461    CYRILLIC SMALL LETTER OMEGA
U+0463    CYRILLIC SMALL LETTER YAT
U+0465    CYRILLIC SMALL LETTER IOTIFIED E
U+0467    CYRILLIC SMALL LETTER LITTLE YUS
U+0469    CYRILLIC SMALL LETTER IOTIFIED LITTLE YUS
U+046B    CYRILLIC SMALL LETTER BIG YUS
U+046D    CYRILLIC SMALL LETTER IOTIFIED BIG YUS
U+046F    CYRILLIC SMALL LETTER KSI
U+0471    CYRILLIC SMALL LETTER PSI
U+0473    CYRILLIC SMALL LETTER FITA
U+0475    CYRILLIC SMALL LETTER IZHITSA
U+0477    CYRILLIC SMALL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
U+0479    CYRILLIC SMALL LETTER UK
U+047B    CYRILLIC SMALL LETTER ROUND OMEGA
U+047D    CYRILLIC SMALL LETTER OMEGA WITH TITLO
U+047F    CYRILLIC SMALL LETTER OT
U+0481    CYRILLIC SMALL LETTER KOPPA
U+048B    CYRILLIC SMALL LETTER SHORT I WITH TAIL
U+048D    CYRILLIC SMALL LETTER SEMISOFT SIGN
U+048F    CYRILLIC SMALL LETTER ER WITH TICK
U+0491    CYRILLIC SMALL LETTER GHE WITH UPTURN
U+0493    CYRILLIC SMALL LETTER GHE WITH STROKE
U+0495    CYRILLIC SMALL LETTER GHE WITH MIDDLE HOOK
U+0497    CYRILLIC SMALL LETTER ZHE WITH DESCENDER
U+0499    CYRILLIC SMALL LETTER ZE WITH DESCENDER
U+049B    CYRILLIC SMALL LETTER KA WITH DESCENDER
U+049D    CYRILLIC SMALL LETTER KA WITH VERTICAL STROKE
U+049F    CYRILLIC SMALL LETTER KA WITH STROKE
U+04A1    CYRILLIC SMALL LETTER BASHKIR KA
U+04A3    CYRILLIC SMALL LETTER EN WITH DESCENDER
U+04A5    CYRILLIC SMALL LIGATURE EN GHE
U+04A7    CYRILLIC SMALL LETTER PE WITH MIDDLE HOOK
U+04A9    CYRILLIC SMALL LETTER ABKHASIAN HA
U+04AB    CYRILLIC SMALL LETTER ES WITH DESCENDER
U+04AD    CYRILLIC SMALL LETTER TE WITH DESCENDER
U+04AF    CYRILLIC SMALL LETTER STRAIGHT U
U+04B1    CYRILLIC SMALL LETTER STRAIGHT U WITH STROKE
U+04B3    CYRILLIC SMALL LETTER HA WITH DESCENDER
U+04B5    CYRILLIC SMALL LIGATURE TE TSE
U+04B7    CYRILLIC SMALL LETTER CHE WITH DESCENDER
U+04B9    CYRILLIC SMALL LETTER CHE WITH VERTICAL STROKE
U+04BB    CYRILLIC SMALL LETTER SHHA
U+04BD    CYRILLIC SMALL LETTER ABKHASIAN CHE
U+04BF    CYRILLIC SMALL LETTER ABKHASIAN CHE WITH DESCENDER
U+04C2    CYRILLIC SMALL LETTER ZHE WITH BREVE
U+04C4    CYRILLIC SMALL LETTER KA WITH HOOK
U+04C6    CYRILLIC SMALL LETTER EL WITH TAIL
U+04C8    CYRILLIC SMALL LETTER EN WITH HOOK
U+04CA    CYRILLIC SMALL LETTER EN WITH TAIL
U+04CC    CYRILLIC SMALL LETTER KHAKASSIAN CHE
U+04CE    CYRILLIC SMALL LETTER EM WITH TAIL
U+04CF    CYRILLIC SMALL LETTER PALOCHKA
U+04D1    CYRILLIC SMALL LETTER A WITH BREVE
U+04D3    CYRILLIC SMALL LETTER A WITH DIAERESIS
U+04D5    CYRILLIC SMALL LIGATURE A IE
U+04D7    CYRILLIC SMALL LETTER IE WITH BREVE
U+04D9    CYRILLIC SMALL LETTER SCHWA
U+04DB    CYRILLIC SMALL LETTER SCHWA WITH DIAERESIS
U+04DD    CYRILLIC SMALL LETTER ZHE WITH DIAERESIS
U+04DF    CYRILLIC SMALL LETTER ZE WITH DIAERESIS
U+04E1    CYRILLIC SMALL LETTER ABKHASIAN DZE
U+04E3    CYRILLIC SMALL LETTER I WITH MACRON
U+04E5    CYRILLIC SMALL LETTER I WITH DIAERESIS
U+04E7    CYRILLIC SMALL LETTER O WITH DIAERESIS
U+04E9    CYRILLIC SMALL LETTER BARRED O
U+04EB    CYRILLIC SMALL LETTER BARRED O WITH DIAERESIS
U+04ED    CYRILLIC SMALL LETTER E WITH DIAERESIS
U+04EF    CYRILLIC SMALL LETTER U WITH MACRON
U+04F1    CYRILLIC SMALL LETTER U WITH DIAERESIS
U+04F3    CYRILLIC SMALL LETTER U WITH DOUBLE ACUTE
U+04F5    CYRILLIC SMALL LETTER CHE WITH DIAERESIS
U+04F7    CYRILLIC SMALL LETTER GHE WITH DESCENDER
U+04F9    CYRILLIC SMALL LETTER YERU WITH DIAERESIS
U+04FB    CYRILLIC SMALL LETTER GHE WITH STROKE AND HOOK
U+04FD    CYRILLIC SMALL LETTER HA WITH HOOK
U+04FF    CYRILLIC SMALL LETTER HA WITH STROKE
U+0501    CYRILLIC SMALL LETTER KOMI DE
U+0503    CYRILLIC SMALL LETTER KOMI DJE
U+0505    CYRILLIC SMALL LETTER KOMI ZJE
U+0507    CYRILLIC SMALL LETTER KOMI DZJE
U+0509    CYRILLIC SMALL LETTER KOMI LJE
U+050B    CYRILLIC SMALL LETTER KOMI NJE
U+050D    CYRILLIC SMALL LETTER KOMI SJE
U+050F    CYRILLIC SMALL LETTER KOMI TJE
U+0511    CYRILLIC SMALL LETTER REVERSED ZE
U+0513    CYRILLIC SMALL LETTER EL WITH HOOK
U+0515    CYRILLIC SMALL LETTER LHA
U+0517    CYRILLIC SMALL LETTER RHA
U+0519    CYRILLIC SMALL LETTER YAE
U+051B    CYRILLIC SMALL LETTER QA
U+051D    CYRILLIC SMALL LETTER WE
U+051F    CYRILLIC SMALL LETTER ALEUT KA
U+0521    CYRILLIC SMALL LETTER EL WITH MIDDLE HOOK
U+0523    CYRILLIC SMALL LETTER EN WITH MIDDLE HOOK
U+0525    CYRILLIC SMALL LETTER PE WITH DESCENDER
U+0527    CYRILLIC SMALL LETTER SHHA WITH DESCENDER
U+0529    CYRILLIC SMALL LETTER EN WITH LEFT HOOK
U+052B    CYRILLIC SMALL LETTER DZZHE
U+052D    CYRILLIC SMALL LETTER DCHE
U+052F    CYRILLIC SMALL LETTER EL WITH DESCENDER
U+0561    ARMENIAN SMALL LETTER AYB
U+0562    ARMENIAN SMALL LETTER BEN
U+0563    ARMENIAN SMALL LETTER GIM
U+0564    ARMENIAN SMALL LETTER DA
U+0565    ARMENIAN SMALL LETTER ECH
U+0566    ARMENIAN SMALL LETTER ZA
U+0567    ARMENIAN SMALL LETTER EH
U+0568    ARMENIAN SMALL LETTER ET
U+0569    ARMENIAN SMALL LETTER TO
U+056A    ARMENIAN SMALL LETTER ZHE
U+056B    ARMENIAN SMALL LETTER INI
U+056C    ARMENIAN SMALL LETTER LIWN
U+056D    ARMENIAN SMALL LETTER XEH
U+056E    ARMENIAN SMALL LETTER CA
U+056F    ARMENIAN SMALL LETTER KEN
U+0570    ARMENIAN SMALL LETTER HO
U+0571    ARMENIAN SMALL LETTER JA
U+0572    ARMENIAN SMALL LETTER GHAD
U+0573    ARMENIAN SMALL LETTER CHEH
U+0574    ARMENIAN SMALL LETTER MEN
U+0575    ARMENIAN SMALL LETTER YI
U+0576    ARMENIAN SMALL LETTER NOW
U+0577    ARMENIAN SMALL LETTER SHA
U+0578    ARMENIAN SMALL LETTER VO
U+0579    ARMENIAN SMALL LETTER CHA
U+057A    ARMENIAN SMALL LETTER PEH
U+057B    ARMENIAN SMALL LETTER JHEH
U+057C    ARMENIAN SMALL LETTER RA
U+057D    ARMENIAN SMALL LETTER SEH
U+057E    ARMENIAN SMALL LETTER VEW
U+057F    ARMENIAN SMALL LETTER TIWN
U+0580    ARMENIAN SMALL LETTER REH
U+0581    ARMENIAN SMALL LETTER CO
U+0582    ARMENIAN SMALL LETTER YIWN
U+0583    ARMENIAN SMALL LETTER PIWR
U+0584    ARMENIAN SMALL LETTER KEH
U+0585    ARMENIAN SMALL LETTER OH
U+0586    ARMENIAN SMALL LETTER FEH
U+0587    ARMENIAN SMALL LIGATURE ECH YIWN
U+13F8    CHEROKEE SMALL LETTER YE
U+13F9    CHEROKEE SMALL LETTER YI
U+13FA    CHEROKEE SMALL LETTER YO
U+13FB    CHEROKEE SMALL LETTER YU
U+13FC    CHEROKEE SMALL LETTER YV
U+13FD    CHEROKEE SMALL LETTER MV
U+1D00    LATIN LETTER SMALL CAPITAL A
U+1D01    LATIN LETTER SMALL CAPITAL AE
U+1D02    LATIN SMALL LETTER TURNED AE
U+1D03    LATIN LETTER SMALL CAPITAL BARRED B
U+1D04    LATIN LETTER SMALL CAPITAL C
U+1D05    LATIN LETTER SMALL CAPITAL D
U+1D06    LATIN LETTER SMALL CAPITAL ETH
U+1D07    LATIN LETTER SMALL CAPITAL E
U+1D08    LATIN SMALL LETTER TURNED OPEN E
U+1D09    LATIN SMALL LETTER TURNED I
U+1D0A    LATIN LETTER SMALL CAPITAL J
U+1D0B    LATIN LETTER SMALL CAPITAL K
U+1D0C    LATIN LETTER SMALL CAPITAL L WITH STROKE
U+1D0D    LATIN LETTER SMALL CAPITAL M
U+1D0E    LATIN LETTER SMALL CAPITAL REVERSED N
U+1D0F    LATIN LETTER SMALL CAPITAL O
U+1D10    LATIN LETTER SMALL CAPITAL OPEN O
U+1D11    LATIN SMALL LETTER SIDEWAYS O
U+1D12    LATIN SMALL LETTER SIDEWAYS OPEN O
U+1D13    LATIN SMALL LETTER SIDEWAYS O WITH STROKE
U+1D14    LATIN SMALL LETTER TURNED OE
U+1D15    LATIN LETTER SMALL CAPITAL OU
U+1D16    LATIN SMALL LETTER TOP HALF O
U+1D17    LATIN SMALL LETTER BOTTOM HALF O
U+1D18    LATIN LETTER SMALL CAPITAL P
U+1D19    LATIN LETTER SMALL CAPITAL REVERSED R
U+1D1A    LATIN LETTER SMALL CAPITAL TURNED R
U+1D1B    LATIN LETTER SMALL CAPITAL T
U+1D1C    LATIN LETTER SMALL CAPITAL U
U+1D1D    LATIN SMALL LETTER SIDEWAYS U
U+1D1E    LATIN SMALL LETTER SIDEWAYS DIAERESIZED U
U+1D1F    LATIN SMALL LETTER SIDEWAYS TURNED M
U+1D20    LATIN LETTER SMALL CAPITAL V
U+1D21    LATIN LETTER SMALL CAPITAL W
U+1D22    LATIN LETTER SMALL CAPITAL Z
U+1D23    LATIN LETTER SMALL CAPITAL EZH
U+1D24    LATIN LETTER VOICED LARYNGEAL SPIRANT
U+1D25    LATIN LETTER AIN
U+1D26    GREEK LETTER SMALL CAPITAL GAMMA
U+1D27    GREEK LETTER SMALL CAPITAL LAMDA
U+1D28    GREEK LETTER SMALL CAPITAL PI
U+1D29    GREEK LETTER SMALL CAPITAL RHO
U+1D2A    GREEK LETTER SMALL CAPITAL PSI
U+1D2B    CYRILLIC LETTER SMALL CAPITAL EL
U+1D6B    LATIN SMALL LETTER UE
U+1D6C    LATIN SMALL LETTER B WITH MIDDLE TILDE
U+1D6D    LATIN SMALL LETTER D WITH MIDDLE TILDE
U+1D6E    LATIN SMALL LETTER F WITH MIDDLE TILDE
U+1D6F    LATIN SMALL LETTER M WITH MIDDLE TILDE
U+1D70    LATIN SMALL LETTER N WITH MIDDLE TILDE
U+1D71    LATIN SMALL LETTER P WITH MIDDLE TILDE
U+1D72    LATIN SMALL LETTER R WITH MIDDLE TILDE
U+1D73    LATIN SMALL LETTER R WITH FISHHOOK AND MIDDLE TILDE
U+1D74    LATIN SMALL LETTER S WITH MIDDLE TILDE
U+1D75    LATIN SMALL LETTER T WITH MIDDLE TILDE
U+1D76    LATIN SMALL LETTER Z WITH MIDDLE TILDE
U+1D77    LATIN SMALL LETTER TURNED G
U+1D79    LATIN SMALL LETTER INSULAR G
U+1D7A    LATIN SMALL LETTER TH WITH STRIKETHROUGH
U+1D7B    LATIN SMALL CAPITAL LETTER I WITH STROKE
U+1D7C    LATIN SMALL LETTER IOTA WITH STROKE
U+1D7D    LATIN SMALL LETTER P WITH STROKE
U+1D7E    LATIN SMALL CAPITAL LETTER U WITH STROKE
U+1D7F    LATIN SMALL LETTER UPSILON WITH STROKE
U+1D80    LATIN SMALL LETTER B WITH PALATAL HOOK
U+1D81    LATIN SMALL LETTER D WITH PALATAL HOOK
U+1D82    LATIN SMALL LETTER F WITH PALATAL HOOK
U+1D83    LATIN SMALL LETTER G WITH PALATAL HOOK
U+1D84    LATIN SMALL LETTER K WITH PALATAL HOOK
U+1D85    LATIN SMALL LETTER L WITH PALATAL HOOK
U+1D86    LATIN SMALL LETTER M WITH PALATAL HOOK
U+1D87    LATIN SMALL LETTER N WITH PALATAL HOOK
U+1D88    LATIN SMALL LETTER P WITH PALATAL HOOK
U+1D89    LATIN SMALL LETTER R WITH PALATAL HOOK
U+1D8A    LATIN SMALL LETTER S WITH PALATAL HOOK
U+1D8B    LATIN SMALL LETTER ESH WITH PALATAL HOOK
U+1D8C    LATIN SMALL LETTER V WITH PALATAL HOOK
U+1D8D    LATIN SMALL LETTER X WITH PALATAL HOOK
U+1D8E    LATIN SMALL LETTER Z WITH PALATAL HOOK
U+1D8F    LATIN SMALL LETTER A WITH RETROFLEX HOOK
U+1D90    LATIN SMALL LETTER ALPHA WITH RETROFLEX HOOK
U+1D91    LATIN SMALL LETTER D WITH HOOK AND TAIL
U+1D92    LATIN SMALL LETTER E WITH RETROFLEX HOOK
U+1D93    LATIN SMALL LETTER OPEN E WITH RETROFLEX HOOK
U+1D94    LATIN SMALL LETTER REVERSED OPEN E WITH RETROFLEX HOOK
U+1D95    LATIN SMALL LETTER SCHWA WITH RETROFLEX HOOK
U+1D96    LATIN SMALL LETTER I WITH RETROFLEX HOOK
U+1D97    LATIN SMALL LETTER OPEN O WITH RETROFLEX HOOK
U+1D98    LATIN SMALL LETTER ESH WITH RETROFLEX HOOK
U+1D99    LATIN SMALL LETTER U WITH RETROFLEX HOOK
U+1D9A    LATIN SMALL LETTER EZH WITH RETROFLEX HOOK
U+1E01    LATIN SMALL LETTER A WITH RING BELOW
U+1E03    LATIN SMALL LETTER B WITH DOT ABOVE
U+1E05    LATIN SMALL LETTER B WITH DOT BELOW
U+1E07    LATIN SMALL LETTER B WITH LINE BELOW
U+1E09    LATIN SMALL LETTER C WITH CEDILLA AND ACUTE
U+1E0B    LATIN SMALL LETTER D WITH DOT ABOVE
U+1E0D    LATIN SMALL LETTER D WITH DOT BELOW
U+1E0F    LATIN SMALL LETTER D WITH LINE BELOW
U+1E11    LATIN SMALL LETTER D WITH CEDILLA
U+1E13    LATIN SMALL LETTER D WITH CIRCUMFLEX BELOW
U+1E15    LATIN SMALL LETTER E WITH MACRON AND GRAVE
U+1E17    LATIN SMALL LETTER E WITH MACRON AND ACUTE
U+1E19    LATIN SMALL LETTER E WITH CIRCUMFLEX BELOW
U+1E1B    LATIN SMALL LETTER E WITH TILDE BELOW
U+1E1D    LATIN SMALL LETTER E WITH CEDILLA AND BREVE
U+1E1F    LATIN SMALL LETTER F WITH DOT ABOVE
U+1E21    LATIN SMALL LETTER G WITH MACRON
U+1E23    LATIN SMALL LETTER H WITH DOT ABOVE
U+1E25    LATIN SMALL LETTER H WITH DOT BELOW
U+1E27    LATIN SMALL LETTER H WITH DIAERESIS
U+1E29    LATIN SMALL LETTER H WITH CEDILLA
U+1E2B    LATIN SMALL LETTER H WITH BREVE BELOW
U+1E2D    LATIN SMALL LETTER I WITH TILDE BELOW
U+1E2F    LATIN SMALL LETTER I WITH DIAERESIS AND ACUTE
U+1E31    LATIN SMALL LETTER K WITH ACUTE
U+1E33    LATIN SMALL LETTER K WITH DOT BELOW
U+1E35    LATIN SMALL LETTER K WITH LINE BELOW
U+1E37    LATIN SMALL LETTER L WITH DOT BELOW
U+1E39    LATIN SMALL LETTER L WITH DOT BELOW AND MACRON
U+1E3B    LATIN SMALL LETTER L WITH LINE BELOW
U+1E3D    LATIN SMALL LETTER L WITH CIRCUMFLEX BELOW
U+1E3F    LATIN SMALL LETTER M WITH ACUTE
U+1E41    LATIN SMALL LETTER M WITH DOT ABOVE
U+1E43    LATIN SMALL LETTER M WITH DOT BELOW
U+1E45    LATIN SMALL LETTER N WITH DOT ABOVE
U+1E47    LATIN SMALL LETTER N WITH DOT BELOW
U+1E49    LATIN SMALL LETTER N WITH LINE BELOW
U+1E4B    LATIN SMALL LETTER N WITH CIRCUMFLEX BELOW
U+1E4D    LATIN SMALL LETTER O WITH TILDE AND ACUTE
U+1E4F    LATIN SMALL LETTER O WITH TILDE AND DIAERESIS
U+1E51    LATIN SMALL LETTER O WITH MACRON AND GRAVE
U+1E53    LATIN SMALL LETTER O WITH MACRON AND ACUTE
U+1E55    LATIN SMALL LETTER P WITH ACUTE
U+1E57    LATIN SMALL LETTER P WITH DOT ABOVE
U+1E59    LATIN SMALL LETTER R WITH DOT ABOVE
U+1E5B    LATIN SMALL LETTER R WITH DOT BELOW
U+1E5D    LATIN SMALL LETTER R WITH DOT BELOW AND MACRON
U+1E5F    LATIN SMALL LETTER R WITH LINE BELOW
U+1E61    LATIN SMALL LETTER S WITH DOT ABOVE
U+1E63    LATIN SMALL LETTER S WITH DOT BELOW
U+1E65    LATIN SMALL LETTER S WITH ACUTE AND DOT ABOVE
U+1E67    LATIN SMALL LETTER S WITH CARON AND DOT ABOVE
U+1E69    LATIN SMALL LETTER S WITH DOT BELOW AND DOT ABOVE
U+1E6B    LATIN SMALL LETTER T WITH DOT ABOVE
U+1E6D    LATIN SMALL LETTER T WITH DOT BELOW
U+1E6F    LATIN SMALL LETTER T WITH LINE BELOW
U+1E71    LATIN SMALL LETTER T WITH CIRCUMFLEX BELOW
U+1E73    LATIN SMALL LETTER U WITH DIAERESIS BELOW
U+1E75    LATIN SMALL LETTER U WITH TILDE BELOW
U+1E77    LATIN SMALL LETTER U WITH CIRCUMFLEX BELOW
U+1E79    LATIN SMALL LETTER U WITH TILDE AND ACUTE
U+1E7B    LATIN SMALL LETTER U WITH MACRON AND DIAERESIS
U+1E7D    LATIN SMALL LETTER V WITH TILDE
U+1E7F    LATIN SMALL LETTER V WITH DOT BELOW
U+1E81    LATIN SMALL LETTER W WITH GRAVE
U+1E83    LATIN SMALL LETTER W WITH ACUTE
U+1E85    LATIN SMALL LETTER W WITH DIAERESIS
U+1E87    LATIN SMALL LETTER W WITH DOT ABOVE
U+1E89    LATIN SMALL LETTER W WITH DOT BELOW
U+1E8B    LATIN SMALL LETTER X WITH DOT ABOVE
U+1E8D    LATIN SMALL LETTER X WITH DIAERESIS
U+1E8F    LATIN SMALL LETTER Y WITH DOT ABOVE
U+1E91    LATIN SMALL LETTER Z WITH CIRCUMFLEX
U+1E93    LATIN SMALL LETTER Z WITH DOT BELOW
U+1E95    LATIN SMALL LETTER Z WITH LINE BELOW
U+1E96    LATIN SMALL LETTER H WITH LINE BELOW
U+1E97    LATIN SMALL LETTER T WITH DIAERESIS
U+1E98    LATIN SMALL LETTER W WITH RING ABOVE
U+1E99    LATIN SMALL LETTER Y WITH RING ABOVE
U+1E9A    LATIN SMALL LETTER A WITH RIGHT HALF RING
U+1E9B    LATIN SMALL LETTER LONG S WITH DOT ABOVE
U+1E9C    LATIN SMALL LETTER LONG S WITH DIAGONAL STROKE
U+1E9D    LATIN SMALL LETTER LONG S WITH HIGH STROKE
U+1E9F    LATIN SMALL LETTER DELTA
U+1EA1    LATIN SMALL LETTER A WITH DOT BELOW
U+1EA3    LATIN SMALL LETTER A WITH HOOK ABOVE
U+1EA5    LATIN SMALL LETTER A WITH CIRCUMFLEX AND ACUTE
U+1EA7    LATIN SMALL LETTER A WITH CIRCUMFLEX AND GRAVE
U+1EA9    LATIN SMALL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
U+1EAB    LATIN SMALL LETTER A WITH CIRCUMFLEX AND TILDE
U+1EAD    LATIN SMALL LETTER A WITH CIRCUMFLEX AND DOT BELOW
U+1EAF    LATIN SMALL LETTER A WITH BREVE AND ACUTE
U+1EB1    LATIN SMALL LETTER A WITH BREVE AND GRAVE
U+1EB3    LATIN SMALL LETTER A WITH BREVE AND HOOK ABOVE
U+1EB5    LATIN SMALL LETTER A WITH BREVE AND TILDE
U+1EB7    LATIN SMALL LETTER A WITH BREVE AND DOT BELOW
U+1EB9    LATIN SMALL LETTER E WITH DOT BELOW
U+1EBB    LATIN SMALL LETTER E WITH HOOK ABOVE
U+1EBD    LATIN SMALL LETTER E WITH TILDE
U+1EBF    LATIN SMALL LETTER E WITH CIRCUMFLEX AND ACUTE
U+1EC1    LATIN SMALL LETTER E WITH CIRCUMFLEX AND GRAVE
U+1EC3    LATIN SMALL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
U+1EC5    LATIN SMALL LETTER E WITH CIRCUMFLEX AND TILDE
U+1EC7    LATIN SMALL LETTER E WITH CIRCUMFLEX AND DOT BELOW
U+1EC9    LATIN SMALL LETTER I WITH HOOK ABOVE
U+1ECB    LATIN SMALL LETTER I WITH DOT BELOW
U+1ECD    LATIN SMALL LETTER O WITH DOT BELOW
U+1ECF    LATIN SMALL LETTER O WITH HOOK ABOVE
U+1ED1    LATIN SMALL LETTER O WITH CIRCUMFLEX AND ACUTE
U+1ED3    LATIN SMALL LETTER O WITH CIRCUMFLEX AND GRAVE
U+1ED5    LATIN SMALL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
U+1ED7    LATIN SMALL LETTER O WITH CIRCUMFLEX AND TILDE
U+1ED9    LATIN SMALL LETTER O WITH CIRCUMFLEX AND DOT BELOW
U+1EDB    LATIN SMALL LETTER O WITH HORN AND ACUTE
U+1EDD    LATIN SMALL LETTER O WITH HORN AND GRAVE
U+1EDF    LATIN SMALL LETTER O WITH HORN AND HOOK ABOVE
U+1EE1    LATIN SMALL LETTER O WITH HORN AND TILDE
U+1EE3    LATIN SMALL LETTER O WITH HORN AND DOT BELOW
U+1EE5    LATIN SMALL LETTER U WITH DOT BELOW
U+1EE7    LATIN SMALL LETTER U WITH HOOK ABOVE
U+1EE9    LATIN SMALL LETTER U WITH HORN AND ACUTE
U+1EEB    LATIN SMALL LETTER U WITH HORN AND GRAVE
U+1EED    LATIN SMALL LETTER U WITH HORN AND HOOK ABOVE
U+1EEF    LATIN SMALL LETTER U WITH HORN AND TILDE
U+1EF1    LATIN SMALL LETTER U WITH HORN AND DOT BELOW
U+1EF3    LATIN SMALL LETTER Y WITH GRAVE
U+1EF5    LATIN SMALL LETTER Y WITH DOT BELOW
U+1EF7    LATIN SMALL LETTER Y WITH HOOK ABOVE
U+1EF9    LATIN SMALL LETTER Y WITH TILDE
U+1EFB    LATIN SMALL LETTER MIDDLE-WELSH LL
U+1EFD    LATIN SMALL LETTER MIDDLE-WELSH V
U+1EFF    LATIN SMALL LETTER Y WITH LOOP
U+1F00    GREEK SMALL LETTER ALPHA WITH PSILI
U+1F01    GREEK SMALL LETTER ALPHA WITH DASIA
U+1F02    GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA
U+1F03    GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA
U+1F04    GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA
U+1F05    GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA
U+1F06    GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI
U+1F07    GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI
U+1F10    GREEK SMALL LETTER EPSILON WITH PSILI
U+1F11    GREEK SMALL LETTER EPSILON WITH DASIA
U+1F12    GREEK SMALL LETTER EPSILON WITH PSILI AND VARIA
U+1F13    GREEK SMALL LETTER EPSILON WITH DASIA AND VARIA
U+1F14    GREEK SMALL LETTER EPSILON WITH PSILI AND OXIA
U+1F15    GREEK SMALL LETTER EPSILON WITH DASIA AND OXIA
U+1F20    GREEK SMALL LETTER ETA WITH PSILI
U+1F21    GREEK SMALL LETTER ETA WITH DASIA
U+1F22    GREEK SMALL LETTER ETA WITH PSILI AND VARIA
U+1F23    GREEK SMALL LETTER ETA WITH DASIA AND VARIA
U+1F24    GREEK SMALL LETTER ETA WITH PSILI AND OXIA
U+1F25    GREEK SMALL LETTER ETA WITH DASIA AND OXIA
U+1F26    GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI
U+1F27    GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI
U+1F30    GREEK SMALL LETTER IOTA WITH PSILI
U+1F31    GREEK SMALL LETTER IOTA WITH DASIA
U+1F32    GREEK SMALL LETTER IOTA WITH PSILI AND VARIA
U+1F33    GREEK SMALL LETTER IOTA WITH DASIA AND VARIA
U+1F34    GREEK SMALL LETTER IOTA WITH PSILI AND OXIA
U+1F35    GREEK SMALL LETTER IOTA WITH DASIA AND OXIA
U+1F36    GREEK SMALL LETTER IOTA WITH PSILI AND PERISPOMENI
U+1F37    GREEK SMALL LETTER IOTA WITH DASIA AND PERISPOMENI
U+1F40    GREEK SMALL LETTER OMICRON WITH PSILI
U+1F41    GREEK SMALL LETTER OMICRON WITH DASIA
U+1F42    GREEK SMALL LETTER OMICRON WITH PSILI AND VARIA
U+1F43    GREEK SMALL LETTER OMICRON WITH DASIA AND VARIA
U+1F44    GREEK SMALL LETTER OMICRON WITH PSILI AND OXIA
U+1F45    GREEK SMALL LETTER OMICRON WITH DASIA AND OXIA
U+1F50    GREEK SMALL LETTER UPSILON WITH PSILI
U+1F51    GREEK SMALL LETTER UPSILON WITH DASIA
U+1F52    GREEK SMALL LETTER UPSILON WITH PSILI AND VARIA
U+1F53    GREEK SMALL LETTER UPSILON WITH DASIA AND VARIA
U+1F54    GREEK SMALL LETTER UPSILON WITH PSILI AND OXIA
U+1F55    GREEK SMALL LETTER UPSILON WITH DASIA AND OXIA
U+1F56    GREEK SMALL LETTER UPSILON WITH PSILI AND PERISPOMENI
U+1F57    GREEK SMALL LETTER UPSILON WITH DASIA AND PERISPOMENI
U+1F60    GREEK SMALL LETTER OMEGA WITH PSILI
U+1F61    GREEK SMALL LETTER OMEGA WITH DASIA
U+1F62    GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA
U+1F63    GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA
U+1F64    GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA
U+1F65    GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA
U+1F66    GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI
U+1F67    GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI
U+1F70    GREEK SMALL LETTER ALPHA WITH VARIA
U+1F71    GREEK SMALL LETTER ALPHA WITH OXIA
U+1F72    GREEK SMALL LETTER EPSILON WITH VARIA
U+1F73    GREEK SMALL LETTER EPSILON WITH OXIA
U+1F74    GREEK SMALL LETTER ETA WITH VARIA
U+1F75    GREEK SMALL LETTER ETA WITH OXIA
U+1F76    GREEK SMALL LETTER IOTA WITH VARIA
U+1F77    GREEK SMALL LETTER IOTA WITH OXIA
U+1F78    GREEK SMALL LETTER OMICRON WITH VARIA
U+1F79    GREEK SMALL LETTER OMICRON WITH OXIA
U+1F7A    GREEK SMALL LETTER UPSILON WITH VARIA
U+1F7B    GREEK SMALL LETTER UPSILON WITH OXIA
U+1F7C    GREEK SMALL LETTER OMEGA WITH VARIA
U+1F7D    GREEK SMALL LETTER OMEGA WITH OXIA
U+1F80    GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI
U+1F81    GREEK SMALL LETTER ALPHA WITH DASIA AND YPOGEGRAMMENI
U+1F82    GREEK SMALL LETTER ALPHA WITH PSILI AND VARIA AND YPOGEGRAMMENI
U+1F83    GREEK SMALL LETTER ALPHA WITH DASIA AND VARIA AND YPOGEGRAMMENI
U+1F84    GREEK SMALL LETTER ALPHA WITH PSILI AND OXIA AND YPOGEGRAMMENI
U+1F85    GREEK SMALL LETTER ALPHA WITH DASIA AND OXIA AND YPOGEGRAMMENI
U+1F86    GREEK SMALL LETTER ALPHA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
U+1F87    GREEK SMALL LETTER ALPHA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
U+1F90    GREEK SMALL LETTER ETA WITH PSILI AND YPOGEGRAMMENI
U+1F91    GREEK SMALL LETTER ETA WITH DASIA AND YPOGEGRAMMENI
U+1F92    GREEK SMALL LETTER ETA WITH PSILI AND VARIA AND YPOGEGRAMMENI
U+1F93    GREEK SMALL LETTER ETA WITH DASIA AND VARIA AND YPOGEGRAMMENI
U+1F94    GREEK SMALL LETTER ETA WITH PSILI AND OXIA AND YPOGEGRAMMENI
U+1F95    GREEK SMALL LETTER ETA WITH DASIA AND OXIA AND YPOGEGRAMMENI
U+1F96    GREEK SMALL LETTER ETA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
U+1F97    GREEK SMALL LETTER ETA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
U+1FA0    GREEK SMALL LETTER OMEGA WITH PSILI AND YPOGEGRAMMENI
U+1FA1    GREEK SMALL LETTER OMEGA WITH DASIA AND YPOGEGRAMMENI
U+1FA2    GREEK SMALL LETTER OMEGA WITH PSILI AND VARIA AND YPOGEGRAMMENI
U+1FA3    GREEK SMALL LETTER OMEGA WITH DASIA AND VARIA AND YPOGEGRAMMENI
U+1FA4    GREEK SMALL LETTER OMEGA WITH PSILI AND OXIA AND YPOGEGRAMMENI
U+1FA5    GREEK SMALL LETTER OMEGA WITH DASIA AND OXIA AND YPOGEGRAMMENI
U+1FA6    GREEK SMALL LETTER OMEGA WITH PSILI AND PERISPOMENI AND YPOGEGRAMMENI
U+1FA7    GREEK SMALL LETTER OMEGA WITH DASIA AND PERISPOMENI AND YPOGEGRAMMENI
U+1FB0    GREEK SMALL LETTER ALPHA WITH VRACHY
U+1FB1    GREEK SMALL LETTER ALPHA WITH MACRON
U+1FB2    GREEK SMALL LETTER ALPHA WITH VARIA AND YPOGEGRAMMENI
U+1FB3    GREEK SMALL LETTER ALPHA WITH YPOGEGRAMMENI
U+1FB4    GREEK SMALL LETTER ALPHA WITH OXIA AND YPOGEGRAMMENI
U+1FB6    GREEK SMALL LETTER ALPHA WITH PERISPOMENI
U+1FB7    GREEK SMALL LETTER ALPHA WITH PERISPOMENI AND YPOGEGRAMMENI
U+1FBE    GREEK PROSGEGRAMMENI
U+1FC2    GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI
U+1FC3    GREEK SMALL LETTER ETA WITH YPOGEGRAMMENI
U+1FC4    GREEK SMALL LETTER ETA WITH OXIA AND YPOGEGRAMMENI
U+1FC6    GREEK SMALL LETTER ETA WITH PERISPOMENI
U+1FC7    GREEK SMALL LETTER ETA WITH PERISPOMENI AND YPOGEGRAMMENI
U+1FD0    GREEK SMALL LETTER IOTA WITH VRACHY
U+1FD1    GREEK SMALL LETTER IOTA WITH MACRON
U+1FD2    GREEK SMALL LETTER IOTA WITH DIALYTIKA AND VARIA
U+1FD3    GREEK SMALL LETTER IOTA WITH DIALYTIKA AND OXIA
U+1FD6    GREEK SMALL LETTER IOTA WITH PERISPOMENI
U+1FD7    GREEK SMALL LETTER IOTA WITH DIALYTIKA AND PERISPOMENI
U+1FE0    GREEK SMALL LETTER UPSILON WITH VRACHY
U+1FE1    GREEK SMALL LETTER UPSILON WITH MACRON
U+1FE2    GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND VARIA
U+1FE3    GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND OXIA
U+1FE4    GREEK SMALL LETTER RHO WITH PSILI
U+1FE5    GREEK SMALL LETTER RHO WITH DASIA
U+1FE6    GREEK SMALL LETTER UPSILON WITH PERISPOMENI
U+1FE7    GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND PERISPOMENI
U+1FF2    GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI
U+1FF3    GREEK SMALL LETTER OMEGA WITH YPOGEGRAMMENI
U+1FF4    GREEK SMALL LETTER OMEGA WITH OXIA AND YPOGEGRAMMENI
U+1FF6    GREEK SMALL LETTER OMEGA WITH PERISPOMENI
U+1FF7    GREEK SMALL LETTER OMEGA WITH PERISPOMENI AND YPOGEGRAMMENI
U+210A    SCRIPT SMALL G
U+210E    PLANCK CONSTANT
U+210F    PLANCK CONSTANT OVER TWO PI
U+2113    SCRIPT SMALL L
U+212F    SCRIPT SMALL E
U+2134    SCRIPT SMALL O
U+2139    INFORMATION SOURCE
U+213C    DOUBLE-STRUCK SMALL PI
U+213D    DOUBLE-STRUCK SMALL GAMMA
U+2146    DOUBLE-STRUCK ITALIC SMALL D
U+2147    DOUBLE-STRUCK ITALIC SMALL E
U+2148    DOUBLE-STRUCK ITALIC SMALL I
U+2149    DOUBLE-STRUCK ITALIC SMALL J
U+214E    TURNED SMALL F
U+2184    LATIN SMALL LETTER REVERSED C
U+2C30    GLAGOLITIC SMALL LETTER AZU
U+2C31    GLAGOLITIC SMALL LETTER BUKY
U+2C32    GLAGOLITIC SMALL LETTER VEDE
U+2C33    GLAGOLITIC SMALL LETTER GLAGOLI
U+2C34    GLAGOLITIC SMALL LETTER DOBRO
U+2C35    GLAGOLITIC SMALL LETTER YESTU
U+2C36    GLAGOLITIC SMALL LETTER ZHIVETE
U+2C37    GLAGOLITIC SMALL LETTER DZELO
U+2C38    GLAGOLITIC SMALL LETTER ZEMLJA
U+2C39    GLAGOLITIC SMALL LETTER IZHE
U+2C3A    GLAGOLITIC SMALL LETTER INITIAL IZHE
U+2C3B    GLAGOLITIC SMALL LETTER I
U+2C3C    GLAGOLITIC SMALL LETTER DJERVI
U+2C3D    GLAGOLITIC SMALL LETTER KAKO
U+2C3E    GLAGOLITIC SMALL LETTER LJUDIJE
U+2C3F    GLAGOLITIC SMALL LETTER MYSLITE
U+2C40    GLAGOLITIC SMALL LETTER NASHI
U+2C41    GLAGOLITIC SMALL LETTER ONU
U+2C42    GLAGOLITIC SMALL LETTER POKOJI
U+2C43    GLAGOLITIC SMALL LETTER RITSI
U+2C44    GLAGOLITIC SMALL LETTER SLOVO
U+2C45    GLAGOLITIC SMALL LETTER TVRIDO
U+2C46    GLAGOLITIC SMALL LETTER UKU
U+2C47    GLAGOLITIC SMALL LETTER FRITU
U+2C48    GLAGOLITIC SMALL LETTER HERU
U+2C49    GLAGOLITIC SMALL LETTER OTU
U+2C4A    GLAGOLITIC SMALL LETTER PE
U+2C4B    GLAGOLITIC SMALL LETTER SHTA
U+2C4C    GLAGOLITIC SMALL LETTER TSI
U+2C4D    GLAGOLITIC SMALL LETTER CHRIVI
U+2C4E    GLAGOLITIC SMALL LETTER SHA
U+2C4F    GLAGOLITIC SMALL LETTER YERU
U+2C50    GLAGOLITIC SMALL LETTER YERI
U+2C51    GLAGOLITIC SMALL LETTER YATI
U+2C52    GLAGOLITIC SMALL LETTER SPIDERY HA
U+2C53    GLAGOLITIC SMALL LETTER YU
U+2C54    GLAGOLITIC SMALL LETTER SMALL YUS
U+2C55    GLAGOLITIC SMALL LETTER SMALL YUS WITH TAIL
U+2C56    GLAGOLITIC SMALL LETTER YO
U+2C57    GLAGOLITIC SMALL LETTER IOTATED SMALL YUS
U+2C58    GLAGOLITIC SMALL LETTER BIG YUS
U+2C59    GLAGOLITIC SMALL LETTER IOTATED BIG YUS
U+2C5A    GLAGOLITIC SMALL LETTER FITA
U+2C5B    GLAGOLITIC SMALL LETTER IZHITSA
U+2C5C    GLAGOLITIC SMALL LETTER SHTAPIC
U+2C5D    GLAGOLITIC SMALL LETTER TROKUTASTI A
U+2C5E    GLAGOLITIC SMALL LETTER LATINATE MYSLITE
U+2C61    LATIN SMALL LETTER L WITH DOUBLE BAR
U+2C65    LATIN SMALL LETTER A WITH STROKE
U+2C66    LATIN SMALL LETTER T WITH DIAGONAL STROKE
U+2C68    LATIN SMALL LETTER H WITH DESCENDER
U+2C6A    LATIN SMALL LETTER K WITH DESCENDER
U+2C6C    LATIN SMALL LETTER Z WITH DESCENDER
U+2C71    LATIN SMALL LETTER V WITH RIGHT HOOK
U+2C73    LATIN SMALL LETTER W WITH HOOK
U+2C74    LATIN SMALL LETTER V WITH CURL
U+2C76    LATIN SMALL LETTER HALF H
U+2C77    LATIN SMALL LETTER TAILLESS PHI
U+2C78    LATIN SMALL LETTER E WITH NOTCH
U+2C79    LATIN SMALL LETTER TURNED R WITH TAIL
U+2C7A    LATIN SMALL LETTER O WITH LOW RING INSIDE
U+2C7B    LATIN LETTER SMALL CAPITAL TURNED E
U+2C81    COPTIC SMALL LETTER ALFA
U+2C83    COPTIC SMALL LETTER VIDA
U+2C85    COPTIC SMALL LETTER GAMMA
U+2C87    COPTIC SMALL LETTER DALDA
U+2C89    COPTIC SMALL LETTER EIE
U+2C8B    COPTIC SMALL LETTER SOU
U+2C8D    COPTIC SMALL LETTER ZATA
U+2C8F    COPTIC SMALL LETTER HATE
U+2C91    COPTIC SMALL LETTER THETHE
U+2C93    COPTIC SMALL LETTER IAUDA
U+2C95    COPTIC SMALL LETTER KAPA
U+2C97    COPTIC SMALL LETTER LAULA
U+2C99    COPTIC SMALL LETTER MI
U+2C9B    COPTIC SMALL LETTER NI
U+2C9D    COPTIC SMALL LETTER KSI
U+2C9F    COPTIC SMALL LETTER O
U+2CA1    COPTIC SMALL LETTER PI
U+2CA3    COPTIC SMALL LETTER RO
U+2CA5    COPTIC SMALL LETTER SIMA
U+2CA7    COPTIC SMALL LETTER TAU
U+2CA9    COPTIC SMALL LETTER UA
U+2CAB    COPTIC SMALL LETTER FI
U+2CAD    COPTIC SMALL LETTER KHI
U+2CAF    COPTIC SMALL LETTER PSI
U+2CB1    COPTIC SMALL LETTER OOU
U+2CB3    COPTIC SMALL LETTER DIALECT-P ALEF
U+2CB5    COPTIC SMALL LETTER OLD COPTIC AIN
U+2CB7    COPTIC SMALL LETTER CRYPTOGRAMMIC EIE
U+2CB9    COPTIC SMALL LETTER DIALECT-P KAPA
U+2CBB    COPTIC SMALL LETTER DIALECT-P NI
U+2CBD    COPTIC SMALL LETTER CRYPTOGRAMMIC NI
U+2CBF    COPTIC SMALL LETTER OLD COPTIC OOU
U+2CC1    COPTIC SMALL LETTER SAMPI
U+2CC3    COPTIC SMALL LETTER CROSSED SHEI
U+2CC5    COPTIC SMALL LETTER OLD COPTIC SHEI
U+2CC7    COPTIC SMALL LETTER OLD COPTIC ESH
U+2CC9    COPTIC SMALL LETTER AKHMIMIC KHEI
U+2CCB    COPTIC SMALL LETTER DIALECT-P HORI
U+2CCD    COPTIC SMALL LETTER OLD COPTIC HORI
U+2CCF    COPTIC SMALL LETTER OLD COPTIC HA
U+2CD1    COPTIC SMALL LETTER L-SHAPED HA
U+2CD3    COPTIC SMALL LETTER OLD COPTIC HEI
U+2CD5    COPTIC SMALL LETTER OLD COPTIC HAT
U+2CD7    COPTIC SMALL LETTER OLD COPTIC GANGIA
U+2CD9    COPTIC SMALL LETTER OLD COPTIC DJA
U+2CDB    COPTIC SMALL LETTER OLD COPTIC SHIMA
U+2CDD    COPTIC SMALL LETTER OLD NUBIAN SHIMA
U+2CDF    COPTIC SMALL LETTER OLD NUBIAN NGI
U+2CE1    COPTIC SMALL LETTER OLD NUBIAN NYI
U+2CE3    COPTIC SMALL LETTER OLD NUBIAN WAU
U+2CE4    COPTIC SYMBOL KAI
U+2CEC    COPTIC SMALL LETTER CRYPTOGRAMMIC SHEI
U+2CEE    COPTIC SMALL LETTER CRYPTOGRAMMIC GANGIA
U+2CF3    COPTIC SMALL LETTER BOHAIRIC KHEI
U+2D00    GEORGIAN SMALL LETTER AN
U+2D01    GEORGIAN SMALL LETTER BAN
U+2D02    GEORGIAN SMALL LETTER GAN
U+2D03    GEORGIAN SMALL LETTER DON
U+2D04    GEORGIAN SMALL LETTER EN
U+2D05    GEORGIAN SMALL LETTER VIN
U+2D06    GEORGIAN SMALL LETTER ZEN
U+2D07    GEORGIAN SMALL LETTER TAN
U+2D08    GEORGIAN SMALL LETTER IN
U+2D09    GEORGIAN SMALL LETTER KAN
U+2D0A    GEORGIAN SMALL LETTER LAS
U+2D0B    GEORGIAN SMALL LETTER MAN
U+2D0C    GEORGIAN SMALL LETTER NAR
U+2D0D    GEORGIAN SMALL LETTER ON
U+2D0E    GEORGIAN SMALL LETTER PAR
U+2D0F    GEORGIAN SMALL LETTER ZHAR
U+2D10    GEORGIAN SMALL LETTER RAE
U+2D11    GEORGIAN SMALL LETTER SAN
U+2D12    GEORGIAN SMALL LETTER TAR
U+2D13    GEORGIAN SMALL LETTER UN
U+2D14    GEORGIAN SMALL LETTER PHAR
U+2D15    GEORGIAN SMALL LETTER KHAR
U+2D16    GEORGIAN SMALL LETTER GHAN
U+2D17    GEORGIAN SMALL LETTER QAR
U+2D18    GEORGIAN SMALL LETTER SHIN
U+2D19    GEORGIAN SMALL LETTER CHIN
U+2D1A    GEORGIAN SMALL LETTER CAN
U+2D1B    GEORGIAN SMALL LETTER JIL
U+2D1C    GEORGIAN SMALL LETTER CIL
U+2D1D    GEORGIAN SMALL LETTER CHAR
U+2D1E    GEORGIAN SMALL LETTER XAN
U+2D1F    GEORGIAN SMALL LETTER JHAN
U+2D20    GEORGIAN SMALL LETTER HAE
U+2D21    GEORGIAN SMALL LETTER HE
U+2D22    GEORGIAN SMALL LETTER HIE
U+2D23    GEORGIAN SMALL LETTER WE
U+2D24    GEORGIAN SMALL LETTER HAR
U+2D25    GEORGIAN SMALL LETTER HOE
U+2D27    GEORGIAN SMALL LETTER YN
U+2D2D    GEORGIAN SMALL LETTER AEN
U+A641    CYRILLIC SMALL LETTER ZEMLYA
U+A643    CYRILLIC SMALL LETTER DZELO
U+A645    CYRILLIC SMALL LETTER REVERSED DZE
U+A647    CYRILLIC SMALL LETTER IOTA
U+A649    CYRILLIC SMALL LETTER DJERV
U+A64B    CYRILLIC SMALL LETTER MONOGRAPH UK
U+A64D    CYRILLIC SMALL LETTER BROAD OMEGA
U+A64F    CYRILLIC SMALL LETTER NEUTRAL YER
U+A651    CYRILLIC SMALL LETTER YERU WITH BACK YER
U+A653    CYRILLIC SMALL LETTER IOTIFIED YAT
U+A655    CYRILLIC SMALL LETTER REVERSED YU
U+A657    CYRILLIC SMALL LETTER IOTIFIED A
U+A659    CYRILLIC SMALL LETTER CLOSED LITTLE YUS
U+A65B    CYRILLIC SMALL LETTER BLENDED YUS
U+A65D    CYRILLIC SMALL LETTER IOTIFIED CLOSED LITTLE YUS
U+A65F    CYRILLIC SMALL LETTER YN
U+A661    CYRILLIC SMALL LETTER REVERSED TSE
U+A663    CYRILLIC SMALL LETTER SOFT DE
U+A665    CYRILLIC SMALL LETTER SOFT EL
U+A667    CYRILLIC SMALL LETTER SOFT EM
U+A669    CYRILLIC SMALL LETTER MONOCULAR O
U+A66B    CYRILLIC SMALL LETTER BINOCULAR O
U+A66D    CYRILLIC SMALL LETTER DOUBLE MONOCULAR O
U+A681    CYRILLIC SMALL LETTER DWE
U+A683    CYRILLIC SMALL LETTER DZWE
U+A685    CYRILLIC SMALL LETTER ZHWE
U+A687    CYRILLIC SMALL LETTER CCHE
U+A689    CYRILLIC SMALL LETTER DZZE
U+A68B    CYRILLIC SMALL LETTER TE WITH MIDDLE HOOK
U+A68D    CYRILLIC SMALL LETTER TWE
U+A68F    CYRILLIC SMALL LETTER TSWE
U+A691    CYRILLIC SMALL LETTER TSSE
U+A693    CYRILLIC SMALL LETTER TCHE
U+A695    CYRILLIC SMALL LETTER HWE
U+A697    CYRILLIC SMALL LETTER SHWE
U+A699    CYRILLIC SMALL LETTER DOUBLE O
U+A69B    CYRILLIC SMALL LETTER CROSSED O
U+A723    LATIN SMALL LETTER EGYPTOLOGICAL ALEF
U+A725    LATIN SMALL LETTER EGYPTOLOGICAL AIN
U+A727    LATIN SMALL LETTER HENG
U+A729    LATIN SMALL LETTER TZ
U+A72B    LATIN SMALL LETTER TRESILLO
U+A72D    LATIN SMALL LETTER CUATRILLO
U+A72F    LATIN SMALL LETTER CUATRILLO WITH COMMA
U+A730    LATIN LETTER SMALL CAPITAL F
U+A731    LATIN LETTER SMALL CAPITAL S
U+A733    LATIN SMALL LETTER AA
U+A735    LATIN SMALL LETTER AO
U+A737    LATIN SMALL LETTER AU
U+A739    LATIN SMALL LETTER AV
U+A73B    LATIN SMALL LETTER AV WITH HORIZONTAL BAR
U+A73D    LATIN SMALL LETTER AY
U+A73F    LATIN SMALL LETTER REVERSED C WITH DOT
U+A741    LATIN SMALL LETTER K WITH STROKE
U+A743    LATIN SMALL LETTER K WITH DIAGONAL STROKE
U+A745    LATIN SMALL LETTER K WITH STROKE AND DIAGONAL STROKE
U+A747    LATIN SMALL LETTER BROKEN L
U+A749    LATIN SMALL LETTER L WITH HIGH STROKE
U+A74B    LATIN SMALL LETTER O WITH LONG STROKE OVERLAY
U+A74D    LATIN SMALL LETTER O WITH LOOP
U+A74F    LATIN SMALL LETTER OO
U+A751    LATIN SMALL LETTER P WITH STROKE THROUGH DESCENDER
U+A753    LATIN SMALL LETTER P WITH FLOURISH
U+A755    LATIN SMALL LETTER P WITH SQUIRREL TAIL
U+A757    LATIN SMALL LETTER Q WITH STROKE THROUGH DESCENDER
U+A759    LATIN SMALL LETTER Q WITH DIAGONAL STROKE
U+A75B    LATIN SMALL LETTER R ROTUNDA
U+A75D    LATIN SMALL LETTER RUM ROTUNDA
U+A75F    LATIN SMALL LETTER V WITH DIAGONAL STROKE
U+A761    LATIN SMALL LETTER VY
U+A763    LATIN SMALL LETTER VISIGOTHIC Z
U+A765    LATIN SMALL LETTER THORN WITH STROKE
U+A767    LATIN SMALL LETTER THORN WITH STROKE THROUGH DESCENDER
U+A769    LATIN SMALL LETTER VEND
U+A76B    LATIN SMALL LETTER ET
U+A76D    LATIN SMALL LETTER IS
U+A76F    LATIN SMALL LETTER CON
U+A771    LATIN SMALL LETTER DUM
U+A772    LATIN SMALL LETTER LUM
U+A773    LATIN SMALL LETTER MUM
U+A774    LATIN SMALL LETTER NUM
U+A775    LATIN SMALL LETTER RUM
U+A776    LATIN LETTER SMALL CAPITAL RUM
U+A777    LATIN SMALL LETTER TUM
U+A778    LATIN SMALL LETTER UM
U+A77A    LATIN SMALL LETTER INSULAR D
U+A77C    LATIN SMALL LETTER INSULAR F
U+A77F    LATIN SMALL LETTER TURNED INSULAR G
U+A781    LATIN SMALL LETTER TURNED L
U+A783    LATIN SMALL LETTER INSULAR R
U+A785    LATIN SMALL LETTER INSULAR S
U+A787    LATIN SMALL LETTER INSULAR T
U+A78C    LATIN SMALL LETTER SALTILLO
U+A78E    LATIN SMALL LETTER L WITH RETROFLEX HOOK AND BELT
U+A791    LATIN SMALL LETTER N WITH DESCENDER
U+A793    LATIN SMALL LETTER C WITH BAR
U+A794    LATIN SMALL LETTER C WITH PALATAL HOOK
U+A795    LATIN SMALL LETTER H WITH PALATAL HOOK
U+A797    LATIN SMALL LETTER B WITH FLOURISH
U+A799    LATIN SMALL LETTER F WITH STROKE
U+A79B    LATIN SMALL LETTER VOLAPUK AE
U+A79D    LATIN SMALL LETTER VOLAPUK OE
U+A79F    LATIN SMALL LETTER VOLAPUK UE
U+A7A1    LATIN SMALL LETTER G WITH OBLIQUE STROKE
U+A7A3    LATIN SMALL LETTER K WITH OBLIQUE STROKE
U+A7A5    LATIN SMALL LETTER N WITH OBLIQUE STROKE
U+A7A7    LATIN SMALL LETTER R WITH OBLIQUE STROKE
U+A7A9    LATIN SMALL LETTER S WITH OBLIQUE STROKE
U+A7B5    LATIN SMALL LETTER BETA
U+A7B7    LATIN SMALL LETTER OMEGA
U+A7FA    LATIN LETTER SMALL CAPITAL TURNED M
U+AB30    LATIN SMALL LETTER BARRED ALPHA
U+AB31    LATIN SMALL LETTER A REVERSED-SCHWA
U+AB32    LATIN SMALL LETTER BLACKLETTER E
U+AB33    LATIN SMALL LETTER BARRED E
U+AB34    LATIN SMALL LETTER E WITH FLOURISH
U+AB35    LATIN SMALL LETTER LENIS F
U+AB36    LATIN SMALL LETTER SCRIPT G WITH CROSSED-TAIL
U+AB37    LATIN SMALL LETTER L WITH INVERTED LAZY S
U+AB38    LATIN SMALL LETTER L WITH DOUBLE MIDDLE TILDE
U+AB39    LATIN SMALL LETTER L WITH MIDDLE RING
U+AB3A    LATIN SMALL LETTER M WITH CROSSED-TAIL
U+AB3B    LATIN SMALL LETTER N WITH CROSSED-TAIL
U+AB3C    LATIN SMALL LETTER ENG WITH CROSSED-TAIL
U+AB3D    LATIN SMALL LETTER BLACKLETTER O
U+AB3E    LATIN SMALL LETTER BLACKLETTER O WITH STROKE
U+AB3F    LATIN SMALL LETTER OPEN O WITH STROKE
U+AB40    LATIN SMALL LETTER INVERTED OE
U+AB41    LATIN SMALL LETTER TURNED OE WITH STROKE
U+AB42    LATIN SMALL LETTER TURNED OE WITH HORIZONTAL STROKE
U+AB43    LATIN SMALL LETTER TURNED O OPEN-O
U+AB44    LATIN SMALL LETTER TURNED O OPEN-O WITH STROKE
U+AB45    LATIN SMALL LETTER STIRRUP R
U+AB46    LATIN LETTER SMALL CAPITAL R WITH RIGHT LEG
U+AB47    LATIN SMALL LETTER R WITHOUT HANDLE
U+AB48    LATIN SMALL LETTER DOUBLE R
U+AB49    LATIN SMALL LETTER R WITH CROSSED-TAIL
U+AB4A    LATIN SMALL LETTER DOUBLE R WITH CROSSED-TAIL
U+AB4B    LATIN SMALL LETTER SCRIPT R
U+AB4C    LATIN SMALL LETTER SCRIPT R WITH RING
U+AB4D    LATIN SMALL LETTER BASELINE ESH
U+AB4E    LATIN SMALL LETTER U WITH SHORT RIGHT LEG
U+AB4F    LATIN SMALL LETTER U BAR WITH SHORT RIGHT LEG
U+AB50    LATIN SMALL LETTER UI
U+AB51    LATIN SMALL LETTER TURNED UI
U+AB52    LATIN SMALL LETTER U WITH LEFT HOOK
U+AB53    LATIN SMALL LETTER CHI
U+AB54    LATIN SMALL LETTER CHI WITH LOW RIGHT RING
U+AB55    LATIN SMALL LETTER CHI WITH LOW LEFT SERIF
U+AB56    LATIN SMALL LETTER X WITH LOW RIGHT RING
U+AB57    LATIN SMALL LETTER X WITH LONG LEFT LEG
U+AB58    LATIN SMALL LETTER X WITH LONG LEFT LEG AND LOW RIGHT RING
U+AB59    LATIN SMALL LETTER X WITH LONG LEFT LEG WITH SERIF
U+AB5A    LATIN SMALL LETTER Y WITH SHORT RIGHT LEG
U+AB60    LATIN SMALL LETTER SAKHA YAT
U+AB61    LATIN SMALL LETTER IOTIFIED E
U+AB62    LATIN SMALL LETTER OPEN OE
U+AB63    LATIN SMALL LETTER UO
U+AB64    LATIN SMALL LETTER INVERTED ALPHA
U+AB65    GREEK LETTER SMALL CAPITAL OMEGA
U+AB70    CHEROKEE SMALL LETTER A
U+AB71    CHEROKEE SMALL LETTER E
U+AB72    CHEROKEE SMALL LETTER I
U+AB73    CHEROKEE SMALL LETTER O
U+AB74    CHEROKEE SMALL LETTER U
U+AB75    CHEROKEE SMALL LETTER V
U+AB76    CHEROKEE SMALL LETTER GA
U+AB77    CHEROKEE SMALL LETTER KA
U+AB78    CHEROKEE SMALL LETTER GE
U+AB79    CHEROKEE SMALL LETTER GI
U+AB7A    CHEROKEE SMALL LETTER GO
U+AB7B    CHEROKEE SMALL LETTER GU
U+AB7C    CHEROKEE SMALL LETTER GV
U+AB7D    CHEROKEE SMALL LETTER HA
U+AB7E    CHEROKEE SMALL LETTER HE
U+AB7F    CHEROKEE SMALL LETTER HI
U+AB80    CHEROKEE SMALL LETTER HO
U+AB81    CHEROKEE SMALL LETTER HU
U+AB82    CHEROKEE SMALL LETTER HV
U+AB83    CHEROKEE SMALL LETTER LA
U+AB84    CHEROKEE SMALL LETTER LE
U+AB85    CHEROKEE SMALL LETTER LI
U+AB86    CHEROKEE SMALL LETTER LO
U+AB87    CHEROKEE SMALL LETTER LU
U+AB88    CHEROKEE SMALL LETTER LV
U+AB89    CHEROKEE SMALL LETTER MA
U+AB8A    CHEROKEE SMALL LETTER ME
U+AB8B    CHEROKEE SMALL LETTER MI
U+AB8C    CHEROKEE SMALL LETTER MO
U+AB8D    CHEROKEE SMALL LETTER MU
U+AB8E    CHEROKEE SMALL LETTER NA
U+AB8F    CHEROKEE SMALL LETTER HNA
U+AB90    CHEROKEE SMALL LETTER NAH
U+AB91    CHEROKEE SMALL LETTER NE
U+AB92    CHEROKEE SMALL LETTER NI
U+AB93    CHEROKEE SMALL LETTER NO
U+AB94    CHEROKEE SMALL LETTER NU
U+AB95    CHEROKEE SMALL LETTER NV
U+AB96    CHEROKEE SMALL LETTER QUA
U+AB97    CHEROKEE SMALL LETTER QUE
U+AB98    CHEROKEE SMALL LETTER QUI
U+AB99    CHEROKEE SMALL LETTER QUO
U+AB9A    CHEROKEE SMALL LETTER QUU
U+AB9B    CHEROKEE SMALL LETTER QUV
U+AB9C    CHEROKEE SMALL LETTER SA
U+AB9D    CHEROKEE SMALL LETTER S
U+AB9E    CHEROKEE SMALL LETTER SE
U+AB9F    CHEROKEE SMALL LETTER SI
U+ABA0    CHEROKEE SMALL LETTER SO
U+ABA1    CHEROKEE SMALL LETTER SU
U+ABA2    CHEROKEE SMALL LETTER SV
U+ABA3    CHEROKEE SMALL LETTER DA
U+ABA4    CHEROKEE SMALL LETTER TA
U+ABA5    CHEROKEE SMALL LETTER DE
U+ABA6    CHEROKEE SMALL LETTER TE
U+ABA7    CHEROKEE SMALL LETTER DI
U+ABA8    CHEROKEE SMALL LETTER TI
U+ABA9    CHEROKEE SMALL LETTER DO
U+ABAA    CHEROKEE SMALL LETTER DU
U+ABAB    CHEROKEE SMALL LETTER DV
U+ABAC    CHEROKEE SMALL LETTER DLA
U+ABAD    CHEROKEE SMALL LETTER TLA
U+ABAE    CHEROKEE SMALL LETTER TLE
U+ABAF    CHEROKEE SMALL LETTER TLI
U+ABB0    CHEROKEE SMALL LETTER TLO
U+ABB1    CHEROKEE SMALL LETTER TLU
U+ABB2    CHEROKEE SMALL LETTER TLV
U+ABB3    CHEROKEE SMALL LETTER TSA
U+ABB4    CHEROKEE SMALL LETTER TSE
U+ABB5    CHEROKEE SMALL LETTER TSI
U+ABB6    CHEROKEE SMALL LETTER TSO
U+ABB7    CHEROKEE SMALL LETTER TSU
U+ABB8    CHEROKEE SMALL LETTER TSV
U+ABB9    CHEROKEE SMALL LETTER WA
U+ABBA    CHEROKEE SMALL LETTER WE
U+ABBB    CHEROKEE SMALL LETTER WI
U+ABBC    CHEROKEE SMALL LETTER WO
U+ABBD    CHEROKEE SMALL LETTER WU
U+ABBE    CHEROKEE SMALL LETTER WV
U+ABBF    CHEROKEE SMALL LETTER YA
U+FB00    LATIN SMALL LIGATURE FF
U+FB01    LATIN SMALL LIGATURE FI
U+FB02    LATIN SMALL LIGATURE FL
U+FB03    LATIN SMALL LIGATURE FFI
U+FB04    LATIN SMALL LIGATURE FFL
U+FB05    LATIN SMALL LIGATURE LONG S T
U+FB06    LATIN SMALL LIGATURE ST
U+FB13    ARMENIAN SMALL LIGATURE MEN NOW
U+FB14    ARMENIAN SMALL LIGATURE MEN ECH
U+FB15    ARMENIAN SMALL LIGATURE MEN INI
U+FB16    ARMENIAN SMALL LIGATURE VEW NOW
U+FB17    ARMENIAN SMALL LIGATURE MEN XEH
U+FF41    FULLWIDTH LATIN SMALL LETTER A
U+FF42    FULLWIDTH LATIN SMALL LETTER B
U+FF43    FULLWIDTH LATIN SMALL LETTER C
U+FF44    FULLWIDTH LATIN SMALL LETTER D
U+FF45    FULLWIDTH LATIN SMALL LETTER E
U+FF46    FULLWIDTH LATIN SMALL LETTER F
U+FF47    FULLWIDTH LATIN SMALL LETTER G
U+FF48    FULLWIDTH LATIN SMALL LETTER H
U+FF49    FULLWIDTH LATIN SMALL LETTER I
U+FF4A    FULLWIDTH LATIN SMALL LETTER J
U+FF4B    FULLWIDTH LATIN SMALL LETTER K
U+FF4C    FULLWIDTH LATIN SMALL LETTER L
U+FF4D    FULLWIDTH LATIN SMALL LETTER M
U+FF4E    FULLWIDTH LATIN SMALL LETTER N
U+FF4F    FULLWIDTH LATIN SMALL LETTER O
U+FF50    FULLWIDTH LATIN SMALL LETTER P
U+FF51    FULLWIDTH LATIN SMALL LETTER Q
U+FF52    FULLWIDTH LATIN SMALL LETTER R
U+FF53    FULLWIDTH LATIN SMALL LETTER S
U+FF54    FULLWIDTH LATIN SMALL LETTER T
U+FF55    FULLWIDTH LATIN SMALL LETTER U
U+FF56    FULLWIDTH LATIN SMALL LETTER V
U+FF57    FULLWIDTH LATIN SMALL LETTER W
U+FF58    FULLWIDTH LATIN SMALL LETTER X
U+FF59    FULLWIDTH LATIN SMALL LETTER Y
U+FF5A    FULLWIDTH LATIN SMALL LETTER Z
U+10428    DESERET SMALL LETTER LONG I
U+10429    DESERET SMALL LETTER LONG E
U+1042A    DESERET SMALL LETTER LONG A
U+1042B    DESERET SMALL LETTER LONG AH
U+1042C    DESERET SMALL LETTER LONG O
U+1042D    DESERET SMALL LETTER LONG OO
U+1042E    DESERET SMALL LETTER SHORT I
U+1042F    DESERET SMALL LETTER SHORT E
U+10430    DESERET SMALL LETTER SHORT A
U+10431    DESERET SMALL LETTER SHORT AH
U+10432    DESERET SMALL LETTER SHORT O
U+10433    DESERET SMALL LETTER SHORT OO
U+10434    DESERET SMALL LETTER AY
U+10435    DESERET SMALL LETTER OW
U+10436    DESERET SMALL LETTER WU
U+10437    DESERET SMALL LETTER YEE
U+10438    DESERET SMALL LETTER H
U+10439    DESERET SMALL LETTER PEE
U+1043A    DESERET SMALL LETTER BEE
U+1043B    DESERET SMALL LETTER TEE
U+1043C    DESERET SMALL LETTER DEE
U+1043D    DESERET SMALL LETTER CHEE
U+1043E    DESERET SMALL LETTER JEE
U+1043F    DESERET SMALL LETTER KAY
U+10440    DESERET SMALL LETTER GAY
U+10441    DESERET SMALL LETTER EF
U+10442    DESERET SMALL LETTER VEE
U+10443    DESERET SMALL LETTER ETH
U+10444    DESERET SMALL LETTER THEE
U+10445    DESERET SMALL LETTER ES
U+10446    DESERET SMALL LETTER ZEE
U+10447    DESERET SMALL LETTER ESH
U+10448    DESERET SMALL LETTER ZHEE
U+10449    DESERET SMALL LETTER ER
U+1044A    DESERET SMALL LETTER EL
U+1044B    DESERET SMALL LETTER EM
U+1044C    DESERET SMALL LETTER EN
U+1044D    DESERET SMALL LETTER ENG
U+1044E    DESERET SMALL LETTER OI
U+1044F    DESERET SMALL LETTER EW
U+10CC0    OLD HUNGARIAN SMALL LETTER A
U+10CC1    OLD HUNGARIAN SMALL LETTER AA
U+10CC2    OLD HUNGARIAN SMALL LETTER EB
U+10CC3    OLD HUNGARIAN SMALL LETTER AMB
U+10CC4    OLD HUNGARIAN SMALL LETTER EC
U+10CC5    OLD HUNGARIAN SMALL LETTER ENC
U+10CC6    OLD HUNGARIAN SMALL LETTER ECS
U+10CC7    OLD HUNGARIAN SMALL LETTER ED
U+10CC8    OLD HUNGARIAN SMALL LETTER AND
U+10CC9    OLD HUNGARIAN SMALL LETTER E
U+10CCA    OLD HUNGARIAN SMALL LETTER CLOSE E
U+10CCB    OLD HUNGARIAN SMALL LETTER EE
U+10CCC    OLD HUNGARIAN SMALL LETTER EF
U+10CCD    OLD HUNGARIAN SMALL LETTER EG
U+10CCE    OLD HUNGARIAN SMALL LETTER EGY
U+10CCF    OLD HUNGARIAN SMALL LETTER EH
U+10CD0    OLD HUNGARIAN SMALL LETTER I
U+10CD1    OLD HUNGARIAN SMALL LETTER II
U+10CD2    OLD HUNGARIAN SMALL LETTER EJ
U+10CD3    OLD HUNGARIAN SMALL LETTER EK
U+10CD4    OLD HUNGARIAN SMALL LETTER AK
U+10CD5    OLD HUNGARIAN SMALL LETTER UNK
U+10CD6    OLD HUNGARIAN SMALL LETTER EL
U+10CD7    OLD HUNGARIAN SMALL LETTER ELY
U+10CD8    OLD HUNGARIAN SMALL LETTER EM
U+10CD9    OLD HUNGARIAN SMALL LETTER EN
U+10CDA    OLD HUNGARIAN SMALL LETTER ENY
U+10CDB    OLD HUNGARIAN SMALL LETTER O
U+10CDC    OLD HUNGARIAN SMALL LETTER OO
U+10CDD    OLD HUNGARIAN SMALL LETTER NIKOLSBURG OE
U+10CDE    OLD HUNGARIAN SMALL LETTER RUDIMENTA OE
U+10CDF    OLD HUNGARIAN SMALL LETTER OEE
U+10CE0    OLD HUNGARIAN SMALL LETTER EP
U+10CE1    OLD HUNGARIAN SMALL LETTER EMP
U+10CE2    OLD HUNGARIAN SMALL LETTER ER
U+10CE3    OLD HUNGARIAN SMALL LETTER SHORT ER
U+10CE4    OLD HUNGARIAN SMALL LETTER ES
U+10CE5    OLD HUNGARIAN SMALL LETTER ESZ
U+10CE6    OLD HUNGARIAN SMALL LETTER ET
U+10CE7    OLD HUNGARIAN SMALL LETTER ENT
U+10CE8    OLD HUNGARIAN SMALL LETTER ETY
U+10CE9    OLD HUNGARIAN SMALL LETTER ECH
U+10CEA    OLD HUNGARIAN SMALL LETTER U
U+10CEB    OLD HUNGARIAN SMALL LETTER UU
U+10CEC    OLD HUNGARIAN SMALL LETTER NIKOLSBURG UE
U+10CED    OLD HUNGARIAN SMALL LETTER RUDIMENTA UE
U+10CEE    OLD HUNGARIAN SMALL LETTER EV
U+10CEF    OLD HUNGARIAN SMALL LETTER EZ
U+10CF0    OLD HUNGARIAN SMALL LETTER EZS
U+10CF1    OLD HUNGARIAN SMALL LETTER ENT-SHAPED SIGN
U+10CF2    OLD HUNGARIAN SMALL LETTER US
U+118C0    WARANG CITI SMALL LETTER NGAA
U+118C1    WARANG CITI SMALL LETTER A
U+118C2    WARANG CITI SMALL LETTER WI
U+118C3    WARANG CITI SMALL LETTER YU
U+118C4    WARANG CITI SMALL LETTER YA
U+118C5    WARANG CITI SMALL LETTER YO
U+118C6    WARANG CITI SMALL LETTER II
U+118C7    WARANG CITI SMALL LETTER UU
U+118C8    WARANG CITI SMALL LETTER E
U+118C9    WARANG CITI SMALL LETTER O
U+118CA    WARANG CITI SMALL LETTER ANG
U+118CB    WARANG CITI SMALL LETTER GA
U+118CC    WARANG CITI SMALL LETTER KO
U+118CD    WARANG CITI SMALL LETTER ENY
U+118CE    WARANG CITI SMALL LETTER YUJ
U+118CF    WARANG CITI SMALL LETTER UC
U+118D0    WARANG CITI SMALL LETTER ENN
U+118D1    WARANG CITI SMALL LETTER ODD
U+118D2    WARANG CITI SMALL LETTER TTE
U+118D3    WARANG CITI SMALL LETTER NUNG
U+118D4    WARANG CITI SMALL LETTER DA
U+118D5    WARANG CITI SMALL LETTER AT
U+118D6    WARANG CITI SMALL LETTER AM
U+118D7    WARANG CITI SMALL LETTER BU
U+118D8    WARANG CITI SMALL LETTER PU
U+118D9    WARANG CITI SMALL LETTER HIYO
U+118DA    WARANG CITI SMALL LETTER HOLO
U+118DB    WARANG CITI SMALL LETTER HORR
U+118DC    WARANG CITI SMALL LETTER HAR
U+118DD    WARANG CITI SMALL LETTER SSUU
U+118DE    WARANG CITI SMALL LETTER SII
U+118DF    WARANG CITI SMALL LETTER VIYO
U+1D41A    MATHEMATICAL BOLD SMALL A
U+1D41B    MATHEMATICAL BOLD SMALL B
U+1D41C    MATHEMATICAL BOLD SMALL C
U+1D41D    MATHEMATICAL BOLD SMALL D
U+1D41E    MATHEMATICAL BOLD SMALL E
U+1D41F    MATHEMATICAL BOLD SMALL F
U+1D420    MATHEMATICAL BOLD SMALL G
U+1D421    MATHEMATICAL BOLD SMALL H
U+1D422    MATHEMATICAL BOLD SMALL I
U+1D423    MATHEMATICAL BOLD SMALL J
U+1D424    MATHEMATICAL BOLD SMALL K
U+1D425    MATHEMATICAL BOLD SMALL L
U+1D426    MATHEMATICAL BOLD SMALL M
U+1D427    MATHEMATICAL BOLD SMALL N
U+1D428    MATHEMATICAL BOLD SMALL O
U+1D429    MATHEMATICAL BOLD SMALL P
U+1D42A    MATHEMATICAL BOLD SMALL Q
U+1D42B    MATHEMATICAL BOLD SMALL R
U+1D42C    MATHEMATICAL BOLD SMALL S
U+1D42D    MATHEMATICAL BOLD SMALL T
U+1D42E    MATHEMATICAL BOLD SMALL U
U+1D42F    MATHEMATICAL BOLD SMALL V
U+1D430    MATHEMATICAL BOLD SMALL W
U+1D431    MATHEMATICAL BOLD SMALL X
U+1D432    MATHEMATICAL BOLD SMALL Y
U+1D433    MATHEMATICAL BOLD SMALL Z
U+1D44E    MATHEMATICAL ITALIC SMALL A
U+1D44F    MATHEMATICAL ITALIC SMALL B
U+1D450    MATHEMATICAL ITALIC SMALL C
U+1D451    MATHEMATICAL ITALIC SMALL D
U+1D452    MATHEMATICAL ITALIC SMALL E
U+1D453    MATHEMATICAL ITALIC SMALL F
U+1D454    MATHEMATICAL ITALIC SMALL G
U+1D456    MATHEMATICAL ITALIC SMALL I
U+1D457    MATHEMATICAL ITALIC SMALL J
U+1D458    MATHEMATICAL ITALIC SMALL K
U+1D459    MATHEMATICAL ITALIC SMALL L
U+1D45A    MATHEMATICAL ITALIC SMALL M
U+1D45B    MATHEMATICAL ITALIC SMALL N
U+1D45C    MATHEMATICAL ITALIC SMALL O
U+1D45D    MATHEMATICAL ITALIC SMALL P
U+1D45E    MATHEMATICAL ITALIC SMALL Q
U+1D45F    MATHEMATICAL ITALIC SMALL R
U+1D460    MATHEMATICAL ITALIC SMALL S
U+1D461    MATHEMATICAL ITALIC SMALL T
U+1D462    MATHEMATICAL ITALIC SMALL U
U+1D463    MATHEMATICAL ITALIC SMALL V
U+1D464    MATHEMATICAL ITALIC SMALL W
U+1D465    MATHEMATICAL ITALIC SMALL X
U+1D466    MATHEMATICAL ITALIC SMALL Y
U+1D467    MATHEMATICAL ITALIC SMALL Z
U+1D482    MATHEMATICAL BOLD ITALIC SMALL A
U+1D483    MATHEMATICAL BOLD ITALIC SMALL B
U+1D484    MATHEMATICAL BOLD ITALIC SMALL C
U+1D485    MATHEMATICAL BOLD ITALIC SMALL D
U+1D486    MATHEMATICAL BOLD ITALIC SMALL E
U+1D487    MATHEMATICAL BOLD ITALIC SMALL F
U+1D488    MATHEMATICAL BOLD ITALIC SMALL G
U+1D489    MATHEMATICAL BOLD ITALIC SMALL H
U+1D48A    MATHEMATICAL BOLD ITALIC SMALL I
U+1D48B    MATHEMATICAL BOLD ITALIC SMALL J
U+1D48C    MATHEMATICAL BOLD ITALIC SMALL K
U+1D48D    MATHEMATICAL BOLD ITALIC SMALL L
U+1D48E    MATHEMATICAL BOLD ITALIC SMALL M
U+1D48F    MATHEMATICAL BOLD ITALIC SMALL N
U+1D490    MATHEMATICAL BOLD ITALIC SMALL O
U+1D491    MATHEMATICAL BOLD ITALIC SMALL P
U+1D492    MATHEMATICAL BOLD ITALIC SMALL Q
U+1D493    MATHEMATICAL BOLD ITALIC SMALL R
U+1D494    MATHEMATICAL BOLD ITALIC SMALL S
U+1D495    MATHEMATICAL BOLD ITALIC SMALL T
U+1D496    MATHEMATICAL BOLD ITALIC SMALL U
U+1D497    MATHEMATICAL BOLD ITALIC SMALL V
U+1D498    MATHEMATICAL BOLD ITALIC SMALL W
U+1D499    MATHEMATICAL BOLD ITALIC SMALL X
U+1D49A    MATHEMATICAL BOLD ITALIC SMALL Y
U+1D49B    MATHEMATICAL BOLD ITALIC SMALL Z
U+1D4B6    MATHEMATICAL SCRIPT SMALL A
U+1D4B7    MATHEMATICAL SCRIPT SMALL B
U+1D4B8    MATHEMATICAL SCRIPT SMALL C
U+1D4B9    MATHEMATICAL SCRIPT SMALL D
U+1D4BB    MATHEMATICAL SCRIPT SMALL F
U+1D4BD    MATHEMATICAL SCRIPT SMALL H
U+1D4BE    MATHEMATICAL SCRIPT SMALL I
U+1D4BF    MATHEMATICAL SCRIPT SMALL J
U+1D4C0    MATHEMATICAL SCRIPT SMALL K
U+1D4C1    MATHEMATICAL SCRIPT SMALL L
U+1D4C2    MATHEMATICAL SCRIPT SMALL M
U+1D4C3    MATHEMATICAL SCRIPT SMALL N
U+1D4C5    MATHEMATICAL SCRIPT SMALL P
U+1D4C6    MATHEMATICAL SCRIPT SMALL Q
U+1D4C7    MATHEMATICAL SCRIPT SMALL R
U+1D4C8    MATHEMATICAL SCRIPT SMALL S
U+1D4C9    MATHEMATICAL SCRIPT SMALL T
U+1D4CA    MATHEMATICAL SCRIPT SMALL U
U+1D4CB    MATHEMATICAL SCRIPT SMALL V
U+1D4CC    MATHEMATICAL SCRIPT SMALL W
U+1D4CD    MATHEMATICAL SCRIPT SMALL X
U+1D4CE    MATHEMATICAL SCRIPT SMALL Y
U+1D4CF    MATHEMATICAL SCRIPT SMALL Z
U+1D4EA    MATHEMATICAL BOLD SCRIPT SMALL A
U+1D4EB    MATHEMATICAL BOLD SCRIPT SMALL B
U+1D4EC    MATHEMATICAL BOLD SCRIPT SMALL C
U+1D4ED    MATHEMATICAL BOLD SCRIPT SMALL D
U+1D4EE    MATHEMATICAL BOLD SCRIPT SMALL E
U+1D4EF    MATHEMATICAL BOLD SCRIPT SMALL F
U+1D4F0    MATHEMATICAL BOLD SCRIPT SMALL G
U+1D4F1    MATHEMATICAL BOLD SCRIPT SMALL H
U+1D4F2    MATHEMATICAL BOLD SCRIPT SMALL I
U+1D4F3    MATHEMATICAL BOLD SCRIPT SMALL J
U+1D4F4    MATHEMATICAL BOLD SCRIPT SMALL K
U+1D4F5    MATHEMATICAL BOLD SCRIPT SMALL L
U+1D4F6    MATHEMATICAL BOLD SCRIPT SMALL M
U+1D4F7    MATHEMATICAL BOLD SCRIPT SMALL N
U+1D4F8    MATHEMATICAL BOLD SCRIPT SMALL O
U+1D4F9    MATHEMATICAL BOLD SCRIPT SMALL P
U+1D4FA    MATHEMATICAL BOLD SCRIPT SMALL Q
U+1D4FB    MATHEMATICAL BOLD SCRIPT SMALL R
U+1D4FC    MATHEMATICAL BOLD SCRIPT SMALL S
U+1D4FD    MATHEMATICAL BOLD SCRIPT SMALL T
U+1D4FE    MATHEMATICAL BOLD SCRIPT SMALL U
U+1D4FF    MATHEMATICAL BOLD SCRIPT SMALL V
U+1D500    MATHEMATICAL BOLD SCRIPT SMALL W
U+1D501    MATHEMATICAL BOLD SCRIPT SMALL X
U+1D502    MATHEMATICAL BOLD SCRIPT SMALL Y
U+1D503    MATHEMATICAL BOLD SCRIPT SMALL Z
U+1D51E    MATHEMATICAL FRAKTUR SMALL A
U+1D51F    MATHEMATICAL FRAKTUR SMALL B
U+1D520    MATHEMATICAL FRAKTUR SMALL C
U+1D521    MATHEMATICAL FRAKTUR SMALL D
U+1D522    MATHEMATICAL FRAKTUR SMALL E
U+1D523    MATHEMATICAL FRAKTUR SMALL F
U+1D524    MATHEMATICAL FRAKTUR SMALL G
U+1D525    MATHEMATICAL FRAKTUR SMALL H
U+1D526    MATHEMATICAL FRAKTUR SMALL I
U+1D527    MATHEMATICAL FRAKTUR SMALL J
U+1D528    MATHEMATICAL FRAKTUR SMALL K
U+1D529    MATHEMATICAL FRAKTUR SMALL L
U+1D52A    MATHEMATICAL FRAKTUR SMALL M
U+1D52B    MATHEMATICAL FRAKTUR SMALL N
U+1D52C    MATHEMATICAL FRAKTUR SMALL O
U+1D52D    MATHEMATICAL FRAKTUR SMALL P
U+1D52E    MATHEMATICAL FRAKTUR SMALL Q
U+1D52F    MATHEMATICAL FRAKTUR SMALL R
U+1D530    MATHEMATICAL FRAKTUR SMALL S
U+1D531    MATHEMATICAL FRAKTUR SMALL T
U+1D532    MATHEMATICAL FRAKTUR SMALL U
U+1D533    MATHEMATICAL FRAKTUR SMALL V
U+1D534    MATHEMATICAL FRAKTUR SMALL W
U+1D535    MATHEMATICAL FRAKTUR SMALL X
U+1D536    MATHEMATICAL FRAKTUR SMALL Y
U+1D537    MATHEMATICAL FRAKTUR SMALL Z
U+1D552    MATHEMATICAL DOUBLE-STRUCK SMALL A
U+1D553    MATHEMATICAL DOUBLE-STRUCK SMALL B
U+1D554    MATHEMATICAL DOUBLE-STRUCK SMALL C
U+1D555    MATHEMATICAL DOUBLE-STRUCK SMALL D
U+1D556    MATHEMATICAL DOUBLE-STRUCK SMALL E
U+1D557    MATHEMATICAL DOUBLE-STRUCK SMALL F
U+1D558    MATHEMATICAL DOUBLE-STRUCK SMALL G
U+1D559    MATHEMATICAL DOUBLE-STRUCK SMALL H
U+1D55A    MATHEMATICAL DOUBLE-STRUCK SMALL I
U+1D55B    MATHEMATICAL DOUBLE-STRUCK SMALL J
U+1D55C    MATHEMATICAL DOUBLE-STRUCK SMALL K
U+1D55D    MATHEMATICAL DOUBLE-STRUCK SMALL L
U+1D55E    MATHEMATICAL DOUBLE-STRUCK SMALL M
U+1D55F    MATHEMATICAL DOUBLE-STRUCK SMALL N
U+1D560    MATHEMATICAL DOUBLE-STRUCK SMALL O
U+1D561    MATHEMATICAL DOUBLE-STRUCK SMALL P
U+1D562    MATHEMATICAL DOUBLE-STRUCK SMALL Q
U+1D563    MATHEMATICAL DOUBLE-STRUCK SMALL R
U+1D564    MATHEMATICAL DOUBLE-STRUCK SMALL S
U+1D565    MATHEMATICAL DOUBLE-STRUCK SMALL T
U+1D566    MATHEMATICAL DOUBLE-STRUCK SMALL U
U+1D567    MATHEMATICAL DOUBLE-STRUCK SMALL V
U+1D568    MATHEMATICAL DOUBLE-STRUCK SMALL W
U+1D569    MATHEMATICAL DOUBLE-STRUCK SMALL X
U+1D56A    MATHEMATICAL DOUBLE-STRUCK SMALL Y
U+1D56B    MATHEMATICAL DOUBLE-STRUCK SMALL Z
U+1D586    MATHEMATICAL BOLD FRAKTUR SMALL A
U+1D587    MATHEMATICAL BOLD FRAKTUR SMALL B
U+1D588    MATHEMATICAL BOLD FRAKTUR SMALL C
U+1D589    MATHEMATICAL BOLD FRAKTUR SMALL D
U+1D58A    MATHEMATICAL BOLD FRAKTUR SMALL E
U+1D58B    MATHEMATICAL BOLD FRAKTUR SMALL F
U+1D58C    MATHEMATICAL BOLD FRAKTUR SMALL G
U+1D58D    MATHEMATICAL BOLD FRAKTUR SMALL H
U+1D58E    MATHEMATICAL BOLD FRAKTUR SMALL I
U+1D58F    MATHEMATICAL BOLD FRAKTUR SMALL J
U+1D590    MATHEMATICAL BOLD FRAKTUR SMALL K
U+1D591    MATHEMATICAL BOLD FRAKTUR SMALL L
U+1D592    MATHEMATICAL BOLD FRAKTUR SMALL M
U+1D593    MATHEMATICAL BOLD FRAKTUR SMALL N
U+1D594    MATHEMATICAL BOLD FRAKTUR SMALL O
U+1D595    MATHEMATICAL BOLD FRAKTUR SMALL P
U+1D596    MATHEMATICAL BOLD FRAKTUR SMALL Q
U+1D597    MATHEMATICAL BOLD FRAKTUR SMALL R
U+1D598    MATHEMATICAL BOLD FRAKTUR SMALL S
U+1D599    MATHEMATICAL BOLD FRAKTUR SMALL T
U+1D59A    MATHEMATICAL BOLD FRAKTUR SMALL U
U+1D59B    MATHEMATICAL BOLD FRAKTUR SMALL V
U+1D59C    MATHEMATICAL BOLD FRAKTUR SMALL W
U+1D59D    MATHEMATICAL BOLD FRAKTUR SMALL X
U+1D59E    MATHEMATICAL BOLD FRAKTUR SMALL Y
U+1D59F    MATHEMATICAL BOLD FRAKTUR SMALL Z
U+1D5BA    MATHEMATICAL SANS-SERIF SMALL A
U+1D5BB    MATHEMATICAL SANS-SERIF SMALL B
U+1D5BC    MATHEMATICAL SANS-SERIF SMALL C
U+1D5BD    MATHEMATICAL SANS-SERIF SMALL D
U+1D5BE    MATHEMATICAL SANS-SERIF SMALL E
U+1D5BF    MATHEMATICAL SANS-SERIF SMALL F
U+1D5C0    MATHEMATICAL SANS-SERIF SMALL G
U+1D5C1    MATHEMATICAL SANS-SERIF SMALL H
U+1D5C2    MATHEMATICAL SANS-SERIF SMALL I
U+1D5C3    MATHEMATICAL SANS-SERIF SMALL J
U+1D5C4    MATHEMATICAL SANS-SERIF SMALL K
U+1D5C5    MATHEMATICAL SANS-SERIF SMALL L
U+1D5C6    MATHEMATICAL SANS-SERIF SMALL M
U+1D5C7    MATHEMATICAL SANS-SERIF SMALL N
U+1D5C8    MATHEMATICAL SANS-SERIF SMALL O
U+1D5C9    MATHEMATICAL SANS-SERIF SMALL P
U+1D5CA    MATHEMATICAL SANS-SERIF SMALL Q
U+1D5CB    MATHEMATICAL SANS-SERIF SMALL R
U+1D5CC    MATHEMATICAL SANS-SERIF SMALL S
U+1D5CD    MATHEMATICAL SANS-SERIF SMALL T
U+1D5CE    MATHEMATICAL SANS-SERIF SMALL U
U+1D5CF    MATHEMATICAL SANS-SERIF SMALL V
U+1D5D0    MATHEMATICAL SANS-SERIF SMALL W
U+1D5D1    MATHEMATICAL SANS-SERIF SMALL X
U+1D5D2    MATHEMATICAL SANS-SERIF SMALL Y
U+1D5D3    MATHEMATICAL SANS-SERIF SMALL Z
U+1D5EE    MATHEMATICAL SANS-SERIF BOLD SMALL A
U+1D5EF    MATHEMATICAL SANS-SERIF BOLD SMALL B
U+1D5F0    MATHEMATICAL SANS-SERIF BOLD SMALL C
U+1D5F1    MATHEMATICAL SANS-SERIF BOLD SMALL D
U+1D5F2    MATHEMATICAL SANS-SERIF BOLD SMALL E
U+1D5F3    MATHEMATICAL SANS-SERIF BOLD SMALL F
U+1D5F4    MATHEMATICAL SANS-SERIF BOLD SMALL G
U+1D5F5    MATHEMATICAL SANS-SERIF BOLD SMALL H
U+1D5F6    MATHEMATICAL SANS-SERIF BOLD SMALL I
U+1D5F7    MATHEMATICAL SANS-SERIF BOLD SMALL J
U+1D5F8    MATHEMATICAL SANS-SERIF BOLD SMALL K
U+1D5F9    MATHEMATICAL SANS-SERIF BOLD SMALL L
U+1D5FA    MATHEMATICAL SANS-SERIF BOLD SMALL M
U+1D5FB    MATHEMATICAL SANS-SERIF BOLD SMALL N
U+1D5FC    MATHEMATICAL SANS-SERIF BOLD SMALL O
U+1D5FD    MATHEMATICAL SANS-SERIF BOLD SMALL P
U+1D5FE    MATHEMATICAL SANS-SERIF BOLD SMALL Q
U+1D5FF    MATHEMATICAL SANS-SERIF BOLD SMALL R
U+1D600    MATHEMATICAL SANS-SERIF BOLD SMALL S
U+1D601    MATHEMATICAL SANS-SERIF BOLD SMALL T
U+1D602    MATHEMATICAL SANS-SERIF BOLD SMALL U
U+1D603    MATHEMATICAL SANS-SERIF BOLD SMALL V
U+1D604    MATHEMATICAL SANS-SERIF BOLD SMALL W
U+1D605    MATHEMATICAL SANS-SERIF BOLD SMALL X
U+1D606    MATHEMATICAL SANS-SERIF BOLD SMALL Y
U+1D607    MATHEMATICAL SANS-SERIF BOLD SMALL Z
U+1D622    MATHEMATICAL SANS-SERIF ITALIC SMALL A
U+1D623    MATHEMATICAL SANS-SERIF ITALIC SMALL B
U+1D624    MATHEMATICAL SANS-SERIF ITALIC SMALL C
U+1D625    MATHEMATICAL SANS-SERIF ITALIC SMALL D
U+1D626    MATHEMATICAL SANS-SERIF ITALIC SMALL E
U+1D627    MATHEMATICAL SANS-SERIF ITALIC SMALL F
U+1D628    MATHEMATICAL SANS-SERIF ITALIC SMALL G
U+1D629    MATHEMATICAL SANS-SERIF ITALIC SMALL H
U+1D62A    MATHEMATICAL SANS-SERIF ITALIC SMALL I
U+1D62B    MATHEMATICAL SANS-SERIF ITALIC SMALL J
U+1D62C    MATHEMATICAL SANS-SERIF ITALIC SMALL K
U+1D62D    MATHEMATICAL SANS-SERIF ITALIC SMALL L
U+1D62E    MATHEMATICAL SANS-SERIF ITALIC SMALL M
U+1D62F    MATHEMATICAL SANS-SERIF ITALIC SMALL N
U+1D630    MATHEMATICAL SANS-SERIF ITALIC SMALL O
U+1D631    MATHEMATICAL SANS-SERIF ITALIC SMALL P
U+1D632    MATHEMATICAL SANS-SERIF ITALIC SMALL Q
U+1D633    MATHEMATICAL SANS-SERIF ITALIC SMALL R
U+1D634    MATHEMATICAL SANS-SERIF ITALIC SMALL S
U+1D635    MATHEMATICAL SANS-SERIF ITALIC SMALL T
U+1D636    MATHEMATICAL SANS-SERIF ITALIC SMALL U
U+1D637    MATHEMATICAL SANS-SERIF ITALIC SMALL V
U+1D638    MATHEMATICAL SANS-SERIF ITALIC SMALL W
U+1D639    MATHEMATICAL SANS-SERIF ITALIC SMALL X
U+1D63A    MATHEMATICAL SANS-SERIF ITALIC SMALL Y
U+1D63B    MATHEMATICAL SANS-SERIF ITALIC SMALL Z
U+1D656    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL A
U+1D657    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL B
U+1D658    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL C
U+1D659    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL D
U+1D65A    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL E
U+1D65B    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL F
U+1D65C    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL G
U+1D65D    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL H
U+1D65E    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL I
U+1D65F    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL J
U+1D660    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL K
U+1D661    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL L
U+1D662    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL M
U+1D663    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL N
U+1D664    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL O
U+1D665    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL P
U+1D666    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Q
U+1D667    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL R
U+1D668    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL S
U+1D669    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL T
U+1D66A    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL U
U+1D66B    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL V
U+1D66C    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL W
U+1D66D    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL X
U+1D66E    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Y
U+1D66F    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL Z
U+1D68A    MATHEMATICAL MONOSPACE SMALL A
U+1D68B    MATHEMATICAL MONOSPACE SMALL B
U+1D68C    MATHEMATICAL MONOSPACE SMALL C
U+1D68D    MATHEMATICAL MONOSPACE SMALL D
U+1D68E    MATHEMATICAL MONOSPACE SMALL E
U+1D68F    MATHEMATICAL MONOSPACE SMALL F
U+1D690    MATHEMATICAL MONOSPACE SMALL G
U+1D691    MATHEMATICAL MONOSPACE SMALL H
U+1D692    MATHEMATICAL MONOSPACE SMALL I
U+1D693    MATHEMATICAL MONOSPACE SMALL J
U+1D694    MATHEMATICAL MONOSPACE SMALL K
U+1D695    MATHEMATICAL MONOSPACE SMALL L
U+1D696    MATHEMATICAL MONOSPACE SMALL M
U+1D697    MATHEMATICAL MONOSPACE SMALL N
U+1D698    MATHEMATICAL MONOSPACE SMALL O
U+1D699    MATHEMATICAL MONOSPACE SMALL P
U+1D69A    MATHEMATICAL MONOSPACE SMALL Q
U+1D69B    MATHEMATICAL MONOSPACE SMALL R
U+1D69C    MATHEMATICAL MONOSPACE SMALL S
U+1D69D    MATHEMATICAL MONOSPACE SMALL T
U+1D69E    MATHEMATICAL MONOSPACE SMALL U
U+1D69F    MATHEMATICAL MONOSPACE SMALL V
U+1D6A0    MATHEMATICAL MONOSPACE SMALL W
U+1D6A1    MATHEMATICAL MONOSPACE SMALL X
U+1D6A2    MATHEMATICAL MONOSPACE SMALL Y
U+1D6A3    MATHEMATICAL MONOSPACE SMALL Z
U+1D6A4    MATHEMATICAL ITALIC SMALL DOTLESS I
U+1D6A5    MATHEMATICAL ITALIC SMALL DOTLESS J
U+1D6C2    MATHEMATICAL BOLD SMALL ALPHA
U+1D6C3    MATHEMATICAL BOLD SMALL BETA
U+1D6C4    MATHEMATICAL BOLD SMALL GAMMA
U+1D6C5    MATHEMATICAL BOLD SMALL DELTA
U+1D6C6    MATHEMATICAL BOLD SMALL EPSILON
U+1D6C7    MATHEMATICAL BOLD SMALL ZETA
U+1D6C8    MATHEMATICAL BOLD SMALL ETA
U+1D6C9    MATHEMATICAL BOLD SMALL THETA
U+1D6CA    MATHEMATICAL BOLD SMALL IOTA
U+1D6CB    MATHEMATICAL BOLD SMALL KAPPA
U+1D6CC    MATHEMATICAL BOLD SMALL LAMDA
U+1D6CD    MATHEMATICAL BOLD SMALL MU
U+1D6CE    MATHEMATICAL BOLD SMALL NU
U+1D6CF    MATHEMATICAL BOLD SMALL XI
U+1D6D0    MATHEMATICAL BOLD SMALL OMICRON
U+1D6D1    MATHEMATICAL BOLD SMALL PI
U+1D6D2    MATHEMATICAL BOLD SMALL RHO
U+1D6D3    MATHEMATICAL BOLD SMALL FINAL SIGMA
U+1D6D4    MATHEMATICAL BOLD SMALL SIGMA
U+1D6D5    MATHEMATICAL BOLD SMALL TAU
U+1D6D6    MATHEMATICAL BOLD SMALL UPSILON
U+1D6D7    MATHEMATICAL BOLD SMALL PHI
U+1D6D8    MATHEMATICAL BOLD SMALL CHI
U+1D6D9    MATHEMATICAL BOLD SMALL PSI
U+1D6DA    MATHEMATICAL BOLD SMALL OMEGA
U+1D6DC    MATHEMATICAL BOLD EPSILON SYMBOL
U+1D6DD    MATHEMATICAL BOLD THETA SYMBOL
U+1D6DE    MATHEMATICAL BOLD KAPPA SYMBOL
U+1D6DF    MATHEMATICAL BOLD PHI SYMBOL
U+1D6E0    MATHEMATICAL BOLD RHO SYMBOL
U+1D6E1    MATHEMATICAL BOLD PI SYMBOL
U+1D6FC    MATHEMATICAL ITALIC SMALL ALPHA
U+1D6FD    MATHEMATICAL ITALIC SMALL BETA
U+1D6FE    MATHEMATICAL ITALIC SMALL GAMMA
U+1D6FF    MATHEMATICAL ITALIC SMALL DELTA
U+1D700    MATHEMATICAL ITALIC SMALL EPSILON
U+1D701    MATHEMATICAL ITALIC SMALL ZETA
U+1D702    MATHEMATICAL ITALIC SMALL ETA
U+1D703    MATHEMATICAL ITALIC SMALL THETA
U+1D704    MATHEMATICAL ITALIC SMALL IOTA
U+1D705    MATHEMATICAL ITALIC SMALL KAPPA
U+1D706    MATHEMATICAL ITALIC SMALL LAMDA
U+1D707    MATHEMATICAL ITALIC SMALL MU
U+1D708    MATHEMATICAL ITALIC SMALL NU
U+1D709    MATHEMATICAL ITALIC SMALL XI
U+1D70A    MATHEMATICAL ITALIC SMALL OMICRON
U+1D70B    MATHEMATICAL ITALIC SMALL PI
U+1D70C    MATHEMATICAL ITALIC SMALL RHO
U+1D70D    MATHEMATICAL ITALIC SMALL FINAL SIGMA
U+1D70E    MATHEMATICAL ITALIC SMALL SIGMA
U+1D70F    MATHEMATICAL ITALIC SMALL TAU
U+1D710    MATHEMATICAL ITALIC SMALL UPSILON
U+1D711    MATHEMATICAL ITALIC SMALL PHI
U+1D712    MATHEMATICAL ITALIC SMALL CHI
U+1D713    MATHEMATICAL ITALIC SMALL PSI
U+1D714    MATHEMATICAL ITALIC SMALL OMEGA
U+1D716    MATHEMATICAL ITALIC EPSILON SYMBOL
U+1D717    MATHEMATICAL ITALIC THETA SYMBOL
U+1D718    MATHEMATICAL ITALIC KAPPA SYMBOL
U+1D719    MATHEMATICAL ITALIC PHI SYMBOL
U+1D71A    MATHEMATICAL ITALIC RHO SYMBOL
U+1D71B    MATHEMATICAL ITALIC PI SYMBOL
U+1D736    MATHEMATICAL BOLD ITALIC SMALL ALPHA
U+1D737    MATHEMATICAL BOLD ITALIC SMALL BETA
U+1D738    MATHEMATICAL BOLD ITALIC SMALL GAMMA
U+1D739    MATHEMATICAL BOLD ITALIC SMALL DELTA
U+1D73A    MATHEMATICAL BOLD ITALIC SMALL EPSILON
U+1D73B    MATHEMATICAL BOLD ITALIC SMALL ZETA
U+1D73C    MATHEMATICAL BOLD ITALIC SMALL ETA
U+1D73D    MATHEMATICAL BOLD ITALIC SMALL THETA
U+1D73E    MATHEMATICAL BOLD ITALIC SMALL IOTA
U+1D73F    MATHEMATICAL BOLD ITALIC SMALL KAPPA
U+1D740    MATHEMATICAL BOLD ITALIC SMALL LAMDA
U+1D741    MATHEMATICAL BOLD ITALIC SMALL MU
U+1D742    MATHEMATICAL BOLD ITALIC SMALL NU
U+1D743    MATHEMATICAL BOLD ITALIC SMALL XI
U+1D744    MATHEMATICAL BOLD ITALIC SMALL OMICRON
U+1D745    MATHEMATICAL BOLD ITALIC SMALL PI
U+1D746    MATHEMATICAL BOLD ITALIC SMALL RHO
U+1D747    MATHEMATICAL BOLD ITALIC SMALL FINAL SIGMA
U+1D748    MATHEMATICAL BOLD ITALIC SMALL SIGMA
U+1D749    MATHEMATICAL BOLD ITALIC SMALL TAU
U+1D74A    MATHEMATICAL BOLD ITALIC SMALL UPSILON
U+1D74B    MATHEMATICAL BOLD ITALIC SMALL PHI
U+1D74C    MATHEMATICAL BOLD ITALIC SMALL CHI
U+1D74D    MATHEMATICAL BOLD ITALIC SMALL PSI
U+1D74E    MATHEMATICAL BOLD ITALIC SMALL OMEGA
U+1D750    MATHEMATICAL BOLD ITALIC EPSILON SYMBOL
U+1D751    MATHEMATICAL BOLD ITALIC THETA SYMBOL
U+1D752    MATHEMATICAL BOLD ITALIC KAPPA SYMBOL
U+1D753    MATHEMATICAL BOLD ITALIC PHI SYMBOL
U+1D754    MATHEMATICAL BOLD ITALIC RHO SYMBOL
U+1D755    MATHEMATICAL BOLD ITALIC PI SYMBOL
U+1D770    MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA
U+1D771    MATHEMATICAL SANS-SERIF BOLD SMALL BETA
U+1D772    MATHEMATICAL SANS-SERIF BOLD SMALL GAMMA
U+1D773    MATHEMATICAL SANS-SERIF BOLD SMALL DELTA
U+1D774    MATHEMATICAL SANS-SERIF BOLD SMALL EPSILON
U+1D775    MATHEMATICAL SANS-SERIF BOLD SMALL ZETA
U+1D776    MATHEMATICAL SANS-SERIF BOLD SMALL ETA
U+1D777    MATHEMATICAL SANS-SERIF BOLD SMALL THETA
U+1D778    MATHEMATICAL SANS-SERIF BOLD SMALL IOTA
U+1D779    MATHEMATICAL SANS-SERIF BOLD SMALL KAPPA
U+1D77A    MATHEMATICAL SANS-SERIF BOLD SMALL LAMDA
U+1D77B    MATHEMATICAL SANS-SERIF BOLD SMALL MU
U+1D77C    MATHEMATICAL SANS-SERIF BOLD SMALL NU
U+1D77D    MATHEMATICAL SANS-SERIF BOLD SMALL XI
U+1D77E    MATHEMATICAL SANS-SERIF BOLD SMALL OMICRON
U+1D77F    MATHEMATICAL SANS-SERIF BOLD SMALL PI
U+1D780    MATHEMATICAL SANS-SERIF BOLD SMALL RHO
U+1D781    MATHEMATICAL SANS-SERIF BOLD SMALL FINAL SIGMA
U+1D782    MATHEMATICAL SANS-SERIF BOLD SMALL SIGMA
U+1D783    MATHEMATICAL SANS-SERIF BOLD SMALL TAU
U+1D784    MATHEMATICAL SANS-SERIF BOLD SMALL UPSILON
U+1D785    MATHEMATICAL SANS-SERIF BOLD SMALL PHI
U+1D786    MATHEMATICAL SANS-SERIF BOLD SMALL CHI
U+1D787    MATHEMATICAL SANS-SERIF BOLD SMALL PSI
U+1D788    MATHEMATICAL SANS-SERIF BOLD SMALL OMEGA
U+1D78A    MATHEMATICAL SANS-SERIF BOLD EPSILON SYMBOL
U+1D78B    MATHEMATICAL SANS-SERIF BOLD THETA SYMBOL
U+1D78C    MATHEMATICAL SANS-SERIF BOLD KAPPA SYMBOL
U+1D78D    MATHEMATICAL SANS-SERIF BOLD PHI SYMBOL
U+1D78E    MATHEMATICAL SANS-SERIF BOLD RHO SYMBOL
U+1D78F    MATHEMATICAL SANS-SERIF BOLD PI SYMBOL
U+1D7AA    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA
U+1D7AB    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL BETA
U+1D7AC    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL GAMMA
U+1D7AD    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL DELTA
U+1D7AE    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL EPSILON
U+1D7AF    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ZETA
U+1D7B0    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ETA
U+1D7B1    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL THETA
U+1D7B2    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL IOTA
U+1D7B3    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL KAPPA
U+1D7B4    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL LAMDA
U+1D7B5    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL MU
U+1D7B6    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL NU
U+1D7B7    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL XI
U+1D7B8    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMICRON
U+1D7B9    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PI
U+1D7BA    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL RHO
U+1D7BB    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL FINAL SIGMA
U+1D7BC    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL SIGMA
U+1D7BD    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL TAU
U+1D7BE    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL UPSILON
U+1D7BF    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PHI
U+1D7C0    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL CHI
U+1D7C1    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL PSI
U+1D7C2    MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMEGA
U+1D7C4    MATHEMATICAL SANS-SERIF BOLD ITALIC EPSILON SYMBOL
U+1D7C5    MATHEMATICAL SANS-SERIF BOLD ITALIC THETA SYMBOL
U+1D7C6    MATHEMATICAL SANS-SERIF BOLD ITALIC KAPPA SYMBOL
U+1D7C7    MATHEMATICAL SANS-SERIF BOLD ITALIC PHI SYMBOL
U+1D7C8    MATHEMATICAL SANS-SERIF BOLD ITALIC RHO SYMBOL
U+1D7C9    MATHEMATICAL SANS-SERIF BOLD ITALIC PI SYMBOL
U+1D7CB    MATHEMATICAL BOLD SMALL DIGAMMA
*/
};

}

#endif // UNICODE_LETTER_LOWERCASE_HPP_INCLUDED
