#ifndef UNICODE_LETTER_TITLECASE_HPP_INCLUDED
#define UNICODE_LETTER_TITLECASE_HPP_INCLUDED

namespace unicode {

// Lt
class letter_titlecase
{
/*
Character Name
U+01C5    LATIN CAPITAL LETTER D WITH SMALL LETTER Z WITH CARON
U+01C8    LATIN CAPITAL LETTER L WITH SMALL LETTER J
U+01CB    LATIN CAPITAL LETTER N WITH SMALL LETTER J
U+01F2    LATIN CAPITAL LETTER D WITH SMALL LETTER Z
U+1F88    GREEK CAPITAL LETTER ALPHA WITH PSILI AND PROSGEGRAMMENI
U+1F89    GREEK CAPITAL LETTER ALPHA WITH DASIA AND PROSGEGRAMMENI
U+1F8A    GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA AND PROSGEGRAMMENI
U+1F8B    GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA AND PROSGEGRAMMENI
U+1F8C    GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA AND PROSGEGRAMMENI
U+1F8D    GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA AND PROSGEGRAMMENI
U+1F8E    GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
U+1F8F    GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
U+1F98    GREEK CAPITAL LETTER ETA WITH PSILI AND PROSGEGRAMMENI
U+1F99    GREEK CAPITAL LETTER ETA WITH DASIA AND PROSGEGRAMMENI
U+1F9A    GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA AND PROSGEGRAMMENI
U+1F9B    GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA AND PROSGEGRAMMENI
U+1F9C    GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA AND PROSGEGRAMMENI
U+1F9D    GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA AND PROSGEGRAMMENI
U+1F9E    GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
U+1F9F    GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
U+1FA8    GREEK CAPITAL LETTER OMEGA WITH PSILI AND PROSGEGRAMMENI
U+1FA9    GREEK CAPITAL LETTER OMEGA WITH DASIA AND PROSGEGRAMMENI
U+1FAA    GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA AND PROSGEGRAMMENI
U+1FAB    GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA AND PROSGEGRAMMENI
U+1FAC    GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA AND PROSGEGRAMMENI
U+1FAD    GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA AND PROSGEGRAMMENI
U+1FAE    GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI AND PROSGEGRAMMENI
U+1FAF    GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI AND PROSGEGRAMMENI
U+1FBC    GREEK CAPITAL LETTER ALPHA WITH PROSGEGRAMMENI
U+1FCC    GREEK CAPITAL LETTER ETA WITH PROSGEGRAMMENI
U+1FFC    GREEK CAPITAL LETTER OMEGA WITH PROSGEGRAMMENI
*/
};

}

#endif // UNICODE_LETTER_TITLECASE_HPP_INCLUDED
