#ifndef UNICODE_LETTER_UPPERCASE_HPP_INCLUDED
#define UNICODE_LETTER_UPPERCASE_HPP_INCLUDED

namespace unicode {

// Lu
class letter_uppercase
{
/*
Character Name
U+0041    LATIN CAPITAL LETTER A
U+0042    LATIN CAPITAL LETTER B
U+0043    LATIN CAPITAL LETTER C
U+0044    LATIN CAPITAL LETTER D
U+0045    LATIN CAPITAL LETTER E
U+0046    LATIN CAPITAL LETTER F
U+0047    LATIN CAPITAL LETTER G
U+0048    LATIN CAPITAL LETTER H
U+0049    LATIN CAPITAL LETTER I
U+004A    LATIN CAPITAL LETTER J
U+004B    LATIN CAPITAL LETTER K
U+004C    LATIN CAPITAL LETTER L
U+004D    LATIN CAPITAL LETTER M
U+004E    LATIN CAPITAL LETTER N
U+004F    LATIN CAPITAL LETTER O
U+0050    LATIN CAPITAL LETTER P
U+0051    LATIN CAPITAL LETTER Q
U+0052    LATIN CAPITAL LETTER R
U+0053    LATIN CAPITAL LETTER S
U+0054    LATIN CAPITAL LETTER T
U+0055    LATIN CAPITAL LETTER U
U+0056    LATIN CAPITAL LETTER V
U+0057    LATIN CAPITAL LETTER W
U+0058    LATIN CAPITAL LETTER X
U+0059    LATIN CAPITAL LETTER Y
U+005A    LATIN CAPITAL LETTER Z
U+00C0    LATIN CAPITAL LETTER A WITH GRAVE
U+00C1    LATIN CAPITAL LETTER A WITH ACUTE
U+00C2    LATIN CAPITAL LETTER A WITH CIRCUMFLEX
U+00C3    LATIN CAPITAL LETTER A WITH TILDE
U+00C4    LATIN CAPITAL LETTER A WITH DIAERESIS
U+00C5    LATIN CAPITAL LETTER A WITH RING ABOVE
U+00C6    LATIN CAPITAL LETTER AE
U+00C7    LATIN CAPITAL LETTER C WITH CEDILLA
U+00C8    LATIN CAPITAL LETTER E WITH GRAVE
U+00C9    LATIN CAPITAL LETTER E WITH ACUTE
U+00CA    LATIN CAPITAL LETTER E WITH CIRCUMFLEX
U+00CB    LATIN CAPITAL LETTER E WITH DIAERESIS
U+00CC    LATIN CAPITAL LETTER I WITH GRAVE
U+00CD    LATIN CAPITAL LETTER I WITH ACUTE
U+00CE    LATIN CAPITAL LETTER I WITH CIRCUMFLEX
U+00CF    LATIN CAPITAL LETTER I WITH DIAERESIS
U+00D0    LATIN CAPITAL LETTER ETH
U+00D1    LATIN CAPITAL LETTER N WITH TILDE
U+00D2    LATIN CAPITAL LETTER O WITH GRAVE
U+00D3    LATIN CAPITAL LETTER O WITH ACUTE
U+00D4    LATIN CAPITAL LETTER O WITH CIRCUMFLEX
U+00D5    LATIN CAPITAL LETTER O WITH TILDE
U+00D6    LATIN CAPITAL LETTER O WITH DIAERESIS
U+00D8    LATIN CAPITAL LETTER O WITH STROKE
U+00D9    LATIN CAPITAL LETTER U WITH GRAVE
U+00DA    LATIN CAPITAL LETTER U WITH ACUTE
U+00DB    LATIN CAPITAL LETTER U WITH CIRCUMFLEX
U+00DC    LATIN CAPITAL LETTER U WITH DIAERESIS
U+00DD    LATIN CAPITAL LETTER Y WITH ACUTE
U+00DE    LATIN CAPITAL LETTER THORN
U+0100    LATIN CAPITAL LETTER A WITH MACRON
U+0102    LATIN CAPITAL LETTER A WITH BREVE
U+0104    LATIN CAPITAL LETTER A WITH OGONEK
U+0106    LATIN CAPITAL LETTER C WITH ACUTE
U+0108    LATIN CAPITAL LETTER C WITH CIRCUMFLEX
U+010A    LATIN CAPITAL LETTER C WITH DOT ABOVE
U+010C    LATIN CAPITAL LETTER C WITH CARON
U+010E    LATIN CAPITAL LETTER D WITH CARON
U+0110    LATIN CAPITAL LETTER D WITH STROKE
U+0112    LATIN CAPITAL LETTER E WITH MACRON
U+0114    LATIN CAPITAL LETTER E WITH BREVE
U+0116    LATIN CAPITAL LETTER E WITH DOT ABOVE
U+0118    LATIN CAPITAL LETTER E WITH OGONEK
U+011A    LATIN CAPITAL LETTER E WITH CARON
U+011C    LATIN CAPITAL LETTER G WITH CIRCUMFLEX
U+011E    LATIN CAPITAL LETTER G WITH BREVE
U+0120    LATIN CAPITAL LETTER G WITH DOT ABOVE
U+0122    LATIN CAPITAL LETTER G WITH CEDILLA
U+0124    LATIN CAPITAL LETTER H WITH CIRCUMFLEX
U+0126    LATIN CAPITAL LETTER H WITH STROKE
U+0128    LATIN CAPITAL LETTER I WITH TILDE
U+012A    LATIN CAPITAL LETTER I WITH MACRON
U+012C    LATIN CAPITAL LETTER I WITH BREVE
U+012E    LATIN CAPITAL LETTER I WITH OGONEK
U+0130    LATIN CAPITAL LETTER I WITH DOT ABOVE
U+0132    LATIN CAPITAL LIGATURE IJ
U+0134    LATIN CAPITAL LETTER J WITH CIRCUMFLEX
U+0136    LATIN CAPITAL LETTER K WITH CEDILLA
U+0139    LATIN CAPITAL LETTER L WITH ACUTE
U+013B    LATIN CAPITAL LETTER L WITH CEDILLA
U+013D    LATIN CAPITAL LETTER L WITH CARON
U+013F    LATIN CAPITAL LETTER L WITH MIDDLE DOT
U+0141    LATIN CAPITAL LETTER L WITH STROKE
U+0143    LATIN CAPITAL LETTER N WITH ACUTE
U+0145    LATIN CAPITAL LETTER N WITH CEDILLA
U+0147    LATIN CAPITAL LETTER N WITH CARON
U+014A    LATIN CAPITAL LETTER ENG
U+014C    LATIN CAPITAL LETTER O WITH MACRON
U+014E    LATIN CAPITAL LETTER O WITH BREVE
U+0150    LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
U+0152    LATIN CAPITAL LIGATURE OE
U+0154    LATIN CAPITAL LETTER R WITH ACUTE
U+0156    LATIN CAPITAL LETTER R WITH CEDILLA
U+0158    LATIN CAPITAL LETTER R WITH CARON
U+015A    LATIN CAPITAL LETTER S WITH ACUTE
U+015C    LATIN CAPITAL LETTER S WITH CIRCUMFLEX
U+015E    LATIN CAPITAL LETTER S WITH CEDILLA
U+0160    LATIN CAPITAL LETTER S WITH CARON
U+0162    LATIN CAPITAL LETTER T WITH CEDILLA
U+0164    LATIN CAPITAL LETTER T WITH CARON
U+0166    LATIN CAPITAL LETTER T WITH STROKE
U+0168    LATIN CAPITAL LETTER U WITH TILDE
U+016A    LATIN CAPITAL LETTER U WITH MACRON
U+016C    LATIN CAPITAL LETTER U WITH BREVE
U+016E    LATIN CAPITAL LETTER U WITH RING ABOVE
U+0170    LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
U+0172    LATIN CAPITAL LETTER U WITH OGONEK
U+0174    LATIN CAPITAL LETTER W WITH CIRCUMFLEX
U+0176    LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
U+0178    LATIN CAPITAL LETTER Y WITH DIAERESIS
U+0179    LATIN CAPITAL LETTER Z WITH ACUTE
U+017B    LATIN CAPITAL LETTER Z WITH DOT ABOVE
U+017D    LATIN CAPITAL LETTER Z WITH CARON
U+0181    LATIN CAPITAL LETTER B WITH HOOK
U+0182    LATIN CAPITAL LETTER B WITH TOPBAR
U+0184    LATIN CAPITAL LETTER TONE SIX
U+0186    LATIN CAPITAL LETTER OPEN O
U+0187    LATIN CAPITAL LETTER C WITH HOOK
U+0189    LATIN CAPITAL LETTER AFRICAN D
U+018A    LATIN CAPITAL LETTER D WITH HOOK
U+018B    LATIN CAPITAL LETTER D WITH TOPBAR
U+018E    LATIN CAPITAL LETTER REVERSED E
U+018F    LATIN CAPITAL LETTER SCHWA
U+0190    LATIN CAPITAL LETTER OPEN E
U+0191    LATIN CAPITAL LETTER F WITH HOOK
U+0193    LATIN CAPITAL LETTER G WITH HOOK
U+0194    LATIN CAPITAL LETTER GAMMA
U+0196    LATIN CAPITAL LETTER IOTA
U+0197    LATIN CAPITAL LETTER I WITH STROKE
U+0198    LATIN CAPITAL LETTER K WITH HOOK
U+019C    LATIN CAPITAL LETTER TURNED M
U+019D    LATIN CAPITAL LETTER N WITH LEFT HOOK
U+019F    LATIN CAPITAL LETTER O WITH MIDDLE TILDE
U+01A0    LATIN CAPITAL LETTER O WITH HORN
U+01A2    LATIN CAPITAL LETTER OI
U+01A4    LATIN CAPITAL LETTER P WITH HOOK
U+01A6    LATIN LETTER YR
U+01A7    LATIN CAPITAL LETTER TONE TWO
U+01A9    LATIN CAPITAL LETTER ESH
U+01AC    LATIN CAPITAL LETTER T WITH HOOK
U+01AE    LATIN CAPITAL LETTER T WITH RETROFLEX HOOK
U+01AF    LATIN CAPITAL LETTER U WITH HORN
U+01B1    LATIN CAPITAL LETTER UPSILON
U+01B2    LATIN CAPITAL LETTER V WITH HOOK
U+01B3    LATIN CAPITAL LETTER Y WITH HOOK
U+01B5    LATIN CAPITAL LETTER Z WITH STROKE
U+01B7    LATIN CAPITAL LETTER EZH
U+01B8    LATIN CAPITAL LETTER EZH REVERSED
U+01BC    LATIN CAPITAL LETTER TONE FIVE
U+01C4    LATIN CAPITAL LETTER DZ WITH CARON
U+01C7    LATIN CAPITAL LETTER LJ
U+01CA    LATIN CAPITAL LETTER NJ
U+01CD    LATIN CAPITAL LETTER A WITH CARON
U+01CF    LATIN CAPITAL LETTER I WITH CARON
U+01D1    LATIN CAPITAL LETTER O WITH CARON
U+01D3    LATIN CAPITAL LETTER U WITH CARON
U+01D5    LATIN CAPITAL LETTER U WITH DIAERESIS AND MACRON
U+01D7    LATIN CAPITAL LETTER U WITH DIAERESIS AND ACUTE
U+01D9    LATIN CAPITAL LETTER U WITH DIAERESIS AND CARON
U+01DB    LATIN CAPITAL LETTER U WITH DIAERESIS AND GRAVE
U+01DE    LATIN CAPITAL LETTER A WITH DIAERESIS AND MACRON
U+01E0    LATIN CAPITAL LETTER A WITH DOT ABOVE AND MACRON
U+01E2    LATIN CAPITAL LETTER AE WITH MACRON
U+01E4    LATIN CAPITAL LETTER G WITH STROKE
U+01E6    LATIN CAPITAL LETTER G WITH CARON
U+01E8    LATIN CAPITAL LETTER K WITH CARON
U+01EA    LATIN CAPITAL LETTER O WITH OGONEK
U+01EC    LATIN CAPITAL LETTER O WITH OGONEK AND MACRON
U+01EE    LATIN CAPITAL LETTER EZH WITH CARON
U+01F1    LATIN CAPITAL LETTER DZ
U+01F4    LATIN CAPITAL LETTER G WITH ACUTE
U+01F6    LATIN CAPITAL LETTER HWAIR
U+01F7    LATIN CAPITAL LETTER WYNN
U+01F8    LATIN CAPITAL LETTER N WITH GRAVE
U+01FA    LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
U+01FC    LATIN CAPITAL LETTER AE WITH ACUTE
U+01FE    LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
U+0200    LATIN CAPITAL LETTER A WITH DOUBLE GRAVE
U+0202    LATIN CAPITAL LETTER A WITH INVERTED BREVE
U+0204    LATIN CAPITAL LETTER E WITH DOUBLE GRAVE
U+0206    LATIN CAPITAL LETTER E WITH INVERTED BREVE
U+0208    LATIN CAPITAL LETTER I WITH DOUBLE GRAVE
U+020A    LATIN CAPITAL LETTER I WITH INVERTED BREVE
U+020C    LATIN CAPITAL LETTER O WITH DOUBLE GRAVE
U+020E    LATIN CAPITAL LETTER O WITH INVERTED BREVE
U+0210    LATIN CAPITAL LETTER R WITH DOUBLE GRAVE
U+0212    LATIN CAPITAL LETTER R WITH INVERTED BREVE
U+0214    LATIN CAPITAL LETTER U WITH DOUBLE GRAVE
U+0216    LATIN CAPITAL LETTER U WITH INVERTED BREVE
U+0218    LATIN CAPITAL LETTER S WITH COMMA BELOW
U+021A    LATIN CAPITAL LETTER T WITH COMMA BELOW
U+021C    LATIN CAPITAL LETTER YOGH
U+021E    LATIN CAPITAL LETTER H WITH CARON
U+0220    LATIN CAPITAL LETTER N WITH LONG RIGHT LEG
U+0222    LATIN CAPITAL LETTER OU
U+0224    LATIN CAPITAL LETTER Z WITH HOOK
U+0226    LATIN CAPITAL LETTER A WITH DOT ABOVE
U+0228    LATIN CAPITAL LETTER E WITH CEDILLA
U+022A    LATIN CAPITAL LETTER O WITH DIAERESIS AND MACRON
U+022C    LATIN CAPITAL LETTER O WITH TILDE AND MACRON
U+022E    LATIN CAPITAL LETTER O WITH DOT ABOVE
U+0230    LATIN CAPITAL LETTER O WITH DOT ABOVE AND MACRON
U+0232    LATIN CAPITAL LETTER Y WITH MACRON
U+023A    LATIN CAPITAL LETTER A WITH STROKE
U+023B    LATIN CAPITAL LETTER C WITH STROKE
U+023D    LATIN CAPITAL LETTER L WITH BAR
U+023E    LATIN CAPITAL LETTER T WITH DIAGONAL STROKE
U+0241    LATIN CAPITAL LETTER GLOTTAL STOP
U+0243    LATIN CAPITAL LETTER B WITH STROKE
U+0244    LATIN CAPITAL LETTER U BAR
U+0245    LATIN CAPITAL LETTER TURNED V
U+0246    LATIN CAPITAL LETTER E WITH STROKE
U+0248    LATIN CAPITAL LETTER J WITH STROKE
U+024A    LATIN CAPITAL LETTER SMALL Q WITH HOOK TAIL
U+024C    LATIN CAPITAL LETTER R WITH STROKE
U+024E    LATIN CAPITAL LETTER Y WITH STROKE
U+0370    GREEK CAPITAL LETTER HETA
U+0372    GREEK CAPITAL LETTER ARCHAIC SAMPI
U+0376    GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA
U+037F    GREEK CAPITAL LETTER YOT
U+0386    GREEK CAPITAL LETTER ALPHA WITH TONOS
U+0388    GREEK CAPITAL LETTER EPSILON WITH TONOS
U+0389    GREEK CAPITAL LETTER ETA WITH TONOS
U+038A    GREEK CAPITAL LETTER IOTA WITH TONOS
U+038C    GREEK CAPITAL LETTER OMICRON WITH TONOS
U+038E    GREEK CAPITAL LETTER UPSILON WITH TONOS
U+038F    GREEK CAPITAL LETTER OMEGA WITH TONOS
U+0391    GREEK CAPITAL LETTER ALPHA
U+0392    GREEK CAPITAL LETTER BETA
U+0393    GREEK CAPITAL LETTER GAMMA
U+0394    GREEK CAPITAL LETTER DELTA
U+0395    GREEK CAPITAL LETTER EPSILON
U+0396    GREEK CAPITAL LETTER ZETA
U+0397    GREEK CAPITAL LETTER ETA
U+0398    GREEK CAPITAL LETTER THETA
U+0399    GREEK CAPITAL LETTER IOTA
U+039A    GREEK CAPITAL LETTER KAPPA
U+039B    GREEK CAPITAL LETTER LAMDA
U+039C    GREEK CAPITAL LETTER MU
U+039D    GREEK CAPITAL LETTER NU
U+039E    GREEK CAPITAL LETTER XI
U+039F    GREEK CAPITAL LETTER OMICRON
U+03A0    GREEK CAPITAL LETTER PI
U+03A1    GREEK CAPITAL LETTER RHO
U+03A3    GREEK CAPITAL LETTER SIGMA
U+03A4    GREEK CAPITAL LETTER TAU
U+03A5    GREEK CAPITAL LETTER UPSILON
U+03A6    GREEK CAPITAL LETTER PHI
U+03A7    GREEK CAPITAL LETTER CHI
U+03A8    GREEK CAPITAL LETTER PSI
U+03A9    GREEK CAPITAL LETTER OMEGA
U+03AA    GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
U+03AB    GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
U+03CF    GREEK CAPITAL KAI SYMBOL
U+03D2    GREEK UPSILON WITH HOOK SYMBOL
U+03D3    GREEK UPSILON WITH ACUTE AND HOOK SYMBOL
U+03D4    GREEK UPSILON WITH DIAERESIS AND HOOK SYMBOL
U+03D8    GREEK LETTER ARCHAIC KOPPA
U+03DA    GREEK LETTER STIGMA
U+03DC    GREEK LETTER DIGAMMA
U+03DE    GREEK LETTER KOPPA
U+03E0    GREEK LETTER SAMPI
U+03E2    COPTIC CAPITAL LETTER SHEI
U+03E4    COPTIC CAPITAL LETTER FEI
U+03E6    COPTIC CAPITAL LETTER KHEI
U+03E8    COPTIC CAPITAL LETTER HORI
U+03EA    COPTIC CAPITAL LETTER GANGIA
U+03EC    COPTIC CAPITAL LETTER SHIMA
U+03EE    COPTIC CAPITAL LETTER DEI
U+03F4    GREEK CAPITAL THETA SYMBOL
U+03F7    GREEK CAPITAL LETTER SHO
U+03F9    GREEK CAPITAL LUNATE SIGMA SYMBOL
U+03FA    GREEK CAPITAL LETTER SAN
U+03FD    GREEK CAPITAL REVERSED LUNATE SIGMA SYMBOL
U+03FE    GREEK CAPITAL DOTTED LUNATE SIGMA SYMBOL
U+03FF    GREEK CAPITAL REVERSED DOTTED LUNATE SIGMA SYMBOL
U+0400    CYRILLIC CAPITAL LETTER IE WITH GRAVE
U+0401    CYRILLIC CAPITAL LETTER IO
U+0402    CYRILLIC CAPITAL LETTER DJE
U+0403    CYRILLIC CAPITAL LETTER GJE
U+0404    CYRILLIC CAPITAL LETTER UKRAINIAN IE
U+0405    CYRILLIC CAPITAL LETTER DZE
U+0406    CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
U+0407    CYRILLIC CAPITAL LETTER YI
U+0408    CYRILLIC CAPITAL LETTER JE
U+0409    CYRILLIC CAPITAL LETTER LJE
U+040A    CYRILLIC CAPITAL LETTER NJE
U+040B    CYRILLIC CAPITAL LETTER TSHE
U+040C    CYRILLIC CAPITAL LETTER KJE
U+040D    CYRILLIC CAPITAL LETTER I WITH GRAVE
U+040E    CYRILLIC CAPITAL LETTER SHORT U
U+040F    CYRILLIC CAPITAL LETTER DZHE
U+0410    CYRILLIC CAPITAL LETTER A
U+0411    CYRILLIC CAPITAL LETTER BE
U+0412    CYRILLIC CAPITAL LETTER VE
U+0413    CYRILLIC CAPITAL LETTER GHE
U+0414    CYRILLIC CAPITAL LETTER DE
U+0415    CYRILLIC CAPITAL LETTER IE
U+0416    CYRILLIC CAPITAL LETTER ZHE
U+0417    CYRILLIC CAPITAL LETTER ZE
U+0418    CYRILLIC CAPITAL LETTER I
U+0419    CYRILLIC CAPITAL LETTER SHORT I
U+041A    CYRILLIC CAPITAL LETTER KA
U+041B    CYRILLIC CAPITAL LETTER EL
U+041C    CYRILLIC CAPITAL LETTER EM
U+041D    CYRILLIC CAPITAL LETTER EN
U+041E    CYRILLIC CAPITAL LETTER O
U+041F    CYRILLIC CAPITAL LETTER PE
U+0420    CYRILLIC CAPITAL LETTER ER
U+0421    CYRILLIC CAPITAL LETTER ES
U+0422    CYRILLIC CAPITAL LETTER TE
U+0423    CYRILLIC CAPITAL LETTER U
U+0424    CYRILLIC CAPITAL LETTER EF
U+0425    CYRILLIC CAPITAL LETTER HA
U+0426    CYRILLIC CAPITAL LETTER TSE
U+0427    CYRILLIC CAPITAL LETTER CHE
U+0428    CYRILLIC CAPITAL LETTER SHA
U+0429    CYRILLIC CAPITAL LETTER SHCHA
U+042A    CYRILLIC CAPITAL LETTER HARD SIGN
U+042B    CYRILLIC CAPITAL LETTER YERU
U+042C    CYRILLIC CAPITAL LETTER SOFT SIGN
U+042D    CYRILLIC CAPITAL LETTER E
U+042E    CYRILLIC CAPITAL LETTER YU
U+042F    CYRILLIC CAPITAL LETTER YA
U+0460    CYRILLIC CAPITAL LETTER OMEGA
U+0462    CYRILLIC CAPITAL LETTER YAT
U+0464    CYRILLIC CAPITAL LETTER IOTIFIED E
U+0466    CYRILLIC CAPITAL LETTER LITTLE YUS
U+0468    CYRILLIC CAPITAL LETTER IOTIFIED LITTLE YUS
U+046A    CYRILLIC CAPITAL LETTER BIG YUS
U+046C    CYRILLIC CAPITAL LETTER IOTIFIED BIG YUS
U+046E    CYRILLIC CAPITAL LETTER KSI
U+0470    CYRILLIC CAPITAL LETTER PSI
U+0472    CYRILLIC CAPITAL LETTER FITA
U+0474    CYRILLIC CAPITAL LETTER IZHITSA
U+0476    CYRILLIC CAPITAL LETTER IZHITSA WITH DOUBLE GRAVE ACCENT
U+0478    CYRILLIC CAPITAL LETTER UK
U+047A    CYRILLIC CAPITAL LETTER ROUND OMEGA
U+047C    CYRILLIC CAPITAL LETTER OMEGA WITH TITLO
U+047E    CYRILLIC CAPITAL LETTER OT
U+0480    CYRILLIC CAPITAL LETTER KOPPA
U+048A    CYRILLIC CAPITAL LETTER SHORT I WITH TAIL
U+048C    CYRILLIC CAPITAL LETTER SEMISOFT SIGN
U+048E    CYRILLIC CAPITAL LETTER ER WITH TICK
U+0490    CYRILLIC CAPITAL LETTER GHE WITH UPTURN
U+0492    CYRILLIC CAPITAL LETTER GHE WITH STROKE
U+0494    CYRILLIC CAPITAL LETTER GHE WITH MIDDLE HOOK
U+0496    CYRILLIC CAPITAL LETTER ZHE WITH DESCENDER
U+0498    CYRILLIC CAPITAL LETTER ZE WITH DESCENDER
U+049A    CYRILLIC CAPITAL LETTER KA WITH DESCENDER
U+049C    CYRILLIC CAPITAL LETTER KA WITH VERTICAL STROKE
U+049E    CYRILLIC CAPITAL LETTER KA WITH STROKE
U+04A0    CYRILLIC CAPITAL LETTER BASHKIR KA
U+04A2    CYRILLIC CAPITAL LETTER EN WITH DESCENDER
U+04A4    CYRILLIC CAPITAL LIGATURE EN GHE
U+04A6    CYRILLIC CAPITAL LETTER PE WITH MIDDLE HOOK
U+04A8    CYRILLIC CAPITAL LETTER ABKHASIAN HA
U+04AA    CYRILLIC CAPITAL LETTER ES WITH DESCENDER
U+04AC    CYRILLIC CAPITAL LETTER TE WITH DESCENDER
U+04AE    CYRILLIC CAPITAL LETTER STRAIGHT U
U+04B0    CYRILLIC CAPITAL LETTER STRAIGHT U WITH STROKE
U+04B2    CYRILLIC CAPITAL LETTER HA WITH DESCENDER
U+04B4    CYRILLIC CAPITAL LIGATURE TE TSE
U+04B6    CYRILLIC CAPITAL LETTER CHE WITH DESCENDER
U+04B8    CYRILLIC CAPITAL LETTER CHE WITH VERTICAL STROKE
U+04BA    CYRILLIC CAPITAL LETTER SHHA
U+04BC    CYRILLIC CAPITAL LETTER ABKHASIAN CHE
U+04BE    CYRILLIC CAPITAL LETTER ABKHASIAN CHE WITH DESCENDER
U+04C0    CYRILLIC LETTER PALOCHKA
U+04C1    CYRILLIC CAPITAL LETTER ZHE WITH BREVE
U+04C3    CYRILLIC CAPITAL LETTER KA WITH HOOK
U+04C5    CYRILLIC CAPITAL LETTER EL WITH TAIL
U+04C7    CYRILLIC CAPITAL LETTER EN WITH HOOK
U+04C9    CYRILLIC CAPITAL LETTER EN WITH TAIL
U+04CB    CYRILLIC CAPITAL LETTER KHAKASSIAN CHE
U+04CD    CYRILLIC CAPITAL LETTER EM WITH TAIL
U+04D0    CYRILLIC CAPITAL LETTER A WITH BREVE
U+04D2    CYRILLIC CAPITAL LETTER A WITH DIAERESIS
U+04D4    CYRILLIC CAPITAL LIGATURE A IE
U+04D6    CYRILLIC CAPITAL LETTER IE WITH BREVE
U+04D8    CYRILLIC CAPITAL LETTER SCHWA
U+04DA    CYRILLIC CAPITAL LETTER SCHWA WITH DIAERESIS
U+04DC    CYRILLIC CAPITAL LETTER ZHE WITH DIAERESIS
U+04DE    CYRILLIC CAPITAL LETTER ZE WITH DIAERESIS
U+04E0    CYRILLIC CAPITAL LETTER ABKHASIAN DZE
U+04E2    CYRILLIC CAPITAL LETTER I WITH MACRON
U+04E4    CYRILLIC CAPITAL LETTER I WITH DIAERESIS
U+04E6    CYRILLIC CAPITAL LETTER O WITH DIAERESIS
U+04E8    CYRILLIC CAPITAL LETTER BARRED O
U+04EA    CYRILLIC CAPITAL LETTER BARRED O WITH DIAERESIS
U+04EC    CYRILLIC CAPITAL LETTER E WITH DIAERESIS
U+04EE    CYRILLIC CAPITAL LETTER U WITH MACRON
U+04F0    CYRILLIC CAPITAL LETTER U WITH DIAERESIS
U+04F2    CYRILLIC CAPITAL LETTER U WITH DOUBLE ACUTE
U+04F4    CYRILLIC CAPITAL LETTER CHE WITH DIAERESIS
U+04F6    CYRILLIC CAPITAL LETTER GHE WITH DESCENDER
U+04F8    CYRILLIC CAPITAL LETTER YERU WITH DIAERESIS
U+04FA    CYRILLIC CAPITAL LETTER GHE WITH STROKE AND HOOK
U+04FC    CYRILLIC CAPITAL LETTER HA WITH HOOK
U+04FE    CYRILLIC CAPITAL LETTER HA WITH STROKE
U+0500    CYRILLIC CAPITAL LETTER KOMI DE
U+0502    CYRILLIC CAPITAL LETTER KOMI DJE
U+0504    CYRILLIC CAPITAL LETTER KOMI ZJE
U+0506    CYRILLIC CAPITAL LETTER KOMI DZJE
U+0508    CYRILLIC CAPITAL LETTER KOMI LJE
U+050A    CYRILLIC CAPITAL LETTER KOMI NJE
U+050C    CYRILLIC CAPITAL LETTER KOMI SJE
U+050E    CYRILLIC CAPITAL LETTER KOMI TJE
U+0510    CYRILLIC CAPITAL LETTER REVERSED ZE
U+0512    CYRILLIC CAPITAL LETTER EL WITH HOOK
U+0514    CYRILLIC CAPITAL LETTER LHA
U+0516    CYRILLIC CAPITAL LETTER RHA
U+0518    CYRILLIC CAPITAL LETTER YAE
U+051A    CYRILLIC CAPITAL LETTER QA
U+051C    CYRILLIC CAPITAL LETTER WE
U+051E    CYRILLIC CAPITAL LETTER ALEUT KA
U+0520    CYRILLIC CAPITAL LETTER EL WITH MIDDLE HOOK
U+0522    CYRILLIC CAPITAL LETTER EN WITH MIDDLE HOOK
U+0524    CYRILLIC CAPITAL LETTER PE WITH DESCENDER
U+0526    CYRILLIC CAPITAL LETTER SHHA WITH DESCENDER
U+0528    CYRILLIC CAPITAL LETTER EN WITH LEFT HOOK
U+052A    CYRILLIC CAPITAL LETTER DZZHE
U+052C    CYRILLIC CAPITAL LETTER DCHE
U+052E    CYRILLIC CAPITAL LETTER EL WITH DESCENDER
U+0531    ARMENIAN CAPITAL LETTER AYB
U+0532    ARMENIAN CAPITAL LETTER BEN
U+0533    ARMENIAN CAPITAL LETTER GIM
U+0534    ARMENIAN CAPITAL LETTER DA
U+0535    ARMENIAN CAPITAL LETTER ECH
U+0536    ARMENIAN CAPITAL LETTER ZA
U+0537    ARMENIAN CAPITAL LETTER EH
U+0538    ARMENIAN CAPITAL LETTER ET
U+0539    ARMENIAN CAPITAL LETTER TO
U+053A    ARMENIAN CAPITAL LETTER ZHE
U+053B    ARMENIAN CAPITAL LETTER INI
U+053C    ARMENIAN CAPITAL LETTER LIWN
U+053D    ARMENIAN CAPITAL LETTER XEH
U+053E    ARMENIAN CAPITAL LETTER CA
U+053F    ARMENIAN CAPITAL LETTER KEN
U+0540    ARMENIAN CAPITAL LETTER HO
U+0541    ARMENIAN CAPITAL LETTER JA
U+0542    ARMENIAN CAPITAL LETTER GHAD
U+0543    ARMENIAN CAPITAL LETTER CHEH
U+0544    ARMENIAN CAPITAL LETTER MEN
U+0545    ARMENIAN CAPITAL LETTER YI
U+0546    ARMENIAN CAPITAL LETTER NOW
U+0547    ARMENIAN CAPITAL LETTER SHA
U+0548    ARMENIAN CAPITAL LETTER VO
U+0549    ARMENIAN CAPITAL LETTER CHA
U+054A    ARMENIAN CAPITAL LETTER PEH
U+054B    ARMENIAN CAPITAL LETTER JHEH
U+054C    ARMENIAN CAPITAL LETTER RA
U+054D    ARMENIAN CAPITAL LETTER SEH
U+054E    ARMENIAN CAPITAL LETTER VEW
U+054F    ARMENIAN CAPITAL LETTER TIWN
U+0550    ARMENIAN CAPITAL LETTER REH
U+0551    ARMENIAN CAPITAL LETTER CO
U+0552    ARMENIAN CAPITAL LETTER YIWN
U+0553    ARMENIAN CAPITAL LETTER PIWR
U+0554    ARMENIAN CAPITAL LETTER KEH
U+0555    ARMENIAN CAPITAL LETTER OH
U+0556    ARMENIAN CAPITAL LETTER FEH
U+10A0    GEORGIAN CAPITAL LETTER AN
U+10A1    GEORGIAN CAPITAL LETTER BAN
U+10A2    GEORGIAN CAPITAL LETTER GAN
U+10A3    GEORGIAN CAPITAL LETTER DON
U+10A4    GEORGIAN CAPITAL LETTER EN
U+10A5    GEORGIAN CAPITAL LETTER VIN
U+10A6    GEORGIAN CAPITAL LETTER ZEN
U+10A7    GEORGIAN CAPITAL LETTER TAN
U+10A8    GEORGIAN CAPITAL LETTER IN
U+10A9    GEORGIAN CAPITAL LETTER KAN
U+10AA    GEORGIAN CAPITAL LETTER LAS
U+10AB    GEORGIAN CAPITAL LETTER MAN
U+10AC    GEORGIAN CAPITAL LETTER NAR
U+10AD    GEORGIAN CAPITAL LETTER ON
U+10AE    GEORGIAN CAPITAL LETTER PAR
U+10AF    GEORGIAN CAPITAL LETTER ZHAR
U+10B0    GEORGIAN CAPITAL LETTER RAE
U+10B1    GEORGIAN CAPITAL LETTER SAN
U+10B2    GEORGIAN CAPITAL LETTER TAR
U+10B3    GEORGIAN CAPITAL LETTER UN
U+10B4    GEORGIAN CAPITAL LETTER PHAR
U+10B5    GEORGIAN CAPITAL LETTER KHAR
U+10B6    GEORGIAN CAPITAL LETTER GHAN
U+10B7    GEORGIAN CAPITAL LETTER QAR
U+10B8    GEORGIAN CAPITAL LETTER SHIN
U+10B9    GEORGIAN CAPITAL LETTER CHIN
U+10BA    GEORGIAN CAPITAL LETTER CAN
U+10BB    GEORGIAN CAPITAL LETTER JIL
U+10BC    GEORGIAN CAPITAL LETTER CIL
U+10BD    GEORGIAN CAPITAL LETTER CHAR
U+10BE    GEORGIAN CAPITAL LETTER XAN
U+10BF    GEORGIAN CAPITAL LETTER JHAN
U+10C0    GEORGIAN CAPITAL LETTER HAE
U+10C1    GEORGIAN CAPITAL LETTER HE
U+10C2    GEORGIAN CAPITAL LETTER HIE
U+10C3    GEORGIAN CAPITAL LETTER WE
U+10C4    GEORGIAN CAPITAL LETTER HAR
U+10C5    GEORGIAN CAPITAL LETTER HOE
U+10C7    GEORGIAN CAPITAL LETTER YN
U+10CD    GEORGIAN CAPITAL LETTER AEN
U+13A0    CHEROKEE LETTER A
U+13A1    CHEROKEE LETTER E
U+13A2    CHEROKEE LETTER I
U+13A3    CHEROKEE LETTER O
U+13A4    CHEROKEE LETTER U
U+13A5    CHEROKEE LETTER V
U+13A6    CHEROKEE LETTER GA
U+13A7    CHEROKEE LETTER KA
U+13A8    CHEROKEE LETTER GE
U+13A9    CHEROKEE LETTER GI
U+13AA    CHEROKEE LETTER GO
U+13AB    CHEROKEE LETTER GU
U+13AC    CHEROKEE LETTER GV
U+13AD    CHEROKEE LETTER HA
U+13AE    CHEROKEE LETTER HE
U+13AF    CHEROKEE LETTER HI
U+13B0    CHEROKEE LETTER HO
U+13B1    CHEROKEE LETTER HU
U+13B2    CHEROKEE LETTER HV
U+13B3    CHEROKEE LETTER LA
U+13B4    CHEROKEE LETTER LE
U+13B5    CHEROKEE LETTER LI
U+13B6    CHEROKEE LETTER LO
U+13B7    CHEROKEE LETTER LU
U+13B8    CHEROKEE LETTER LV
U+13B9    CHEROKEE LETTER MA
U+13BA    CHEROKEE LETTER ME
U+13BB    CHEROKEE LETTER MI
U+13BC    CHEROKEE LETTER MO
U+13BD    CHEROKEE LETTER MU
U+13BE    CHEROKEE LETTER NA
U+13BF    CHEROKEE LETTER HNA
U+13C0    CHEROKEE LETTER NAH
U+13C1    CHEROKEE LETTER NE
U+13C2    CHEROKEE LETTER NI
U+13C3    CHEROKEE LETTER NO
U+13C4    CHEROKEE LETTER NU
U+13C5    CHEROKEE LETTER NV
U+13C6    CHEROKEE LETTER QUA
U+13C7    CHEROKEE LETTER QUE
U+13C8    CHEROKEE LETTER QUI
U+13C9    CHEROKEE LETTER QUO
U+13CA    CHEROKEE LETTER QUU
U+13CB    CHEROKEE LETTER QUV
U+13CC    CHEROKEE LETTER SA
U+13CD    CHEROKEE LETTER S
U+13CE    CHEROKEE LETTER SE
U+13CF    CHEROKEE LETTER SI
U+13D0    CHEROKEE LETTER SO
U+13D1    CHEROKEE LETTER SU
U+13D2    CHEROKEE LETTER SV
U+13D3    CHEROKEE LETTER DA
U+13D4    CHEROKEE LETTER TA
U+13D5    CHEROKEE LETTER DE
U+13D6    CHEROKEE LETTER TE
U+13D7    CHEROKEE LETTER DI
U+13D8    CHEROKEE LETTER TI
U+13D9    CHEROKEE LETTER DO
U+13DA    CHEROKEE LETTER DU
U+13DB    CHEROKEE LETTER DV
U+13DC    CHEROKEE LETTER DLA
U+13DD    CHEROKEE LETTER TLA
U+13DE    CHEROKEE LETTER TLE
U+13DF    CHEROKEE LETTER TLI
U+13E0    CHEROKEE LETTER TLO
U+13E1    CHEROKEE LETTER TLU
U+13E2    CHEROKEE LETTER TLV
U+13E3    CHEROKEE LETTER TSA
U+13E4    CHEROKEE LETTER TSE
U+13E5    CHEROKEE LETTER TSI
U+13E6    CHEROKEE LETTER TSO
U+13E7    CHEROKEE LETTER TSU
U+13E8    CHEROKEE LETTER TSV
U+13E9    CHEROKEE LETTER WA
U+13EA    CHEROKEE LETTER WE
U+13EB    CHEROKEE LETTER WI
U+13EC    CHEROKEE LETTER WO
U+13ED    CHEROKEE LETTER WU
U+13EE    CHEROKEE LETTER WV
U+13EF    CHEROKEE LETTER YA
U+13F0    CHEROKEE LETTER YE
U+13F1    CHEROKEE LETTER YI
U+13F2    CHEROKEE LETTER YO
U+13F3    CHEROKEE LETTER YU
U+13F4    CHEROKEE LETTER YV
U+13F5    CHEROKEE LETTER MV
U+1E00    LATIN CAPITAL LETTER A WITH RING BELOW
U+1E02    LATIN CAPITAL LETTER B WITH DOT ABOVE
U+1E04    LATIN CAPITAL LETTER B WITH DOT BELOW
U+1E06    LATIN CAPITAL LETTER B WITH LINE BELOW
U+1E08    LATIN CAPITAL LETTER C WITH CEDILLA AND ACUTE
U+1E0A    LATIN CAPITAL LETTER D WITH DOT ABOVE
U+1E0C    LATIN CAPITAL LETTER D WITH DOT BELOW
U+1E0E    LATIN CAPITAL LETTER D WITH LINE BELOW
U+1E10    LATIN CAPITAL LETTER D WITH CEDILLA
U+1E12    LATIN CAPITAL LETTER D WITH CIRCUMFLEX BELOW
U+1E14    LATIN CAPITAL LETTER E WITH MACRON AND GRAVE
U+1E16    LATIN CAPITAL LETTER E WITH MACRON AND ACUTE
U+1E18    LATIN CAPITAL LETTER E WITH CIRCUMFLEX BELOW
U+1E1A    LATIN CAPITAL LETTER E WITH TILDE BELOW
U+1E1C    LATIN CAPITAL LETTER E WITH CEDILLA AND BREVE
U+1E1E    LATIN CAPITAL LETTER F WITH DOT ABOVE
U+1E20    LATIN CAPITAL LETTER G WITH MACRON
U+1E22    LATIN CAPITAL LETTER H WITH DOT ABOVE
U+1E24    LATIN CAPITAL LETTER H WITH DOT BELOW
U+1E26    LATIN CAPITAL LETTER H WITH DIAERESIS
U+1E28    LATIN CAPITAL LETTER H WITH CEDILLA
U+1E2A    LATIN CAPITAL LETTER H WITH BREVE BELOW
U+1E2C    LATIN CAPITAL LETTER I WITH TILDE BELOW
U+1E2E    LATIN CAPITAL LETTER I WITH DIAERESIS AND ACUTE
U+1E30    LATIN CAPITAL LETTER K WITH ACUTE
U+1E32    LATIN CAPITAL LETTER K WITH DOT BELOW
U+1E34    LATIN CAPITAL LETTER K WITH LINE BELOW
U+1E36    LATIN CAPITAL LETTER L WITH DOT BELOW
U+1E38    LATIN CAPITAL LETTER L WITH DOT BELOW AND MACRON
U+1E3A    LATIN CAPITAL LETTER L WITH LINE BELOW
U+1E3C    LATIN CAPITAL LETTER L WITH CIRCUMFLEX BELOW
U+1E3E    LATIN CAPITAL LETTER M WITH ACUTE
U+1E40    LATIN CAPITAL LETTER M WITH DOT ABOVE
U+1E42    LATIN CAPITAL LETTER M WITH DOT BELOW
U+1E44    LATIN CAPITAL LETTER N WITH DOT ABOVE
U+1E46    LATIN CAPITAL LETTER N WITH DOT BELOW
U+1E48    LATIN CAPITAL LETTER N WITH LINE BELOW
U+1E4A    LATIN CAPITAL LETTER N WITH CIRCUMFLEX BELOW
U+1E4C    LATIN CAPITAL LETTER O WITH TILDE AND ACUTE
U+1E4E    LATIN CAPITAL LETTER O WITH TILDE AND DIAERESIS
U+1E50    LATIN CAPITAL LETTER O WITH MACRON AND GRAVE
U+1E52    LATIN CAPITAL LETTER O WITH MACRON AND ACUTE
U+1E54    LATIN CAPITAL LETTER P WITH ACUTE
U+1E56    LATIN CAPITAL LETTER P WITH DOT ABOVE
U+1E58    LATIN CAPITAL LETTER R WITH DOT ABOVE
U+1E5A    LATIN CAPITAL LETTER R WITH DOT BELOW
U+1E5C    LATIN CAPITAL LETTER R WITH DOT BELOW AND MACRON
U+1E5E    LATIN CAPITAL LETTER R WITH LINE BELOW
U+1E60    LATIN CAPITAL LETTER S WITH DOT ABOVE
U+1E62    LATIN CAPITAL LETTER S WITH DOT BELOW
U+1E64    LATIN CAPITAL LETTER S WITH ACUTE AND DOT ABOVE
U+1E66    LATIN CAPITAL LETTER S WITH CARON AND DOT ABOVE
U+1E68    LATIN CAPITAL LETTER S WITH DOT BELOW AND DOT ABOVE
U+1E6A    LATIN CAPITAL LETTER T WITH DOT ABOVE
U+1E6C    LATIN CAPITAL LETTER T WITH DOT BELOW
U+1E6E    LATIN CAPITAL LETTER T WITH LINE BELOW
U+1E70    LATIN CAPITAL LETTER T WITH CIRCUMFLEX BELOW
U+1E72    LATIN CAPITAL LETTER U WITH DIAERESIS BELOW
U+1E74    LATIN CAPITAL LETTER U WITH TILDE BELOW
U+1E76    LATIN CAPITAL LETTER U WITH CIRCUMFLEX BELOW
U+1E78    LATIN CAPITAL LETTER U WITH TILDE AND ACUTE
U+1E7A    LATIN CAPITAL LETTER U WITH MACRON AND DIAERESIS
U+1E7C    LATIN CAPITAL LETTER V WITH TILDE
U+1E7E    LATIN CAPITAL LETTER V WITH DOT BELOW
U+1E80    LATIN CAPITAL LETTER W WITH GRAVE
U+1E82    LATIN CAPITAL LETTER W WITH ACUTE
U+1E84    LATIN CAPITAL LETTER W WITH DIAERESIS
U+1E86    LATIN CAPITAL LETTER W WITH DOT ABOVE
U+1E88    LATIN CAPITAL LETTER W WITH DOT BELOW
U+1E8A    LATIN CAPITAL LETTER X WITH DOT ABOVE
U+1E8C    LATIN CAPITAL LETTER X WITH DIAERESIS
U+1E8E    LATIN CAPITAL LETTER Y WITH DOT ABOVE
U+1E90    LATIN CAPITAL LETTER Z WITH CIRCUMFLEX
U+1E92    LATIN CAPITAL LETTER Z WITH DOT BELOW
U+1E94    LATIN CAPITAL LETTER Z WITH LINE BELOW
U+1E9E    LATIN CAPITAL LETTER SHARP S
U+1EA0    LATIN CAPITAL LETTER A WITH DOT BELOW
U+1EA2    LATIN CAPITAL LETTER A WITH HOOK ABOVE
U+1EA4    LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND ACUTE
U+1EA6    LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND GRAVE
U+1EA8    LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND HOOK ABOVE
U+1EAA    LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND TILDE
U+1EAC    LATIN CAPITAL LETTER A WITH CIRCUMFLEX AND DOT BELOW
U+1EAE    LATIN CAPITAL LETTER A WITH BREVE AND ACUTE
U+1EB0    LATIN CAPITAL LETTER A WITH BREVE AND GRAVE
U+1EB2    LATIN CAPITAL LETTER A WITH BREVE AND HOOK ABOVE
U+1EB4    LATIN CAPITAL LETTER A WITH BREVE AND TILDE
U+1EB6    LATIN CAPITAL LETTER A WITH BREVE AND DOT BELOW
U+1EB8    LATIN CAPITAL LETTER E WITH DOT BELOW
U+1EBA    LATIN CAPITAL LETTER E WITH HOOK ABOVE
U+1EBC    LATIN CAPITAL LETTER E WITH TILDE
U+1EBE    LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND ACUTE
U+1EC0    LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND GRAVE
U+1EC2    LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND HOOK ABOVE
U+1EC4    LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND TILDE
U+1EC6    LATIN CAPITAL LETTER E WITH CIRCUMFLEX AND DOT BELOW
U+1EC8    LATIN CAPITAL LETTER I WITH HOOK ABOVE
U+1ECA    LATIN CAPITAL LETTER I WITH DOT BELOW
U+1ECC    LATIN CAPITAL LETTER O WITH DOT BELOW
U+1ECE    LATIN CAPITAL LETTER O WITH HOOK ABOVE
U+1ED0    LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND ACUTE
U+1ED2    LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND GRAVE
U+1ED4    LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND HOOK ABOVE
U+1ED6    LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND TILDE
U+1ED8    LATIN CAPITAL LETTER O WITH CIRCUMFLEX AND DOT BELOW
U+1EDA    LATIN CAPITAL LETTER O WITH HORN AND ACUTE
U+1EDC    LATIN CAPITAL LETTER O WITH HORN AND GRAVE
U+1EDE    LATIN CAPITAL LETTER O WITH HORN AND HOOK ABOVE
U+1EE0    LATIN CAPITAL LETTER O WITH HORN AND TILDE
U+1EE2    LATIN CAPITAL LETTER O WITH HORN AND DOT BELOW
U+1EE4    LATIN CAPITAL LETTER U WITH DOT BELOW
U+1EE6    LATIN CAPITAL LETTER U WITH HOOK ABOVE
U+1EE8    LATIN CAPITAL LETTER U WITH HORN AND ACUTE
U+1EEA    LATIN CAPITAL LETTER U WITH HORN AND GRAVE
U+1EEC    LATIN CAPITAL LETTER U WITH HORN AND HOOK ABOVE
U+1EEE    LATIN CAPITAL LETTER U WITH HORN AND TILDE
U+1EF0    LATIN CAPITAL LETTER U WITH HORN AND DOT BELOW
U+1EF2    LATIN CAPITAL LETTER Y WITH GRAVE
U+1EF4    LATIN CAPITAL LETTER Y WITH DOT BELOW
U+1EF6    LATIN CAPITAL LETTER Y WITH HOOK ABOVE
U+1EF8    LATIN CAPITAL LETTER Y WITH TILDE
U+1EFA    LATIN CAPITAL LETTER MIDDLE-WELSH LL
U+1EFC    LATIN CAPITAL LETTER MIDDLE-WELSH V
U+1EFE    LATIN CAPITAL LETTER Y WITH LOOP
U+1F08    GREEK CAPITAL LETTER ALPHA WITH PSILI
U+1F09    GREEK CAPITAL LETTER ALPHA WITH DASIA
U+1F0A    GREEK CAPITAL LETTER ALPHA WITH PSILI AND VARIA
U+1F0B    GREEK CAPITAL LETTER ALPHA WITH DASIA AND VARIA
U+1F0C    GREEK CAPITAL LETTER ALPHA WITH PSILI AND OXIA
U+1F0D    GREEK CAPITAL LETTER ALPHA WITH DASIA AND OXIA
U+1F0E    GREEK CAPITAL LETTER ALPHA WITH PSILI AND PERISPOMENI
U+1F0F    GREEK CAPITAL LETTER ALPHA WITH DASIA AND PERISPOMENI
U+1F18    GREEK CAPITAL LETTER EPSILON WITH PSILI
U+1F19    GREEK CAPITAL LETTER EPSILON WITH DASIA
U+1F1A    GREEK CAPITAL LETTER EPSILON WITH PSILI AND VARIA
U+1F1B    GREEK CAPITAL LETTER EPSILON WITH DASIA AND VARIA
U+1F1C    GREEK CAPITAL LETTER EPSILON WITH PSILI AND OXIA
U+1F1D    GREEK CAPITAL LETTER EPSILON WITH DASIA AND OXIA
U+1F28    GREEK CAPITAL LETTER ETA WITH PSILI
U+1F29    GREEK CAPITAL LETTER ETA WITH DASIA
U+1F2A    GREEK CAPITAL LETTER ETA WITH PSILI AND VARIA
U+1F2B    GREEK CAPITAL LETTER ETA WITH DASIA AND VARIA
U+1F2C    GREEK CAPITAL LETTER ETA WITH PSILI AND OXIA
U+1F2D    GREEK CAPITAL LETTER ETA WITH DASIA AND OXIA
U+1F2E    GREEK CAPITAL LETTER ETA WITH PSILI AND PERISPOMENI
U+1F2F    GREEK CAPITAL LETTER ETA WITH DASIA AND PERISPOMENI
U+1F38    GREEK CAPITAL LETTER IOTA WITH PSILI
U+1F39    GREEK CAPITAL LETTER IOTA WITH DASIA
U+1F3A    GREEK CAPITAL LETTER IOTA WITH PSILI AND VARIA
U+1F3B    GREEK CAPITAL LETTER IOTA WITH DASIA AND VARIA
U+1F3C    GREEK CAPITAL LETTER IOTA WITH PSILI AND OXIA
U+1F3D    GREEK CAPITAL LETTER IOTA WITH DASIA AND OXIA
U+1F3E    GREEK CAPITAL LETTER IOTA WITH PSILI AND PERISPOMENI
U+1F3F    GREEK CAPITAL LETTER IOTA WITH DASIA AND PERISPOMENI
U+1F48    GREEK CAPITAL LETTER OMICRON WITH PSILI
U+1F49    GREEK CAPITAL LETTER OMICRON WITH DASIA
U+1F4A    GREEK CAPITAL LETTER OMICRON WITH PSILI AND VARIA
U+1F4B    GREEK CAPITAL LETTER OMICRON WITH DASIA AND VARIA
U+1F4C    GREEK CAPITAL LETTER OMICRON WITH PSILI AND OXIA
U+1F4D    GREEK CAPITAL LETTER OMICRON WITH DASIA AND OXIA
U+1F59    GREEK CAPITAL LETTER UPSILON WITH DASIA
U+1F5B    GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA
U+1F5D    GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA
U+1F5F    GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI
U+1F68    GREEK CAPITAL LETTER OMEGA WITH PSILI
U+1F69    GREEK CAPITAL LETTER OMEGA WITH DASIA
U+1F6A    GREEK CAPITAL LETTER OMEGA WITH PSILI AND VARIA
U+1F6B    GREEK CAPITAL LETTER OMEGA WITH DASIA AND VARIA
U+1F6C    GREEK CAPITAL LETTER OMEGA WITH PSILI AND OXIA
U+1F6D    GREEK CAPITAL LETTER OMEGA WITH DASIA AND OXIA
U+1F6E    GREEK CAPITAL LETTER OMEGA WITH PSILI AND PERISPOMENI
U+1F6F    GREEK CAPITAL LETTER OMEGA WITH DASIA AND PERISPOMENI
U+1FB8    GREEK CAPITAL LETTER ALPHA WITH VRACHY
U+1FB9    GREEK CAPITAL LETTER ALPHA WITH MACRON
U+1FBA    GREEK CAPITAL LETTER ALPHA WITH VARIA
U+1FBB    GREEK CAPITAL LETTER ALPHA WITH OXIA
U+1FC8    GREEK CAPITAL LETTER EPSILON WITH VARIA
U+1FC9    GREEK CAPITAL LETTER EPSILON WITH OXIA
U+1FCA    GREEK CAPITAL LETTER ETA WITH VARIA
U+1FCB    GREEK CAPITAL LETTER ETA WITH OXIA
U+1FD8    GREEK CAPITAL LETTER IOTA WITH VRACHY
U+1FD9    GREEK CAPITAL LETTER IOTA WITH MACRON
U+1FDA    GREEK CAPITAL LETTER IOTA WITH VARIA
U+1FDB    GREEK CAPITAL LETTER IOTA WITH OXIA
U+1FE8    GREEK CAPITAL LETTER UPSILON WITH VRACHY
U+1FE9    GREEK CAPITAL LETTER UPSILON WITH MACRON
U+1FEA    GREEK CAPITAL LETTER UPSILON WITH VARIA
U+1FEB    GREEK CAPITAL LETTER UPSILON WITH OXIA
U+1FEC    GREEK CAPITAL LETTER RHO WITH DASIA
U+1FF8    GREEK CAPITAL LETTER OMICRON WITH VARIA
U+1FF9    GREEK CAPITAL LETTER OMICRON WITH OXIA
U+1FFA    GREEK CAPITAL LETTER OMEGA WITH VARIA
U+1FFB    GREEK CAPITAL LETTER OMEGA WITH OXIA
U+2102    DOUBLE-STRUCK CAPITAL C
U+2107    EULER CONSTANT
U+210B    SCRIPT CAPITAL H
U+210C    BLACK-LETTER CAPITAL H
U+210D    DOUBLE-STRUCK CAPITAL H
U+2110    SCRIPT CAPITAL I
U+2111    BLACK-LETTER CAPITAL I
U+2112    SCRIPT CAPITAL L
U+2115    DOUBLE-STRUCK CAPITAL N
U+2119    DOUBLE-STRUCK CAPITAL P
U+211A    DOUBLE-STRUCK CAPITAL Q
U+211B    SCRIPT CAPITAL R
U+211C    BLACK-LETTER CAPITAL R
U+211D    DOUBLE-STRUCK CAPITAL R
U+2124    DOUBLE-STRUCK CAPITAL Z
U+2126    OHM SIGN
U+2128    BLACK-LETTER CAPITAL Z
U+212A    KELVIN SIGN
U+212B    ANGSTROM SIGN
U+212C    SCRIPT CAPITAL B
U+212D    BLACK-LETTER CAPITAL C
U+2130    SCRIPT CAPITAL E
U+2131    SCRIPT CAPITAL F
U+2132    TURNED CAPITAL F
U+2133    SCRIPT CAPITAL M
U+213E    DOUBLE-STRUCK CAPITAL GAMMA
U+213F    DOUBLE-STRUCK CAPITAL PI
U+2145    DOUBLE-STRUCK ITALIC CAPITAL D
U+2183    ROMAN NUMERAL REVERSED ONE HUNDRED
U+2C00    GLAGOLITIC CAPITAL LETTER AZU
U+2C01    GLAGOLITIC CAPITAL LETTER BUKY
U+2C02    GLAGOLITIC CAPITAL LETTER VEDE
U+2C03    GLAGOLITIC CAPITAL LETTER GLAGOLI
U+2C04    GLAGOLITIC CAPITAL LETTER DOBRO
U+2C05    GLAGOLITIC CAPITAL LETTER YESTU
U+2C06    GLAGOLITIC CAPITAL LETTER ZHIVETE
U+2C07    GLAGOLITIC CAPITAL LETTER DZELO
U+2C08    GLAGOLITIC CAPITAL LETTER ZEMLJA
U+2C09    GLAGOLITIC CAPITAL LETTER IZHE
U+2C0A    GLAGOLITIC CAPITAL LETTER INITIAL IZHE
U+2C0B    GLAGOLITIC CAPITAL LETTER I
U+2C0C    GLAGOLITIC CAPITAL LETTER DJERVI
U+2C0D    GLAGOLITIC CAPITAL LETTER KAKO
U+2C0E    GLAGOLITIC CAPITAL LETTER LJUDIJE
U+2C0F    GLAGOLITIC CAPITAL LETTER MYSLITE
U+2C10    GLAGOLITIC CAPITAL LETTER NASHI
U+2C11    GLAGOLITIC CAPITAL LETTER ONU
U+2C12    GLAGOLITIC CAPITAL LETTER POKOJI
U+2C13    GLAGOLITIC CAPITAL LETTER RITSI
U+2C14    GLAGOLITIC CAPITAL LETTER SLOVO
U+2C15    GLAGOLITIC CAPITAL LETTER TVRIDO
U+2C16    GLAGOLITIC CAPITAL LETTER UKU
U+2C17    GLAGOLITIC CAPITAL LETTER FRITU
U+2C18    GLAGOLITIC CAPITAL LETTER HERU
U+2C19    GLAGOLITIC CAPITAL LETTER OTU
U+2C1A    GLAGOLITIC CAPITAL LETTER PE
U+2C1B    GLAGOLITIC CAPITAL LETTER SHTA
U+2C1C    GLAGOLITIC CAPITAL LETTER TSI
U+2C1D    GLAGOLITIC CAPITAL LETTER CHRIVI
U+2C1E    GLAGOLITIC CAPITAL LETTER SHA
U+2C1F    GLAGOLITIC CAPITAL LETTER YERU
U+2C20    GLAGOLITIC CAPITAL LETTER YERI
U+2C21    GLAGOLITIC CAPITAL LETTER YATI
U+2C22    GLAGOLITIC CAPITAL LETTER SPIDERY HA
U+2C23    GLAGOLITIC CAPITAL LETTER YU
U+2C24    GLAGOLITIC CAPITAL LETTER SMALL YUS
U+2C25    GLAGOLITIC CAPITAL LETTER SMALL YUS WITH TAIL
U+2C26    GLAGOLITIC CAPITAL LETTER YO
U+2C27    GLAGOLITIC CAPITAL LETTER IOTATED SMALL YUS
U+2C28    GLAGOLITIC CAPITAL LETTER BIG YUS
U+2C29    GLAGOLITIC CAPITAL LETTER IOTATED BIG YUS
U+2C2A    GLAGOLITIC CAPITAL LETTER FITA
U+2C2B    GLAGOLITIC CAPITAL LETTER IZHITSA
U+2C2C    GLAGOLITIC CAPITAL LETTER SHTAPIC
U+2C2D    GLAGOLITIC CAPITAL LETTER TROKUTASTI A
U+2C2E    GLAGOLITIC CAPITAL LETTER LATINATE MYSLITE
U+2C60    LATIN CAPITAL LETTER L WITH DOUBLE BAR
U+2C62    LATIN CAPITAL LETTER L WITH MIDDLE TILDE
U+2C63    LATIN CAPITAL LETTER P WITH STROKE
U+2C64    LATIN CAPITAL LETTER R WITH TAIL
U+2C67    LATIN CAPITAL LETTER H WITH DESCENDER
U+2C69    LATIN CAPITAL LETTER K WITH DESCENDER
U+2C6B    LATIN CAPITAL LETTER Z WITH DESCENDER
U+2C6D    LATIN CAPITAL LETTER ALPHA
U+2C6E    LATIN CAPITAL LETTER M WITH HOOK
U+2C6F    LATIN CAPITAL LETTER TURNED A
U+2C70    LATIN CAPITAL LETTER TURNED ALPHA
U+2C72    LATIN CAPITAL LETTER W WITH HOOK
U+2C75    LATIN CAPITAL LETTER HALF H
U+2C7E    LATIN CAPITAL LETTER S WITH SWASH TAIL
U+2C7F    LATIN CAPITAL LETTER Z WITH SWASH TAIL
U+2C80    COPTIC CAPITAL LETTER ALFA
U+2C82    COPTIC CAPITAL LETTER VIDA
U+2C84    COPTIC CAPITAL LETTER GAMMA
U+2C86    COPTIC CAPITAL LETTER DALDA
U+2C88    COPTIC CAPITAL LETTER EIE
U+2C8A    COPTIC CAPITAL LETTER SOU
U+2C8C    COPTIC CAPITAL LETTER ZATA
U+2C8E    COPTIC CAPITAL LETTER HATE
U+2C90    COPTIC CAPITAL LETTER THETHE
U+2C92    COPTIC CAPITAL LETTER IAUDA
U+2C94    COPTIC CAPITAL LETTER KAPA
U+2C96    COPTIC CAPITAL LETTER LAULA
U+2C98    COPTIC CAPITAL LETTER MI
U+2C9A    COPTIC CAPITAL LETTER NI
U+2C9C    COPTIC CAPITAL LETTER KSI
U+2C9E    COPTIC CAPITAL LETTER O
U+2CA0    COPTIC CAPITAL LETTER PI
U+2CA2    COPTIC CAPITAL LETTER RO
U+2CA4    COPTIC CAPITAL LETTER SIMA
U+2CA6    COPTIC CAPITAL LETTER TAU
U+2CA8    COPTIC CAPITAL LETTER UA
U+2CAA    COPTIC CAPITAL LETTER FI
U+2CAC    COPTIC CAPITAL LETTER KHI
U+2CAE    COPTIC CAPITAL LETTER PSI
U+2CB0    COPTIC CAPITAL LETTER OOU
U+2CB2    COPTIC CAPITAL LETTER DIALECT-P ALEF
U+2CB4    COPTIC CAPITAL LETTER OLD COPTIC AIN
U+2CB6    COPTIC CAPITAL LETTER CRYPTOGRAMMIC EIE
U+2CB8    COPTIC CAPITAL LETTER DIALECT-P KAPA
U+2CBA    COPTIC CAPITAL LETTER DIALECT-P NI
U+2CBC    COPTIC CAPITAL LETTER CRYPTOGRAMMIC NI
U+2CBE    COPTIC CAPITAL LETTER OLD COPTIC OOU
U+2CC0    COPTIC CAPITAL LETTER SAMPI
U+2CC2    COPTIC CAPITAL LETTER CROSSED SHEI
U+2CC4    COPTIC CAPITAL LETTER OLD COPTIC SHEI
U+2CC6    COPTIC CAPITAL LETTER OLD COPTIC ESH
U+2CC8    COPTIC CAPITAL LETTER AKHMIMIC KHEI
U+2CCA    COPTIC CAPITAL LETTER DIALECT-P HORI
U+2CCC    COPTIC CAPITAL LETTER OLD COPTIC HORI
U+2CCE    COPTIC CAPITAL LETTER OLD COPTIC HA
U+2CD0    COPTIC CAPITAL LETTER L-SHAPED HA
U+2CD2    COPTIC CAPITAL LETTER OLD COPTIC HEI
U+2CD4    COPTIC CAPITAL LETTER OLD COPTIC HAT
U+2CD6    COPTIC CAPITAL LETTER OLD COPTIC GANGIA
U+2CD8    COPTIC CAPITAL LETTER OLD COPTIC DJA
U+2CDA    COPTIC CAPITAL LETTER OLD COPTIC SHIMA
U+2CDC    COPTIC CAPITAL LETTER OLD NUBIAN SHIMA
U+2CDE    COPTIC CAPITAL LETTER OLD NUBIAN NGI
U+2CE0    COPTIC CAPITAL LETTER OLD NUBIAN NYI
U+2CE2    COPTIC CAPITAL LETTER OLD NUBIAN WAU
U+2CEB    COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI
U+2CED    COPTIC CAPITAL LETTER CRYPTOGRAMMIC GANGIA
U+2CF2    COPTIC CAPITAL LETTER BOHAIRIC KHEI
U+A640    CYRILLIC CAPITAL LETTER ZEMLYA
U+A642    CYRILLIC CAPITAL LETTER DZELO
U+A644    CYRILLIC CAPITAL LETTER REVERSED DZE
U+A646    CYRILLIC CAPITAL LETTER IOTA
U+A648    CYRILLIC CAPITAL LETTER DJERV
U+A64A    CYRILLIC CAPITAL LETTER MONOGRAPH UK
U+A64C    CYRILLIC CAPITAL LETTER BROAD OMEGA
U+A64E    CYRILLIC CAPITAL LETTER NEUTRAL YER
U+A650    CYRILLIC CAPITAL LETTER YERU WITH BACK YER
U+A652    CYRILLIC CAPITAL LETTER IOTIFIED YAT
U+A654    CYRILLIC CAPITAL LETTER REVERSED YU
U+A656    CYRILLIC CAPITAL LETTER IOTIFIED A
U+A658    CYRILLIC CAPITAL LETTER CLOSED LITTLE YUS
U+A65A    CYRILLIC CAPITAL LETTER BLENDED YUS
U+A65C    CYRILLIC CAPITAL LETTER IOTIFIED CLOSED LITTLE YUS
U+A65E    CYRILLIC CAPITAL LETTER YN
U+A660    CYRILLIC CAPITAL LETTER REVERSED TSE
U+A662    CYRILLIC CAPITAL LETTER SOFT DE
U+A664    CYRILLIC CAPITAL LETTER SOFT EL
U+A666    CYRILLIC CAPITAL LETTER SOFT EM
U+A668    CYRILLIC CAPITAL LETTER MONOCULAR O
U+A66A    CYRILLIC CAPITAL LETTER BINOCULAR O
U+A66C    CYRILLIC CAPITAL LETTER DOUBLE MONOCULAR O
U+A680    CYRILLIC CAPITAL LETTER DWE
U+A682    CYRILLIC CAPITAL LETTER DZWE
U+A684    CYRILLIC CAPITAL LETTER ZHWE
U+A686    CYRILLIC CAPITAL LETTER CCHE
U+A688    CYRILLIC CAPITAL LETTER DZZE
U+A68A    CYRILLIC CAPITAL LETTER TE WITH MIDDLE HOOK
U+A68C    CYRILLIC CAPITAL LETTER TWE
U+A68E    CYRILLIC CAPITAL LETTER TSWE
U+A690    CYRILLIC CAPITAL LETTER TSSE
U+A692    CYRILLIC CAPITAL LETTER TCHE
U+A694    CYRILLIC CAPITAL LETTER HWE
U+A696    CYRILLIC CAPITAL LETTER SHWE
U+A698    CYRILLIC CAPITAL LETTER DOUBLE O
U+A69A    CYRILLIC CAPITAL LETTER CROSSED O
U+A722    LATIN CAPITAL LETTER EGYPTOLOGICAL ALEF
U+A724    LATIN CAPITAL LETTER EGYPTOLOGICAL AIN
U+A726    LATIN CAPITAL LETTER HENG
U+A728    LATIN CAPITAL LETTER TZ
U+A72A    LATIN CAPITAL LETTER TRESILLO
U+A72C    LATIN CAPITAL LETTER CUATRILLO
U+A72E    LATIN CAPITAL LETTER CUATRILLO WITH COMMA
U+A732    LATIN CAPITAL LETTER AA
U+A734    LATIN CAPITAL LETTER AO
U+A736    LATIN CAPITAL LETTER AU
U+A738    LATIN CAPITAL LETTER AV
U+A73A    LATIN CAPITAL LETTER AV WITH HORIZONTAL BAR
U+A73C    LATIN CAPITAL LETTER AY
U+A73E    LATIN CAPITAL LETTER REVERSED C WITH DOT
U+A740    LATIN CAPITAL LETTER K WITH STROKE
U+A742    LATIN CAPITAL LETTER K WITH DIAGONAL STROKE
U+A744    LATIN CAPITAL LETTER K WITH STROKE AND DIAGONAL STROKE
U+A746    LATIN CAPITAL LETTER BROKEN L
U+A748    LATIN CAPITAL LETTER L WITH HIGH STROKE
U+A74A    LATIN CAPITAL LETTER O WITH LONG STROKE OVERLAY
U+A74C    LATIN CAPITAL LETTER O WITH LOOP
U+A74E    LATIN CAPITAL LETTER OO
U+A750    LATIN CAPITAL LETTER P WITH STROKE THROUGH DESCENDER
U+A752    LATIN CAPITAL LETTER P WITH FLOURISH
U+A754    LATIN CAPITAL LETTER P WITH SQUIRREL TAIL
U+A756    LATIN CAPITAL LETTER Q WITH STROKE THROUGH DESCENDER
U+A758    LATIN CAPITAL LETTER Q WITH DIAGONAL STROKE
U+A75A    LATIN CAPITAL LETTER R ROTUNDA
U+A75C    LATIN CAPITAL LETTER RUM ROTUNDA
U+A75E    LATIN CAPITAL LETTER V WITH DIAGONAL STROKE
U+A760    LATIN CAPITAL LETTER VY
U+A762    LATIN CAPITAL LETTER VISIGOTHIC Z
U+A764    LATIN CAPITAL LETTER THORN WITH STROKE
U+A766    LATIN CAPITAL LETTER THORN WITH STROKE THROUGH DESCENDER
U+A768    LATIN CAPITAL LETTER VEND
U+A76A    LATIN CAPITAL LETTER ET
U+A76C    LATIN CAPITAL LETTER IS
U+A76E    LATIN CAPITAL LETTER CON
U+A779    LATIN CAPITAL LETTER INSULAR D
U+A77B    LATIN CAPITAL LETTER INSULAR F
U+A77D    LATIN CAPITAL LETTER INSULAR G
U+A77E    LATIN CAPITAL LETTER TURNED INSULAR G
U+A780    LATIN CAPITAL LETTER TURNED L
U+A782    LATIN CAPITAL LETTER INSULAR R
U+A784    LATIN CAPITAL LETTER INSULAR S
U+A786    LATIN CAPITAL LETTER INSULAR T
U+A78B    LATIN CAPITAL LETTER SALTILLO
U+A78D    LATIN CAPITAL LETTER TURNED H
U+A790    LATIN CAPITAL LETTER N WITH DESCENDER
U+A792    LATIN CAPITAL LETTER C WITH BAR
U+A796    LATIN CAPITAL LETTER B WITH FLOURISH
U+A798    LATIN CAPITAL LETTER F WITH STROKE
U+A79A    LATIN CAPITAL LETTER VOLAPUK AE
U+A79C    LATIN CAPITAL LETTER VOLAPUK OE
U+A79E    LATIN CAPITAL LETTER VOLAPUK UE
U+A7A0    LATIN CAPITAL LETTER G WITH OBLIQUE STROKE
U+A7A2    LATIN CAPITAL LETTER K WITH OBLIQUE STROKE
U+A7A4    LATIN CAPITAL LETTER N WITH OBLIQUE STROKE
U+A7A6    LATIN CAPITAL LETTER R WITH OBLIQUE STROKE
U+A7A8    LATIN CAPITAL LETTER S WITH OBLIQUE STROKE
U+A7AA    LATIN CAPITAL LETTER H WITH HOOK
U+A7AB    LATIN CAPITAL LETTER REVERSED OPEN E
U+A7AC    LATIN CAPITAL LETTER SCRIPT G
U+A7AD    LATIN CAPITAL LETTER L WITH BELT
U+A7B0    LATIN CAPITAL LETTER TURNED K
U+A7B1    LATIN CAPITAL LETTER TURNED T
U+A7B2    LATIN CAPITAL LETTER J WITH CROSSED-TAIL
U+A7B3    LATIN CAPITAL LETTER CHI
U+A7B4    LATIN CAPITAL LETTER BETA
U+A7B6    LATIN CAPITAL LETTER OMEGA
U+FF21    FULLWIDTH LATIN CAPITAL LETTER A
U+FF22    FULLWIDTH LATIN CAPITAL LETTER B
U+FF23    FULLWIDTH LATIN CAPITAL LETTER C
U+FF24    FULLWIDTH LATIN CAPITAL LETTER D
U+FF25    FULLWIDTH LATIN CAPITAL LETTER E
U+FF26    FULLWIDTH LATIN CAPITAL LETTER F
U+FF27    FULLWIDTH LATIN CAPITAL LETTER G
U+FF28    FULLWIDTH LATIN CAPITAL LETTER H
U+FF29    FULLWIDTH LATIN CAPITAL LETTER I
U+FF2A    FULLWIDTH LATIN CAPITAL LETTER J
U+FF2B    FULLWIDTH LATIN CAPITAL LETTER K
U+FF2C    FULLWIDTH LATIN CAPITAL LETTER L
U+FF2D    FULLWIDTH LATIN CAPITAL LETTER M
U+FF2E    FULLWIDTH LATIN CAPITAL LETTER N
U+FF2F    FULLWIDTH LATIN CAPITAL LETTER O
U+FF30    FULLWIDTH LATIN CAPITAL LETTER P
U+FF31    FULLWIDTH LATIN CAPITAL LETTER Q
U+FF32    FULLWIDTH LATIN CAPITAL LETTER R
U+FF33    FULLWIDTH LATIN CAPITAL LETTER S
U+FF34    FULLWIDTH LATIN CAPITAL LETTER T
U+FF35    FULLWIDTH LATIN CAPITAL LETTER U
U+FF36    FULLWIDTH LATIN CAPITAL LETTER V
U+FF37    FULLWIDTH LATIN CAPITAL LETTER W
U+FF38    FULLWIDTH LATIN CAPITAL LETTER X
U+FF39    FULLWIDTH LATIN CAPITAL LETTER Y
U+FF3A    FULLWIDTH LATIN CAPITAL LETTER Z
U+10400    DESERET CAPITAL LETTER LONG I
U+10401    DESERET CAPITAL LETTER LONG E
U+10402    DESERET CAPITAL LETTER LONG A
U+10403    DESERET CAPITAL LETTER LONG AH
U+10404    DESERET CAPITAL LETTER LONG O
U+10405    DESERET CAPITAL LETTER LONG OO
U+10406    DESERET CAPITAL LETTER SHORT I
U+10407    DESERET CAPITAL LETTER SHORT E
U+10408    DESERET CAPITAL LETTER SHORT A
U+10409    DESERET CAPITAL LETTER SHORT AH
U+1040A    DESERET CAPITAL LETTER SHORT O
U+1040B    DESERET CAPITAL LETTER SHORT OO
U+1040C    DESERET CAPITAL LETTER AY
U+1040D    DESERET CAPITAL LETTER OW
U+1040E    DESERET CAPITAL LETTER WU
U+1040F    DESERET CAPITAL LETTER YEE
U+10410    DESERET CAPITAL LETTER H
U+10411    DESERET CAPITAL LETTER PEE
U+10412    DESERET CAPITAL LETTER BEE
U+10413    DESERET CAPITAL LETTER TEE
U+10414    DESERET CAPITAL LETTER DEE
U+10415    DESERET CAPITAL LETTER CHEE
U+10416    DESERET CAPITAL LETTER JEE
U+10417    DESERET CAPITAL LETTER KAY
U+10418    DESERET CAPITAL LETTER GAY
U+10419    DESERET CAPITAL LETTER EF
U+1041A    DESERET CAPITAL LETTER VEE
U+1041B    DESERET CAPITAL LETTER ETH
U+1041C    DESERET CAPITAL LETTER THEE
U+1041D    DESERET CAPITAL LETTER ES
U+1041E    DESERET CAPITAL LETTER ZEE
U+1041F    DESERET CAPITAL LETTER ESH
U+10420    DESERET CAPITAL LETTER ZHEE
U+10421    DESERET CAPITAL LETTER ER
U+10422    DESERET CAPITAL LETTER EL
U+10423    DESERET CAPITAL LETTER EM
U+10424    DESERET CAPITAL LETTER EN
U+10425    DESERET CAPITAL LETTER ENG
U+10426    DESERET CAPITAL LETTER OI
U+10427    DESERET CAPITAL LETTER EW
U+10C80    OLD HUNGARIAN CAPITAL LETTER A
U+10C81    OLD HUNGARIAN CAPITAL LETTER AA
U+10C82    OLD HUNGARIAN CAPITAL LETTER EB
U+10C83    OLD HUNGARIAN CAPITAL LETTER AMB
U+10C84    OLD HUNGARIAN CAPITAL LETTER EC
U+10C85    OLD HUNGARIAN CAPITAL LETTER ENC
U+10C86    OLD HUNGARIAN CAPITAL LETTER ECS
U+10C87    OLD HUNGARIAN CAPITAL LETTER ED
U+10C88    OLD HUNGARIAN CAPITAL LETTER AND
U+10C89    OLD HUNGARIAN CAPITAL LETTER E
U+10C8A    OLD HUNGARIAN CAPITAL LETTER CLOSE E
U+10C8B    OLD HUNGARIAN CAPITAL LETTER EE
U+10C8C    OLD HUNGARIAN CAPITAL LETTER EF
U+10C8D    OLD HUNGARIAN CAPITAL LETTER EG
U+10C8E    OLD HUNGARIAN CAPITAL LETTER EGY
U+10C8F    OLD HUNGARIAN CAPITAL LETTER EH
U+10C90    OLD HUNGARIAN CAPITAL LETTER I
U+10C91    OLD HUNGARIAN CAPITAL LETTER II
U+10C92    OLD HUNGARIAN CAPITAL LETTER EJ
U+10C93    OLD HUNGARIAN CAPITAL LETTER EK
U+10C94    OLD HUNGARIAN CAPITAL LETTER AK
U+10C95    OLD HUNGARIAN CAPITAL LETTER UNK
U+10C96    OLD HUNGARIAN CAPITAL LETTER EL
U+10C97    OLD HUNGARIAN CAPITAL LETTER ELY
U+10C98    OLD HUNGARIAN CAPITAL LETTER EM
U+10C99    OLD HUNGARIAN CAPITAL LETTER EN
U+10C9A    OLD HUNGARIAN CAPITAL LETTER ENY
U+10C9B    OLD HUNGARIAN CAPITAL LETTER O
U+10C9C    OLD HUNGARIAN CAPITAL LETTER OO
U+10C9D    OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG OE
U+10C9E    OLD HUNGARIAN CAPITAL LETTER RUDIMENTA OE
U+10C9F    OLD HUNGARIAN CAPITAL LETTER OEE
U+10CA0    OLD HUNGARIAN CAPITAL LETTER EP
U+10CA1    OLD HUNGARIAN CAPITAL LETTER EMP
U+10CA2    OLD HUNGARIAN CAPITAL LETTER ER
U+10CA3    OLD HUNGARIAN CAPITAL LETTER SHORT ER
U+10CA4    OLD HUNGARIAN CAPITAL LETTER ES
U+10CA5    OLD HUNGARIAN CAPITAL LETTER ESZ
U+10CA6    OLD HUNGARIAN CAPITAL LETTER ET
U+10CA7    OLD HUNGARIAN CAPITAL LETTER ENT
U+10CA8    OLD HUNGARIAN CAPITAL LETTER ETY
U+10CA9    OLD HUNGARIAN CAPITAL LETTER ECH
U+10CAA    OLD HUNGARIAN CAPITAL LETTER U
U+10CAB    OLD HUNGARIAN CAPITAL LETTER UU
U+10CAC    OLD HUNGARIAN CAPITAL LETTER NIKOLSBURG UE
U+10CAD    OLD HUNGARIAN CAPITAL LETTER RUDIMENTA UE
U+10CAE    OLD HUNGARIAN CAPITAL LETTER EV
U+10CAF    OLD HUNGARIAN CAPITAL LETTER EZ
U+10CB0    OLD HUNGARIAN CAPITAL LETTER EZS
U+10CB1    OLD HUNGARIAN CAPITAL LETTER ENT-SHAPED SIGN
U+10CB2    OLD HUNGARIAN CAPITAL LETTER US
U+118A0    WARANG CITI CAPITAL LETTER NGAA
U+118A1    WARANG CITI CAPITAL LETTER A
U+118A2    WARANG CITI CAPITAL LETTER WI
U+118A3    WARANG CITI CAPITAL LETTER YU
U+118A4    WARANG CITI CAPITAL LETTER YA
U+118A5    WARANG CITI CAPITAL LETTER YO
U+118A6    WARANG CITI CAPITAL LETTER II
U+118A7    WARANG CITI CAPITAL LETTER UU
U+118A8    WARANG CITI CAPITAL LETTER E
U+118A9    WARANG CITI CAPITAL LETTER O
U+118AA    WARANG CITI CAPITAL LETTER ANG
U+118AB    WARANG CITI CAPITAL LETTER GA
U+118AC    WARANG CITI CAPITAL LETTER KO
U+118AD    WARANG CITI CAPITAL LETTER ENY
U+118AE    WARANG CITI CAPITAL LETTER YUJ
U+118AF    WARANG CITI CAPITAL LETTER UC
U+118B0    WARANG CITI CAPITAL LETTER ENN
U+118B1    WARANG CITI CAPITAL LETTER ODD
U+118B2    WARANG CITI CAPITAL LETTER TTE
U+118B3    WARANG CITI CAPITAL LETTER NUNG
U+118B4    WARANG CITI CAPITAL LETTER DA
U+118B5    WARANG CITI CAPITAL LETTER AT
U+118B6    WARANG CITI CAPITAL LETTER AM
U+118B7    WARANG CITI CAPITAL LETTER BU
U+118B8    WARANG CITI CAPITAL LETTER PU
U+118B9    WARANG CITI CAPITAL LETTER HIYO
U+118BA    WARANG CITI CAPITAL LETTER HOLO
U+118BB    WARANG CITI CAPITAL LETTER HORR
U+118BC    WARANG CITI CAPITAL LETTER HAR
U+118BD    WARANG CITI CAPITAL LETTER SSUU
U+118BE    WARANG CITI CAPITAL LETTER SII
U+118BF    WARANG CITI CAPITAL LETTER VIYO
U+1D400    MATHEMATICAL BOLD CAPITAL A
U+1D401    MATHEMATICAL BOLD CAPITAL B
U+1D402    MATHEMATICAL BOLD CAPITAL C
U+1D403    MATHEMATICAL BOLD CAPITAL D
U+1D404    MATHEMATICAL BOLD CAPITAL E
U+1D405    MATHEMATICAL BOLD CAPITAL F
U+1D406    MATHEMATICAL BOLD CAPITAL G
U+1D407    MATHEMATICAL BOLD CAPITAL H
U+1D408    MATHEMATICAL BOLD CAPITAL I
U+1D409    MATHEMATICAL BOLD CAPITAL J
U+1D40A    MATHEMATICAL BOLD CAPITAL K
U+1D40B    MATHEMATICAL BOLD CAPITAL L
U+1D40C    MATHEMATICAL BOLD CAPITAL M
U+1D40D    MATHEMATICAL BOLD CAPITAL N
U+1D40E    MATHEMATICAL BOLD CAPITAL O
U+1D40F    MATHEMATICAL BOLD CAPITAL P
U+1D410    MATHEMATICAL BOLD CAPITAL Q
U+1D411    MATHEMATICAL BOLD CAPITAL R
U+1D412    MATHEMATICAL BOLD CAPITAL S
U+1D413    MATHEMATICAL BOLD CAPITAL T
U+1D414    MATHEMATICAL BOLD CAPITAL U
U+1D415    MATHEMATICAL BOLD CAPITAL V
U+1D416    MATHEMATICAL BOLD CAPITAL W
U+1D417    MATHEMATICAL BOLD CAPITAL X
U+1D418    MATHEMATICAL BOLD CAPITAL Y
U+1D419    MATHEMATICAL BOLD CAPITAL Z
U+1D434    MATHEMATICAL ITALIC CAPITAL A
U+1D435    MATHEMATICAL ITALIC CAPITAL B
U+1D436    MATHEMATICAL ITALIC CAPITAL C
U+1D437    MATHEMATICAL ITALIC CAPITAL D
U+1D438    MATHEMATICAL ITALIC CAPITAL E
U+1D439    MATHEMATICAL ITALIC CAPITAL F
U+1D43A    MATHEMATICAL ITALIC CAPITAL G
U+1D43B    MATHEMATICAL ITALIC CAPITAL H
U+1D43C    MATHEMATICAL ITALIC CAPITAL I
U+1D43D    MATHEMATICAL ITALIC CAPITAL J
U+1D43E    MATHEMATICAL ITALIC CAPITAL K
U+1D43F    MATHEMATICAL ITALIC CAPITAL L
U+1D440    MATHEMATICAL ITALIC CAPITAL M
U+1D441    MATHEMATICAL ITALIC CAPITAL N
U+1D442    MATHEMATICAL ITALIC CAPITAL O
U+1D443    MATHEMATICAL ITALIC CAPITAL P
U+1D444    MATHEMATICAL ITALIC CAPITAL Q
U+1D445    MATHEMATICAL ITALIC CAPITAL R
U+1D446    MATHEMATICAL ITALIC CAPITAL S
U+1D447    MATHEMATICAL ITALIC CAPITAL T
U+1D448    MATHEMATICAL ITALIC CAPITAL U
U+1D449    MATHEMATICAL ITALIC CAPITAL V
U+1D44A    MATHEMATICAL ITALIC CAPITAL W
U+1D44B    MATHEMATICAL ITALIC CAPITAL X
U+1D44C    MATHEMATICAL ITALIC CAPITAL Y
U+1D44D    MATHEMATICAL ITALIC CAPITAL Z
U+1D468    MATHEMATICAL BOLD ITALIC CAPITAL A
U+1D469    MATHEMATICAL BOLD ITALIC CAPITAL B
U+1D46A    MATHEMATICAL BOLD ITALIC CAPITAL C
U+1D46B    MATHEMATICAL BOLD ITALIC CAPITAL D
U+1D46C    MATHEMATICAL BOLD ITALIC CAPITAL E
U+1D46D    MATHEMATICAL BOLD ITALIC CAPITAL F
U+1D46E    MATHEMATICAL BOLD ITALIC CAPITAL G
U+1D46F    MATHEMATICAL BOLD ITALIC CAPITAL H
U+1D470    MATHEMATICAL BOLD ITALIC CAPITAL I
U+1D471    MATHEMATICAL BOLD ITALIC CAPITAL J
U+1D472    MATHEMATICAL BOLD ITALIC CAPITAL K
U+1D473    MATHEMATICAL BOLD ITALIC CAPITAL L
U+1D474    MATHEMATICAL BOLD ITALIC CAPITAL M
U+1D475    MATHEMATICAL BOLD ITALIC CAPITAL N
U+1D476    MATHEMATICAL BOLD ITALIC CAPITAL O
U+1D477    MATHEMATICAL BOLD ITALIC CAPITAL P
U+1D478    MATHEMATICAL BOLD ITALIC CAPITAL Q
U+1D479    MATHEMATICAL BOLD ITALIC CAPITAL R
U+1D47A    MATHEMATICAL BOLD ITALIC CAPITAL S
U+1D47B    MATHEMATICAL BOLD ITALIC CAPITAL T
U+1D47C    MATHEMATICAL BOLD ITALIC CAPITAL U
U+1D47D    MATHEMATICAL BOLD ITALIC CAPITAL V
U+1D47E    MATHEMATICAL BOLD ITALIC CAPITAL W
U+1D47F    MATHEMATICAL BOLD ITALIC CAPITAL X
U+1D480    MATHEMATICAL BOLD ITALIC CAPITAL Y
U+1D481    MATHEMATICAL BOLD ITALIC CAPITAL Z
U+1D49C    MATHEMATICAL SCRIPT CAPITAL A
U+1D49E    MATHEMATICAL SCRIPT CAPITAL C
U+1D49F    MATHEMATICAL SCRIPT CAPITAL D
U+1D4A2    MATHEMATICAL SCRIPT CAPITAL G
U+1D4A5    MATHEMATICAL SCRIPT CAPITAL J
U+1D4A6    MATHEMATICAL SCRIPT CAPITAL K
U+1D4A9    MATHEMATICAL SCRIPT CAPITAL N
U+1D4AA    MATHEMATICAL SCRIPT CAPITAL O
U+1D4AB    MATHEMATICAL SCRIPT CAPITAL P
U+1D4AC    MATHEMATICAL SCRIPT CAPITAL Q
U+1D4AE    MATHEMATICAL SCRIPT CAPITAL S
U+1D4AF    MATHEMATICAL SCRIPT CAPITAL T
U+1D4B0    MATHEMATICAL SCRIPT CAPITAL U
U+1D4B1    MATHEMATICAL SCRIPT CAPITAL V
U+1D4B2    MATHEMATICAL SCRIPT CAPITAL W
U+1D4B3    MATHEMATICAL SCRIPT CAPITAL X
U+1D4B4    MATHEMATICAL SCRIPT CAPITAL Y
U+1D4B5    MATHEMATICAL SCRIPT CAPITAL Z
U+1D4D0    MATHEMATICAL BOLD SCRIPT CAPITAL A
U+1D4D1    MATHEMATICAL BOLD SCRIPT CAPITAL B
U+1D4D2    MATHEMATICAL BOLD SCRIPT CAPITAL C
U+1D4D3    MATHEMATICAL BOLD SCRIPT CAPITAL D
U+1D4D4    MATHEMATICAL BOLD SCRIPT CAPITAL E
U+1D4D5    MATHEMATICAL BOLD SCRIPT CAPITAL F
U+1D4D6    MATHEMATICAL BOLD SCRIPT CAPITAL G
U+1D4D7    MATHEMATICAL BOLD SCRIPT CAPITAL H
U+1D4D8    MATHEMATICAL BOLD SCRIPT CAPITAL I
U+1D4D9    MATHEMATICAL BOLD SCRIPT CAPITAL J
U+1D4DA    MATHEMATICAL BOLD SCRIPT CAPITAL K
U+1D4DB    MATHEMATICAL BOLD SCRIPT CAPITAL L
U+1D4DC    MATHEMATICAL BOLD SCRIPT CAPITAL M
U+1D4DD    MATHEMATICAL BOLD SCRIPT CAPITAL N
U+1D4DE    MATHEMATICAL BOLD SCRIPT CAPITAL O
U+1D4DF    MATHEMATICAL BOLD SCRIPT CAPITAL P
U+1D4E0    MATHEMATICAL BOLD SCRIPT CAPITAL Q
U+1D4E1    MATHEMATICAL BOLD SCRIPT CAPITAL R
U+1D4E2    MATHEMATICAL BOLD SCRIPT CAPITAL S
U+1D4E3    MATHEMATICAL BOLD SCRIPT CAPITAL T
U+1D4E4    MATHEMATICAL BOLD SCRIPT CAPITAL U
U+1D4E5    MATHEMATICAL BOLD SCRIPT CAPITAL V
U+1D4E6    MATHEMATICAL BOLD SCRIPT CAPITAL W
U+1D4E7    MATHEMATICAL BOLD SCRIPT CAPITAL X
U+1D4E8    MATHEMATICAL BOLD SCRIPT CAPITAL Y
U+1D4E9    MATHEMATICAL BOLD SCRIPT CAPITAL Z
U+1D504    MATHEMATICAL FRAKTUR CAPITAL A
U+1D505    MATHEMATICAL FRAKTUR CAPITAL B
U+1D507    MATHEMATICAL FRAKTUR CAPITAL D
U+1D508    MATHEMATICAL FRAKTUR CAPITAL E
U+1D509    MATHEMATICAL FRAKTUR CAPITAL F
U+1D50A    MATHEMATICAL FRAKTUR CAPITAL G
U+1D50D    MATHEMATICAL FRAKTUR CAPITAL J
U+1D50E    MATHEMATICAL FRAKTUR CAPITAL K
U+1D50F    MATHEMATICAL FRAKTUR CAPITAL L
U+1D510    MATHEMATICAL FRAKTUR CAPITAL M
U+1D511    MATHEMATICAL FRAKTUR CAPITAL N
U+1D512    MATHEMATICAL FRAKTUR CAPITAL O
U+1D513    MATHEMATICAL FRAKTUR CAPITAL P
U+1D514    MATHEMATICAL FRAKTUR CAPITAL Q
U+1D516    MATHEMATICAL FRAKTUR CAPITAL S
U+1D517    MATHEMATICAL FRAKTUR CAPITAL T
U+1D518    MATHEMATICAL FRAKTUR CAPITAL U
U+1D519    MATHEMATICAL FRAKTUR CAPITAL V
U+1D51A    MATHEMATICAL FRAKTUR CAPITAL W
U+1D51B    MATHEMATICAL FRAKTUR CAPITAL X
U+1D51C    MATHEMATICAL FRAKTUR CAPITAL Y
U+1D538    MATHEMATICAL DOUBLE-STRUCK CAPITAL A
U+1D539    MATHEMATICAL DOUBLE-STRUCK CAPITAL B
U+1D53B    MATHEMATICAL DOUBLE-STRUCK CAPITAL D
U+1D53C    MATHEMATICAL DOUBLE-STRUCK CAPITAL E
U+1D53D    MATHEMATICAL DOUBLE-STRUCK CAPITAL F
U+1D53E    MATHEMATICAL DOUBLE-STRUCK CAPITAL G
U+1D540    MATHEMATICAL DOUBLE-STRUCK CAPITAL I
U+1D541    MATHEMATICAL DOUBLE-STRUCK CAPITAL J
U+1D542    MATHEMATICAL DOUBLE-STRUCK CAPITAL K
U+1D543    MATHEMATICAL DOUBLE-STRUCK CAPITAL L
U+1D544    MATHEMATICAL DOUBLE-STRUCK CAPITAL M
U+1D546    MATHEMATICAL DOUBLE-STRUCK CAPITAL O
U+1D54A    MATHEMATICAL DOUBLE-STRUCK CAPITAL S
U+1D54B    MATHEMATICAL DOUBLE-STRUCK CAPITAL T
U+1D54C    MATHEMATICAL DOUBLE-STRUCK CAPITAL U
U+1D54D    MATHEMATICAL DOUBLE-STRUCK CAPITAL V
U+1D54E    MATHEMATICAL DOUBLE-STRUCK CAPITAL W
U+1D54F    MATHEMATICAL DOUBLE-STRUCK CAPITAL X
U+1D550    MATHEMATICAL DOUBLE-STRUCK CAPITAL Y
U+1D56C    MATHEMATICAL BOLD FRAKTUR CAPITAL A
U+1D56D    MATHEMATICAL BOLD FRAKTUR CAPITAL B
U+1D56E    MATHEMATICAL BOLD FRAKTUR CAPITAL C
U+1D56F    MATHEMATICAL BOLD FRAKTUR CAPITAL D
U+1D570    MATHEMATICAL BOLD FRAKTUR CAPITAL E
U+1D571    MATHEMATICAL BOLD FRAKTUR CAPITAL F
U+1D572    MATHEMATICAL BOLD FRAKTUR CAPITAL G
U+1D573    MATHEMATICAL BOLD FRAKTUR CAPITAL H
U+1D574    MATHEMATICAL BOLD FRAKTUR CAPITAL I
U+1D575    MATHEMATICAL BOLD FRAKTUR CAPITAL J
U+1D576    MATHEMATICAL BOLD FRAKTUR CAPITAL K
U+1D577    MATHEMATICAL BOLD FRAKTUR CAPITAL L
U+1D578    MATHEMATICAL BOLD FRAKTUR CAPITAL M
U+1D579    MATHEMATICAL BOLD FRAKTUR CAPITAL N
U+1D57A    MATHEMATICAL BOLD FRAKTUR CAPITAL O
U+1D57B    MATHEMATICAL BOLD FRAKTUR CAPITAL P
U+1D57C    MATHEMATICAL BOLD FRAKTUR CAPITAL Q
U+1D57D    MATHEMATICAL BOLD FRAKTUR CAPITAL R
U+1D57E    MATHEMATICAL BOLD FRAKTUR CAPITAL S
U+1D57F    MATHEMATICAL BOLD FRAKTUR CAPITAL T
U+1D580    MATHEMATICAL BOLD FRAKTUR CAPITAL U
U+1D581    MATHEMATICAL BOLD FRAKTUR CAPITAL V
U+1D582    MATHEMATICAL BOLD FRAKTUR CAPITAL W
U+1D583    MATHEMATICAL BOLD FRAKTUR CAPITAL X
U+1D584    MATHEMATICAL BOLD FRAKTUR CAPITAL Y
U+1D585    MATHEMATICAL BOLD FRAKTUR CAPITAL Z
U+1D5A0    MATHEMATICAL SANS-SERIF CAPITAL A
U+1D5A1    MATHEMATICAL SANS-SERIF CAPITAL B
U+1D5A2    MATHEMATICAL SANS-SERIF CAPITAL C
U+1D5A3    MATHEMATICAL SANS-SERIF CAPITAL D
U+1D5A4    MATHEMATICAL SANS-SERIF CAPITAL E
U+1D5A5    MATHEMATICAL SANS-SERIF CAPITAL F
U+1D5A6    MATHEMATICAL SANS-SERIF CAPITAL G
U+1D5A7    MATHEMATICAL SANS-SERIF CAPITAL H
U+1D5A8    MATHEMATICAL SANS-SERIF CAPITAL I
U+1D5A9    MATHEMATICAL SANS-SERIF CAPITAL J
U+1D5AA    MATHEMATICAL SANS-SERIF CAPITAL K
U+1D5AB    MATHEMATICAL SANS-SERIF CAPITAL L
U+1D5AC    MATHEMATICAL SANS-SERIF CAPITAL M
U+1D5AD    MATHEMATICAL SANS-SERIF CAPITAL N
U+1D5AE    MATHEMATICAL SANS-SERIF CAPITAL O
U+1D5AF    MATHEMATICAL SANS-SERIF CAPITAL P
U+1D5B0    MATHEMATICAL SANS-SERIF CAPITAL Q
U+1D5B1    MATHEMATICAL SANS-SERIF CAPITAL R
U+1D5B2    MATHEMATICAL SANS-SERIF CAPITAL S
U+1D5B3    MATHEMATICAL SANS-SERIF CAPITAL T
U+1D5B4    MATHEMATICAL SANS-SERIF CAPITAL U
U+1D5B5    MATHEMATICAL SANS-SERIF CAPITAL V
U+1D5B6    MATHEMATICAL SANS-SERIF CAPITAL W
U+1D5B7    MATHEMATICAL SANS-SERIF CAPITAL X
U+1D5B8    MATHEMATICAL SANS-SERIF CAPITAL Y
U+1D5B9    MATHEMATICAL SANS-SERIF CAPITAL Z
U+1D5D4    MATHEMATICAL SANS-SERIF BOLD CAPITAL A
U+1D5D5    MATHEMATICAL SANS-SERIF BOLD CAPITAL B
U+1D5D6    MATHEMATICAL SANS-SERIF BOLD CAPITAL C
U+1D5D7    MATHEMATICAL SANS-SERIF BOLD CAPITAL D
U+1D5D8    MATHEMATICAL SANS-SERIF BOLD CAPITAL E
U+1D5D9    MATHEMATICAL SANS-SERIF BOLD CAPITAL F
U+1D5DA    MATHEMATICAL SANS-SERIF BOLD CAPITAL G
U+1D5DB    MATHEMATICAL SANS-SERIF BOLD CAPITAL H
U+1D5DC    MATHEMATICAL SANS-SERIF BOLD CAPITAL I
U+1D5DD    MATHEMATICAL SANS-SERIF BOLD CAPITAL J
U+1D5DE    MATHEMATICAL SANS-SERIF BOLD CAPITAL K
U+1D5DF    MATHEMATICAL SANS-SERIF BOLD CAPITAL L
U+1D5E0    MATHEMATICAL SANS-SERIF BOLD CAPITAL M
U+1D5E1    MATHEMATICAL SANS-SERIF BOLD CAPITAL N
U+1D5E2    MATHEMATICAL SANS-SERIF BOLD CAPITAL O
U+1D5E3    MATHEMATICAL SANS-SERIF BOLD CAPITAL P
U+1D5E4    MATHEMATICAL SANS-SERIF BOLD CAPITAL Q
U+1D5E5    MATHEMATICAL SANS-SERIF BOLD CAPITAL R
U+1D5E6    MATHEMATICAL SANS-SERIF BOLD CAPITAL S
U+1D5E7    MATHEMATICAL SANS-SERIF BOLD CAPITAL T
U+1D5E8    MATHEMATICAL SANS-SERIF BOLD CAPITAL U
U+1D5E9    MATHEMATICAL SANS-SERIF BOLD CAPITAL V
U+1D5EA    MATHEMATICAL SANS-SERIF BOLD CAPITAL W
U+1D5EB    MATHEMATICAL SANS-SERIF BOLD CAPITAL X
U+1D5EC    MATHEMATICAL SANS-SERIF BOLD CAPITAL Y
U+1D5ED    MATHEMATICAL SANS-SERIF BOLD CAPITAL Z
U+1D608    MATHEMATICAL SANS-SERIF ITALIC CAPITAL A
U+1D609    MATHEMATICAL SANS-SERIF ITALIC CAPITAL B
U+1D60A    MATHEMATICAL SANS-SERIF ITALIC CAPITAL C
U+1D60B    MATHEMATICAL SANS-SERIF ITALIC CAPITAL D
U+1D60C    MATHEMATICAL SANS-SERIF ITALIC CAPITAL E
U+1D60D    MATHEMATICAL SANS-SERIF ITALIC CAPITAL F
U+1D60E    MATHEMATICAL SANS-SERIF ITALIC CAPITAL G
U+1D60F    MATHEMATICAL SANS-SERIF ITALIC CAPITAL H
U+1D610    MATHEMATICAL SANS-SERIF ITALIC CAPITAL I
U+1D611    MATHEMATICAL SANS-SERIF ITALIC CAPITAL J
U+1D612    MATHEMATICAL SANS-SERIF ITALIC CAPITAL K
U+1D613    MATHEMATICAL SANS-SERIF ITALIC CAPITAL L
U+1D614    MATHEMATICAL SANS-SERIF ITALIC CAPITAL M
U+1D615    MATHEMATICAL SANS-SERIF ITALIC CAPITAL N
U+1D616    MATHEMATICAL SANS-SERIF ITALIC CAPITAL O
U+1D617    MATHEMATICAL SANS-SERIF ITALIC CAPITAL P
U+1D618    MATHEMATICAL SANS-SERIF ITALIC CAPITAL Q
U+1D619    MATHEMATICAL SANS-SERIF ITALIC CAPITAL R
U+1D61A    MATHEMATICAL SANS-SERIF ITALIC CAPITAL S
U+1D61B    MATHEMATICAL SANS-SERIF ITALIC CAPITAL T
U+1D61C    MATHEMATICAL SANS-SERIF ITALIC CAPITAL U
U+1D61D    MATHEMATICAL SANS-SERIF ITALIC CAPITAL V
U+1D61E    MATHEMATICAL SANS-SERIF ITALIC CAPITAL W
U+1D61F    MATHEMATICAL SANS-SERIF ITALIC CAPITAL X
U+1D620    MATHEMATICAL SANS-SERIF ITALIC CAPITAL Y
U+1D621    MATHEMATICAL SANS-SERIF ITALIC CAPITAL Z
U+1D63C    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL A
U+1D63D    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL B
U+1D63E    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL C
U+1D63F    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL D
U+1D640    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL E
U+1D641    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL F
U+1D642    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL G
U+1D643    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL H
U+1D644    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I
U+1D645    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL J
U+1D646    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL K
U+1D647    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL L
U+1D648    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL M
U+1D649    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL N
U+1D64A    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL O
U+1D64B    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL P
U+1D64C    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Q
U+1D64D    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL R
U+1D64E    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL S
U+1D64F    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL T
U+1D650    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL U
U+1D651    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL V
U+1D652    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL W
U+1D653    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL X
U+1D654    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Y
U+1D655    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL Z
U+1D670    MATHEMATICAL MONOSPACE CAPITAL A
U+1D671    MATHEMATICAL MONOSPACE CAPITAL B
U+1D672    MATHEMATICAL MONOSPACE CAPITAL C
U+1D673    MATHEMATICAL MONOSPACE CAPITAL D
U+1D674    MATHEMATICAL MONOSPACE CAPITAL E
U+1D675    MATHEMATICAL MONOSPACE CAPITAL F
U+1D676    MATHEMATICAL MONOSPACE CAPITAL G
U+1D677    MATHEMATICAL MONOSPACE CAPITAL H
U+1D678    MATHEMATICAL MONOSPACE CAPITAL I
U+1D679    MATHEMATICAL MONOSPACE CAPITAL J
U+1D67A    MATHEMATICAL MONOSPACE CAPITAL K
U+1D67B    MATHEMATICAL MONOSPACE CAPITAL L
U+1D67C    MATHEMATICAL MONOSPACE CAPITAL M
U+1D67D    MATHEMATICAL MONOSPACE CAPITAL N
U+1D67E    MATHEMATICAL MONOSPACE CAPITAL O
U+1D67F    MATHEMATICAL MONOSPACE CAPITAL P
U+1D680    MATHEMATICAL MONOSPACE CAPITAL Q
U+1D681    MATHEMATICAL MONOSPACE CAPITAL R
U+1D682    MATHEMATICAL MONOSPACE CAPITAL S
U+1D683    MATHEMATICAL MONOSPACE CAPITAL T
U+1D684    MATHEMATICAL MONOSPACE CAPITAL U
U+1D685    MATHEMATICAL MONOSPACE CAPITAL V
U+1D686    MATHEMATICAL MONOSPACE CAPITAL W
U+1D687    MATHEMATICAL MONOSPACE CAPITAL X
U+1D688    MATHEMATICAL MONOSPACE CAPITAL Y
U+1D689    MATHEMATICAL MONOSPACE CAPITAL Z
U+1D6A8    MATHEMATICAL BOLD CAPITAL ALPHA
U+1D6A9    MATHEMATICAL BOLD CAPITAL BETA
U+1D6AA    MATHEMATICAL BOLD CAPITAL GAMMA
U+1D6AB    MATHEMATICAL BOLD CAPITAL DELTA
U+1D6AC    MATHEMATICAL BOLD CAPITAL EPSILON
U+1D6AD    MATHEMATICAL BOLD CAPITAL ZETA
U+1D6AE    MATHEMATICAL BOLD CAPITAL ETA
U+1D6AF    MATHEMATICAL BOLD CAPITAL THETA
U+1D6B0    MATHEMATICAL BOLD CAPITAL IOTA
U+1D6B1    MATHEMATICAL BOLD CAPITAL KAPPA
U+1D6B2    MATHEMATICAL BOLD CAPITAL LAMDA
U+1D6B3    MATHEMATICAL BOLD CAPITAL MU
U+1D6B4    MATHEMATICAL BOLD CAPITAL NU
U+1D6B5    MATHEMATICAL BOLD CAPITAL XI
U+1D6B6    MATHEMATICAL BOLD CAPITAL OMICRON
U+1D6B7    MATHEMATICAL BOLD CAPITAL PI
U+1D6B8    MATHEMATICAL BOLD CAPITAL RHO
U+1D6B9    MATHEMATICAL BOLD CAPITAL THETA SYMBOL
U+1D6BA    MATHEMATICAL BOLD CAPITAL SIGMA
U+1D6BB    MATHEMATICAL BOLD CAPITAL TAU
U+1D6BC    MATHEMATICAL BOLD CAPITAL UPSILON
U+1D6BD    MATHEMATICAL BOLD CAPITAL PHI
U+1D6BE    MATHEMATICAL BOLD CAPITAL CHI
U+1D6BF    MATHEMATICAL BOLD CAPITAL PSI
U+1D6C0    MATHEMATICAL BOLD CAPITAL OMEGA
U+1D6E2    MATHEMATICAL ITALIC CAPITAL ALPHA
U+1D6E3    MATHEMATICAL ITALIC CAPITAL BETA
U+1D6E4    MATHEMATICAL ITALIC CAPITAL GAMMA
U+1D6E5    MATHEMATICAL ITALIC CAPITAL DELTA
U+1D6E6    MATHEMATICAL ITALIC CAPITAL EPSILON
U+1D6E7    MATHEMATICAL ITALIC CAPITAL ZETA
U+1D6E8    MATHEMATICAL ITALIC CAPITAL ETA
U+1D6E9    MATHEMATICAL ITALIC CAPITAL THETA
U+1D6EA    MATHEMATICAL ITALIC CAPITAL IOTA
U+1D6EB    MATHEMATICAL ITALIC CAPITAL KAPPA
U+1D6EC    MATHEMATICAL ITALIC CAPITAL LAMDA
U+1D6ED    MATHEMATICAL ITALIC CAPITAL MU
U+1D6EE    MATHEMATICAL ITALIC CAPITAL NU
U+1D6EF    MATHEMATICAL ITALIC CAPITAL XI
U+1D6F0    MATHEMATICAL ITALIC CAPITAL OMICRON
U+1D6F1    MATHEMATICAL ITALIC CAPITAL PI
U+1D6F2    MATHEMATICAL ITALIC CAPITAL RHO
U+1D6F3    MATHEMATICAL ITALIC CAPITAL THETA SYMBOL
U+1D6F4    MATHEMATICAL ITALIC CAPITAL SIGMA
U+1D6F5    MATHEMATICAL ITALIC CAPITAL TAU
U+1D6F6    MATHEMATICAL ITALIC CAPITAL UPSILON
U+1D6F7    MATHEMATICAL ITALIC CAPITAL PHI
U+1D6F8    MATHEMATICAL ITALIC CAPITAL CHI
U+1D6F9    MATHEMATICAL ITALIC CAPITAL PSI
U+1D6FA    MATHEMATICAL ITALIC CAPITAL OMEGA
U+1D71C    MATHEMATICAL BOLD ITALIC CAPITAL ALPHA
U+1D71D    MATHEMATICAL BOLD ITALIC CAPITAL BETA
U+1D71E    MATHEMATICAL BOLD ITALIC CAPITAL GAMMA
U+1D71F    MATHEMATICAL BOLD ITALIC CAPITAL DELTA
U+1D720    MATHEMATICAL BOLD ITALIC CAPITAL EPSILON
U+1D721    MATHEMATICAL BOLD ITALIC CAPITAL ZETA
U+1D722    MATHEMATICAL BOLD ITALIC CAPITAL ETA
U+1D723    MATHEMATICAL BOLD ITALIC CAPITAL THETA
U+1D724    MATHEMATICAL BOLD ITALIC CAPITAL IOTA
U+1D725    MATHEMATICAL BOLD ITALIC CAPITAL KAPPA
U+1D726    MATHEMATICAL BOLD ITALIC CAPITAL LAMDA
U+1D727    MATHEMATICAL BOLD ITALIC CAPITAL MU
U+1D728    MATHEMATICAL BOLD ITALIC CAPITAL NU
U+1D729    MATHEMATICAL BOLD ITALIC CAPITAL XI
U+1D72A    MATHEMATICAL BOLD ITALIC CAPITAL OMICRON
U+1D72B    MATHEMATICAL BOLD ITALIC CAPITAL PI
U+1D72C    MATHEMATICAL BOLD ITALIC CAPITAL RHO
U+1D72D    MATHEMATICAL BOLD ITALIC CAPITAL THETA SYMBOL
U+1D72E    MATHEMATICAL BOLD ITALIC CAPITAL SIGMA
U+1D72F    MATHEMATICAL BOLD ITALIC CAPITAL TAU
U+1D730    MATHEMATICAL BOLD ITALIC CAPITAL UPSILON
U+1D731    MATHEMATICAL BOLD ITALIC CAPITAL PHI
U+1D732    MATHEMATICAL BOLD ITALIC CAPITAL CHI
U+1D733    MATHEMATICAL BOLD ITALIC CAPITAL PSI
U+1D734    MATHEMATICAL BOLD ITALIC CAPITAL OMEGA
U+1D756    MATHEMATICAL SANS-SERIF BOLD CAPITAL ALPHA
U+1D757    MATHEMATICAL SANS-SERIF BOLD CAPITAL BETA
U+1D758    MATHEMATICAL SANS-SERIF BOLD CAPITAL GAMMA
U+1D759    MATHEMATICAL SANS-SERIF BOLD CAPITAL DELTA
U+1D75A    MATHEMATICAL SANS-SERIF BOLD CAPITAL EPSILON
U+1D75B    MATHEMATICAL SANS-SERIF BOLD CAPITAL ZETA
U+1D75C    MATHEMATICAL SANS-SERIF BOLD CAPITAL ETA
U+1D75D    MATHEMATICAL SANS-SERIF BOLD CAPITAL THETA
U+1D75E    MATHEMATICAL SANS-SERIF BOLD CAPITAL IOTA
U+1D75F    MATHEMATICAL SANS-SERIF BOLD CAPITAL KAPPA
U+1D760    MATHEMATICAL SANS-SERIF BOLD CAPITAL LAMDA
U+1D761    MATHEMATICAL SANS-SERIF BOLD CAPITAL MU
U+1D762    MATHEMATICAL SANS-SERIF BOLD CAPITAL NU
U+1D763    MATHEMATICAL SANS-SERIF BOLD CAPITAL XI
U+1D764    MATHEMATICAL SANS-SERIF BOLD CAPITAL OMICRON
U+1D765    MATHEMATICAL SANS-SERIF BOLD CAPITAL PI
U+1D766    MATHEMATICAL SANS-SERIF BOLD CAPITAL RHO
U+1D767    MATHEMATICAL SANS-SERIF BOLD CAPITAL THETA SYMBOL
U+1D768    MATHEMATICAL SANS-SERIF BOLD CAPITAL SIGMA
U+1D769    MATHEMATICAL SANS-SERIF BOLD CAPITAL TAU
U+1D76A    MATHEMATICAL SANS-SERIF BOLD CAPITAL UPSILON
U+1D76B    MATHEMATICAL SANS-SERIF BOLD CAPITAL PHI
U+1D76C    MATHEMATICAL SANS-SERIF BOLD CAPITAL CHI
U+1D76D    MATHEMATICAL SANS-SERIF BOLD CAPITAL PSI
U+1D76E    MATHEMATICAL SANS-SERIF BOLD CAPITAL OMEGA
U+1D790    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ALPHA
U+1D791    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL BETA
U+1D792    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL GAMMA
U+1D793    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL DELTA
U+1D794    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL EPSILON
U+1D795    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ZETA
U+1D796    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ETA
U+1D797    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL THETA
U+1D798    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL IOTA
U+1D799    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL KAPPA
U+1D79A    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL LAMDA
U+1D79B    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL MU
U+1D79C    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL NU
U+1D79D    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL XI
U+1D79E    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMICRON
U+1D79F    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PI
U+1D7A0    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL RHO
U+1D7A1    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL THETA SYMBOL
U+1D7A2    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL SIGMA
U+1D7A3    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL TAU
U+1D7A4    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL UPSILON
U+1D7A5    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PHI
U+1D7A6    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL CHI
U+1D7A7    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL PSI
U+1D7A8    MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMEGA
U+1D7CA    MATHEMATICAL BOLD CAPITAL DIGAMMA
*/
};

}

#endif // UNICODE_LETTER_UPPERCASE_HPP_INCLUDED
