#ifndef UNICODE_LETTER_MODIFIER_HPP_INCLUDED
#define UNICODE_LETTER_MODIFIER_HPP_INCLUDED

namespace unicode {

// Lm
class letter_modifier
{
/*
Character Name
U+02B0    MODIFIER LETTER SMALL H
U+02B1    MODIFIER LETTER SMALL H WITH HOOK
U+02B2    MODIFIER LETTER SMALL J
U+02B3    MODIFIER LETTER SMALL R
U+02B4    MODIFIER LETTER SMALL TURNED R
U+02B5    MODIFIER LETTER SMALL TURNED R WITH HOOK
U+02B6    MODIFIER LETTER SMALL CAPITAL INVERTED R
U+02B7    MODIFIER LETTER SMALL W
U+02B8    MODIFIER LETTER SMALL Y
U+02B9    MODIFIER LETTER PRIME
U+02BA    MODIFIER LETTER DOUBLE PRIME
U+02BB    MODIFIER LETTER TURNED COMMA
U+02BC    MODIFIER LETTER APOSTROPHE
U+02BD    MODIFIER LETTER REVERSED COMMA
U+02BE    MODIFIER LETTER RIGHT HALF RING
U+02BF    MODIFIER LETTER LEFT HALF RING
U+02C0    MODIFIER LETTER GLOTTAL STOP
U+02C1    MODIFIER LETTER REVERSED GLOTTAL STOP
U+02C6    MODIFIER LETTER CIRCUMFLEX ACCENT
U+02C7    CARON
U+02C8    MODIFIER LETTER VERTICAL LINE
U+02C9    MODIFIER LETTER MACRON
U+02CA    MODIFIER LETTER ACUTE ACCENT
U+02CB    MODIFIER LETTER GRAVE ACCENT
U+02CC    MODIFIER LETTER LOW VERTICAL LINE
U+02CD    MODIFIER LETTER LOW MACRON
U+02CE    MODIFIER LETTER LOW GRAVE ACCENT
U+02CF    MODIFIER LETTER LOW ACUTE ACCENT
U+02D0    MODIFIER LETTER TRIANGULAR COLON
U+02D1    MODIFIER LETTER HALF TRIANGULAR COLON
U+02E0    MODIFIER LETTER SMALL GAMMA
U+02E1    MODIFIER LETTER SMALL L
U+02E2    MODIFIER LETTER SMALL S
U+02E3    MODIFIER LETTER SMALL X
U+02E4    MODIFIER LETTER SMALL REVERSED GLOTTAL STOP
U+02EC    MODIFIER LETTER VOICING
U+02EE    MODIFIER LETTER DOUBLE APOSTROPHE
U+0374    GREEK NUMERAL SIGN
U+037A    GREEK YPOGEGRAMMENI
U+0559    ARMENIAN MODIFIER LETTER LEFT HALF RING
U+0640    ARABIC TATWEEL
U+06E5    ARABIC SMALL WAW
U+06E6    ARABIC SMALL YEH
U+07F4    NKO HIGH TONE APOSTROPHE
U+07F5    NKO LOW TONE APOSTROPHE
U+07FA    NKO LAJANYALAN
U+081A    SAMARITAN MODIFIER LETTER EPENTHETIC YUT
U+0824    SAMARITAN MODIFIER LETTER SHORT A
U+0828    SAMARITAN MODIFIER LETTER I
U+0971    DEVANAGARI SIGN HIGH SPACING DOT
U+0E46    THAI CHARACTER MAIYAMOK
U+0EC6    LAO KO LA
U+10FC    MODIFIER LETTER GEORGIAN NAR
U+17D7    KHMER SIGN LEK TOO
U+1843    MONGOLIAN LETTER TODO LONG VOWEL SIGN
U+1AA7    TAI THAM SIGN MAI YAMOK
U+1C78    OL CHIKI MU TTUDDAG
U+1C79    OL CHIKI GAAHLAA TTUDDAAG
U+1C7A    OL CHIKI MU-GAAHLAA TTUDDAAG
U+1C7B    OL CHIKI RELAA
U+1C7C    OL CHIKI PHAARKAA
U+1C7D    OL CHIKI AHAD
U+1D2C    MODIFIER LETTER CAPITAL A
U+1D2D    MODIFIER LETTER CAPITAL AE
U+1D2E    MODIFIER LETTER CAPITAL B
U+1D2F    MODIFIER LETTER CAPITAL BARRED B
U+1D30    MODIFIER LETTER CAPITAL D
U+1D31    MODIFIER LETTER CAPITAL E
U+1D32    MODIFIER LETTER CAPITAL REVERSED E
U+1D33    MODIFIER LETTER CAPITAL G
U+1D34    MODIFIER LETTER CAPITAL H
U+1D35    MODIFIER LETTER CAPITAL I
U+1D36    MODIFIER LETTER CAPITAL J
U+1D37    MODIFIER LETTER CAPITAL K
U+1D38    MODIFIER LETTER CAPITAL L
U+1D39    MODIFIER LETTER CAPITAL M
U+1D3A    MODIFIER LETTER CAPITAL N
U+1D3B    MODIFIER LETTER CAPITAL REVERSED N
U+1D3C    MODIFIER LETTER CAPITAL O
U+1D3D    MODIFIER LETTER CAPITAL OU
U+1D3E    MODIFIER LETTER CAPITAL P
U+1D3F    MODIFIER LETTER CAPITAL R
U+1D40    MODIFIER LETTER CAPITAL T
U+1D41    MODIFIER LETTER CAPITAL U
U+1D42    MODIFIER LETTER CAPITAL W
U+1D43    MODIFIER LETTER SMALL A
U+1D44    MODIFIER LETTER SMALL TURNED A
U+1D45    MODIFIER LETTER SMALL ALPHA
U+1D46    MODIFIER LETTER SMALL TURNED AE
U+1D47    MODIFIER LETTER SMALL B
U+1D48    MODIFIER LETTER SMALL D
U+1D49    MODIFIER LETTER SMALL E
U+1D4A    MODIFIER LETTER SMALL SCHWA
U+1D4B    MODIFIER LETTER SMALL OPEN E
U+1D4C    MODIFIER LETTER SMALL TURNED OPEN E
U+1D4D    MODIFIER LETTER SMALL G
U+1D4E    MODIFIER LETTER SMALL TURNED I
U+1D4F    MODIFIER LETTER SMALL K
U+1D50    MODIFIER LETTER SMALL M
U+1D51    MODIFIER LETTER SMALL ENG
U+1D52    MODIFIER LETTER SMALL O
U+1D53    MODIFIER LETTER SMALL OPEN O
U+1D54    MODIFIER LETTER SMALL TOP HALF O
U+1D55    MODIFIER LETTER SMALL BOTTOM HALF O
U+1D56    MODIFIER LETTER SMALL P
U+1D57    MODIFIER LETTER SMALL T
U+1D58    MODIFIER LETTER SMALL U
U+1D59    MODIFIER LETTER SMALL SIDEWAYS U
U+1D5A    MODIFIER LETTER SMALL TURNED M
U+1D5B    MODIFIER LETTER SMALL V
U+1D5C    MODIFIER LETTER SMALL AIN
U+1D5D    MODIFIER LETTER SMALL BETA
U+1D5E    MODIFIER LETTER SMALL GREEK GAMMA
U+1D5F    MODIFIER LETTER SMALL DELTA
U+1D60    MODIFIER LETTER SMALL GREEK PHI
U+1D61    MODIFIER LETTER SMALL CHI
U+1D62    LATIN SUBSCRIPT SMALL LETTER I
U+1D63    LATIN SUBSCRIPT SMALL LETTER R
U+1D64    LATIN SUBSCRIPT SMALL LETTER U
U+1D65    LATIN SUBSCRIPT SMALL LETTER V
U+1D66    GREEK SUBSCRIPT SMALL LETTER BETA
U+1D67    GREEK SUBSCRIPT SMALL LETTER GAMMA
U+1D68    GREEK SUBSCRIPT SMALL LETTER RHO
U+1D69    GREEK SUBSCRIPT SMALL LETTER PHI
U+1D6A    GREEK SUBSCRIPT SMALL LETTER CHI
U+1D78    MODIFIER LETTER CYRILLIC EN
U+1D9B    MODIFIER LETTER SMALL TURNED ALPHA
U+1D9C    MODIFIER LETTER SMALL C
U+1D9D    MODIFIER LETTER SMALL C WITH CURL
U+1D9E    MODIFIER LETTER SMALL ETH
U+1D9F    MODIFIER LETTER SMALL REVERSED OPEN E
U+1DA0    MODIFIER LETTER SMALL F
U+1DA1    MODIFIER LETTER SMALL DOTLESS J WITH STROKE
U+1DA2    MODIFIER LETTER SMALL SCRIPT G
U+1DA3    MODIFIER LETTER SMALL TURNED H
U+1DA4    MODIFIER LETTER SMALL I WITH STROKE
U+1DA5    MODIFIER LETTER SMALL IOTA
U+1DA6    MODIFIER LETTER SMALL CAPITAL I
U+1DA7    MODIFIER LETTER SMALL CAPITAL I WITH STROKE
U+1DA8    MODIFIER LETTER SMALL J WITH CROSSED-TAIL
U+1DA9    MODIFIER LETTER SMALL L WITH RETROFLEX HOOK
U+1DAA    MODIFIER LETTER SMALL L WITH PALATAL HOOK
U+1DAB    MODIFIER LETTER SMALL CAPITAL L
U+1DAC    MODIFIER LETTER SMALL M WITH HOOK
U+1DAD    MODIFIER LETTER SMALL TURNED M WITH LONG LEG
U+1DAE    MODIFIER LETTER SMALL N WITH LEFT HOOK
U+1DAF    MODIFIER LETTER SMALL N WITH RETROFLEX HOOK
U+1DB0    MODIFIER LETTER SMALL CAPITAL N
U+1DB1    MODIFIER LETTER SMALL BARRED O
U+1DB2    MODIFIER LETTER SMALL PHI
U+1DB3    MODIFIER LETTER SMALL S WITH HOOK
U+1DB4    MODIFIER LETTER SMALL ESH
U+1DB5    MODIFIER LETTER SMALL T WITH PALATAL HOOK
U+1DB6    MODIFIER LETTER SMALL U BAR
U+1DB7    MODIFIER LETTER SMALL UPSILON
U+1DB8    MODIFIER LETTER SMALL CAPITAL U
U+1DB9    MODIFIER LETTER SMALL V WITH HOOK
U+1DBA    MODIFIER LETTER SMALL TURNED V
U+1DBB    MODIFIER LETTER SMALL Z
U+1DBC    MODIFIER LETTER SMALL Z WITH RETROFLEX HOOK
U+1DBD    MODIFIER LETTER SMALL Z WITH CURL
U+1DBE    MODIFIER LETTER SMALL EZH
U+1DBF    MODIFIER LETTER SMALL THETA
U+2071    SUPERSCRIPT LATIN SMALL LETTER I
U+207F    SUPERSCRIPT LATIN SMALL LETTER N
U+2090    LATIN SUBSCRIPT SMALL LETTER A
U+2091    LATIN SUBSCRIPT SMALL LETTER E
U+2092    LATIN SUBSCRIPT SMALL LETTER O
U+2093    LATIN SUBSCRIPT SMALL LETTER X
U+2094    LATIN SUBSCRIPT SMALL LETTER SCHWA
U+2095    LATIN SUBSCRIPT SMALL LETTER H
U+2096    LATIN SUBSCRIPT SMALL LETTER K
U+2097    LATIN SUBSCRIPT SMALL LETTER L
U+2098    LATIN SUBSCRIPT SMALL LETTER M
U+2099    LATIN SUBSCRIPT SMALL LETTER N
U+209A    LATIN SUBSCRIPT SMALL LETTER P
U+209B    LATIN SUBSCRIPT SMALL LETTER S
U+209C    LATIN SUBSCRIPT SMALL LETTER T
U+2C7C    LATIN SUBSCRIPT SMALL LETTER J
U+2C7D    MODIFIER LETTER CAPITAL V
U+2D6F    TIFINAGH MODIFIER LETTER LABIALIZATION MARK
U+2E2F    VERTICAL TILDE
U+3005    IDEOGRAPHIC ITERATION MARK
U+3031    VERTICAL KANA REPEAT MARK
U+3032    VERTICAL KANA REPEAT WITH VOICED SOUND MARK
U+3033    VERTICAL KANA REPEAT MARK UPPER HALF
U+3034    VERTICAL KANA REPEAT WITH VOICED SOUND MARK UPPER HALF
U+3035    VERTICAL KANA REPEAT MARK LOWER HALF
U+303B    VERTICAL IDEOGRAPHIC ITERATION MARK
U+309D    HIRAGANA ITERATION MARK
U+309E    HIRAGANA VOICED ITERATION MARK
U+30FC    KATAKANA-HIRAGANA PROLONGED SOUND MARK
U+30FD    KATAKANA ITERATION MARK
U+30FE    KATAKANA VOICED ITERATION MARK
U+A015    YI SYLLABLE WU
U+A4F8    LISU LETTER TONE MYA TI
U+A4F9    LISU LETTER TONE NA PO
U+A4FA    LISU LETTER TONE MYA CYA
U+A4FB    LISU LETTER TONE MYA BO
U+A4FC    LISU LETTER TONE MYA NA
U+A4FD    LISU LETTER TONE MYA JEU
U+A60C    VAI SYLLABLE LENGTHENER
U+A67F    CYRILLIC PAYEROK
U+A69C    MODIFIER LETTER CYRILLIC HARD SIGN
U+A69D    MODIFIER LETTER CYRILLIC SOFT SIGN
U+A717    MODIFIER LETTER DOT VERTICAL BAR
U+A718    MODIFIER LETTER DOT SLASH
U+A719    MODIFIER LETTER DOT HORIZONTAL BAR
U+A71A    MODIFIER LETTER LOWER RIGHT CORNER ANGLE
U+A71B    MODIFIER LETTER RAISED UP ARROW
U+A71C    MODIFIER LETTER RAISED DOWN ARROW
U+A71D    MODIFIER LETTER RAISED EXCLAMATION MARK
U+A71E    MODIFIER LETTER RAISED INVERTED EXCLAMATION MARK
U+A71F    MODIFIER LETTER LOW INVERTED EXCLAMATION MARK
U+A770    MODIFIER LETTER US
U+A788    MODIFIER LETTER LOW CIRCUMFLEX ACCENT
U+A7F8    MODIFIER LETTER CAPITAL H WITH STROKE
U+A7F9    MODIFIER LETTER SMALL LIGATURE OE
U+A9CF    JAVANESE PANGRANGKEP
U+A9E6    MYANMAR MODIFIER LETTER SHAN REDUPLICATION
U+AA70    MYANMAR MODIFIER LETTER KHAMTI REDUPLICATION
U+AADD    TAI VIET SYMBOL SAM
U+AAF3    MEETEI MAYEK SYLLABLE REPETITION MARK
U+AAF4    MEETEI MAYEK WORD REPETITION MARK
U+AB5C    MODIFIER LETTER SMALL HENG
U+AB5D    MODIFIER LETTER SMALL L WITH INVERTED LAZY S
U+AB5E    MODIFIER LETTER SMALL L WITH MIDDLE TILDE
U+AB5F    MODIFIER LETTER SMALL U WITH LEFT HOOK
U+FF70    HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK
U+FF9E    HALFWIDTH KATAKANA VOICED SOUND MARK
U+FF9F    HALFWIDTH KATAKANA SEMI-VOICED SOUND MARK
U+16B40    PAHAWH HMONG SIGN VOS SEEV
U+16B41    PAHAWH HMONG SIGN MEEJ SUAB
U+16B42    PAHAWH HMONG SIGN VOS NRUA
U+16B43    PAHAWH HMONG SIGN IB YAM
U+16F93    MIAO LETTER TONE-2
U+16F94    MIAO LETTER TONE-3
U+16F95    MIAO LETTER TONE-4
U+16F96    MIAO LETTER TONE-5
U+16F97    MIAO LETTER TONE-6
U+16F98    MIAO LETTER TONE-7
U+16F99    MIAO LETTER TONE-8
U+16F9A    MIAO LETTER REFORMED TONE-1
U+16F9B    MIAO LETTER REFORMED TONE-2
U+16F9C    MIAO LETTER REFORMED TONE-4
U+16F9D    MIAO LETTER REFORMED TONE-5
U+16F9E    MIAO LETTER REFORMED TONE-6
U+16F9F    MIAO LETTER REFORMED TONE-8
*/
};

}

#endif // UNICODE_LETTER_MODIFIER_HPP_INCLUDED
