#ifndef UNICODE_MARK_ENCLOSING_HPP_INCLUDED
#define UNICODE_MARK_ENCLOSING_HPP_INCLUDED

namespace unicode {

// Me
class mark_enclosing
{
/*
Character Name
U+0488    COMBINING CYRILLIC HUNDRED THOUSANDS SIGN
U+0489    COMBINING CYRILLIC MILLIONS SIGN
U+1ABE    COMBINING PARENTHESES OVERLAY
U+20DD    COMBINING ENCLOSING CIRCLE
U+20DE    COMBINING ENCLOSING SQUARE
U+20DF    COMBINING ENCLOSING DIAMOND
U+20E0    COMBINING ENCLOSING CIRCLE BACKSLASH
U+20E2    COMBINING ENCLOSING SCREEN
U+20E3    COMBINING ENCLOSING KEYCAP
U+20E4    COMBINING ENCLOSING UPWARD POINTING TRIANGLE
U+A670    COMBINING CYRILLIC TEN MILLIONS SIGN
U+A671    COMBINING CYRILLIC HUNDRED MILLIONS SIGN
U+A672    COMBINING CYRILLIC THOUSAND MILLIONS SIGN
*/
};

}

#endif // UNICODE_MARK_ENCLOSING_HPP_INCLUDED
