#ifndef UNICODE_NUMBER_LETTER_HPP_INCLUDED
#define UNICODE_NUMBER_LETTER_HPP_INCLUDED

namespace unicode {

// Nl
class number_letter
{
/*
Character Name
U+16EE    RUNIC ARLAUG SYMBOL
U+16EF    RUNIC TVIMADUR SYMBOL
U+16F0    RUNIC BELGTHOR SYMBOL
U+2160    ROMAN NUMERAL ONE
U+2161    ROMAN NUMERAL TWO
U+2162    ROMAN NUMERAL THREE
U+2163    ROMAN NUMERAL FOUR
U+2164    ROMAN NUMERAL FIVE
U+2165    ROMAN NUMERAL SIX
U+2166    ROMAN NUMERAL SEVEN
U+2167    ROMAN NUMERAL EIGHT
U+2168    ROMAN NUMERAL NINE
U+2169    ROMAN NUMERAL TEN
U+216A    ROMAN NUMERAL ELEVEN
U+216B    ROMAN NUMERAL TWELVE
U+216C    ROMAN NUMERAL FIFTY
U+216D    ROMAN NUMERAL ONE HUNDRED
U+216E    ROMAN NUMERAL FIVE HUNDRED
U+216F    ROMAN NUMERAL ONE THOUSAND
U+2170    SMALL ROMAN NUMERAL ONE
U+2171    SMALL ROMAN NUMERAL TWO
U+2172    SMALL ROMAN NUMERAL THREE
U+2173    SMALL ROMAN NUMERAL FOUR
U+2174    SMALL ROMAN NUMERAL FIVE
U+2175    SMALL ROMAN NUMERAL SIX
U+2176    SMALL ROMAN NUMERAL SEVEN
U+2177    SMALL ROMAN NUMERAL EIGHT
U+2178    SMALL ROMAN NUMERAL NINE
U+2179    SMALL ROMAN NUMERAL TEN
U+217A    SMALL ROMAN NUMERAL ELEVEN
U+217B    SMALL ROMAN NUMERAL TWELVE
U+217C    SMALL ROMAN NUMERAL FIFTY
U+217D    SMALL ROMAN NUMERAL ONE HUNDRED
U+217E    SMALL ROMAN NUMERAL FIVE HUNDRED
U+217F    SMALL ROMAN NUMERAL ONE THOUSAND
U+2180    ROMAN NUMERAL ONE THOUSAND C D
U+2181    ROMAN NUMERAL FIVE THOUSAND
U+2182    ROMAN NUMERAL TEN THOUSAND
U+2185    ROMAN NUMERAL SIX LATE FORM
U+2186    ROMAN NUMERAL FIFTY EARLY FORM
U+2187    ROMAN NUMERAL FIFTY THOUSAND
U+2188    ROMAN NUMERAL ONE HUNDRED THOUSAND
U+3007    IDEOGRAPHIC NUMBER ZERO
U+3021    HANGZHOU NUMERAL ONE
U+3022    HANGZHOU NUMERAL TWO
U+3023    HANGZHOU NUMERAL THREE
U+3024    HANGZHOU NUMERAL FOUR
U+3025    HANGZHOU NUMERAL FIVE
U+3026    HANGZHOU NUMERAL SIX
U+3027    HANGZHOU NUMERAL SEVEN
U+3028    HANGZHOU NUMERAL EIGHT
U+3029    HANGZHOU NUMERAL NINE
U+3038    HANGZHOU NUMERAL TEN
U+3039    HANGZHOU NUMERAL TWENTY
U+303A    HANGZHOU NUMERAL THIRTY
U+A6E6    BAMUM LETTER MO
U+A6E7    BAMUM LETTER MBAA
U+A6E8    BAMUM LETTER TET
U+A6E9    BAMUM LETTER KPA
U+A6EA    BAMUM LETTER TEN
U+A6EB    BAMUM LETTER NTUU
U+A6EC    BAMUM LETTER SAMBA
U+A6ED    BAMUM LETTER FAAMAE
U+A6EE    BAMUM LETTER KOVUU
U+A6EF    BAMUM LETTER KOGHOM
U+10140    GREEK ACROPHONIC ATTIC ONE QUARTER
U+10141    GREEK ACROPHONIC ATTIC ONE HALF
U+10142    GREEK ACROPHONIC ATTIC ONE DRACHMA
U+10143    GREEK ACROPHONIC ATTIC FIVE
U+10144    GREEK ACROPHONIC ATTIC FIFTY
U+10145    GREEK ACROPHONIC ATTIC FIVE HUNDRED
U+10146    GREEK ACROPHONIC ATTIC FIVE THOUSAND
U+10147    GREEK ACROPHONIC ATTIC FIFTY THOUSAND
U+10148    GREEK ACROPHONIC ATTIC FIVE TALENTS
U+10149    GREEK ACROPHONIC ATTIC TEN TALENTS
U+1014A    GREEK ACROPHONIC ATTIC FIFTY TALENTS
U+1014B    GREEK ACROPHONIC ATTIC ONE HUNDRED TALENTS
U+1014C    GREEK ACROPHONIC ATTIC FIVE HUNDRED TALENTS
U+1014D    GREEK ACROPHONIC ATTIC ONE THOUSAND TALENTS
U+1014E    GREEK ACROPHONIC ATTIC FIVE THOUSAND TALENTS
U+1014F    GREEK ACROPHONIC ATTIC FIVE STATERS
U+10150    GREEK ACROPHONIC ATTIC TEN STATERS
U+10151    GREEK ACROPHONIC ATTIC FIFTY STATERS
U+10152    GREEK ACROPHONIC ATTIC ONE HUNDRED STATERS
U+10153    GREEK ACROPHONIC ATTIC FIVE HUNDRED STATERS
U+10154    GREEK ACROPHONIC ATTIC ONE THOUSAND STATERS
U+10155    GREEK ACROPHONIC ATTIC TEN THOUSAND STATERS
U+10156    GREEK ACROPHONIC ATTIC FIFTY THOUSAND STATERS
U+10157    GREEK ACROPHONIC ATTIC TEN MNAS
U+10158    GREEK ACROPHONIC HERAEUM ONE PLETHRON
U+10159    GREEK ACROPHONIC THESPIAN ONE
U+1015A    GREEK ACROPHONIC HERMIONIAN ONE
U+1015B    GREEK ACROPHONIC EPIDAUREAN TWO
U+1015C    GREEK ACROPHONIC THESPIAN TWO
U+1015D    GREEK ACROPHONIC CYRENAIC TWO DRACHMAS
U+1015E    GREEK ACROPHONIC EPIDAUREAN TWO DRACHMAS
U+1015F    GREEK ACROPHONIC TROEZENIAN FIVE
U+10160    GREEK ACROPHONIC TROEZENIAN TEN
U+10161    GREEK ACROPHONIC TROEZENIAN TEN ALTERNATE FORM
U+10162    GREEK ACROPHONIC HERMIONIAN TEN
U+10163    GREEK ACROPHONIC MESSENIAN TEN
U+10164    GREEK ACROPHONIC THESPIAN TEN
U+10165    GREEK ACROPHONIC THESPIAN THIRTY
U+10166    GREEK ACROPHONIC TROEZENIAN FIFTY
U+10167    GREEK ACROPHONIC TROEZENIAN FIFTY ALTERNATE FORM
U+10168    GREEK ACROPHONIC HERMIONIAN FIFTY
U+10169    GREEK ACROPHONIC THESPIAN FIFTY
U+1016A    GREEK ACROPHONIC THESPIAN ONE HUNDRED
U+1016B    GREEK ACROPHONIC THESPIAN THREE HUNDRED
U+1016C    GREEK ACROPHONIC EPIDAUREAN FIVE HUNDRED
U+1016D    GREEK ACROPHONIC TROEZENIAN FIVE HUNDRED
U+1016E    GREEK ACROPHONIC THESPIAN FIVE HUNDRED
U+1016F    GREEK ACROPHONIC CARYSTIAN FIVE HUNDRED
U+10170    GREEK ACROPHONIC NAXIAN FIVE HUNDRED
U+10171    GREEK ACROPHONIC THESPIAN ONE THOUSAND
U+10172    GREEK ACROPHONIC THESPIAN FIVE THOUSAND
U+10173    GREEK ACROPHONIC DELPHIC FIVE MNAS
U+10174    GREEK ACROPHONIC STRATIAN FIFTY MNAS
U+10341    GOTHIC LETTER NINETY
U+1034A    GOTHIC LETTER NINE HUNDRED
U+103D1    OLD PERSIAN NUMBER ONE
U+103D2    OLD PERSIAN NUMBER TWO
U+103D3    OLD PERSIAN NUMBER TEN
U+103D4    OLD PERSIAN NUMBER TWENTY
U+103D5    OLD PERSIAN NUMBER HUNDRED
U+12400    CUNEIFORM NUMERIC SIGN TWO ASH
U+12401    CUNEIFORM NUMERIC SIGN THREE ASH
U+12402    CUNEIFORM NUMERIC SIGN FOUR ASH
U+12403    CUNEIFORM NUMERIC SIGN FIVE ASH
U+12404    CUNEIFORM NUMERIC SIGN SIX ASH
U+12405    CUNEIFORM NUMERIC SIGN SEVEN ASH
U+12406    CUNEIFORM NUMERIC SIGN EIGHT ASH
U+12407    CUNEIFORM NUMERIC SIGN NINE ASH
U+12408    CUNEIFORM NUMERIC SIGN THREE DISH
U+12409    CUNEIFORM NUMERIC SIGN FOUR DISH
U+1240A    CUNEIFORM NUMERIC SIGN FIVE DISH
U+1240B    CUNEIFORM NUMERIC SIGN SIX DISH
U+1240C    CUNEIFORM NUMERIC SIGN SEVEN DISH
U+1240D    CUNEIFORM NUMERIC SIGN EIGHT DISH
U+1240E    CUNEIFORM NUMERIC SIGN NINE DISH
U+1240F    CUNEIFORM NUMERIC SIGN FOUR U
U+12410    CUNEIFORM NUMERIC SIGN FIVE U
U+12411    CUNEIFORM NUMERIC SIGN SIX U
U+12412    CUNEIFORM NUMERIC SIGN SEVEN U
U+12413    CUNEIFORM NUMERIC SIGN EIGHT U
U+12414    CUNEIFORM NUMERIC SIGN NINE U
U+12415    CUNEIFORM NUMERIC SIGN ONE GESH2
U+12416    CUNEIFORM NUMERIC SIGN TWO GESH2
U+12417    CUNEIFORM NUMERIC SIGN THREE GESH2
U+12418    CUNEIFORM NUMERIC SIGN FOUR GESH2
U+12419    CUNEIFORM NUMERIC SIGN FIVE GESH2
U+1241A    CUNEIFORM NUMERIC SIGN SIX GESH2
U+1241B    CUNEIFORM NUMERIC SIGN SEVEN GESH2
U+1241C    CUNEIFORM NUMERIC SIGN EIGHT GESH2
U+1241D    CUNEIFORM NUMERIC SIGN NINE GESH2
U+1241E    CUNEIFORM NUMERIC SIGN ONE GESHU
U+1241F    CUNEIFORM NUMERIC SIGN TWO GESHU
U+12420    CUNEIFORM NUMERIC SIGN THREE GESHU
U+12421    CUNEIFORM NUMERIC SIGN FOUR GESHU
U+12422    CUNEIFORM NUMERIC SIGN FIVE GESHU
U+12423    CUNEIFORM NUMERIC SIGN TWO SHAR2
U+12424    CUNEIFORM NUMERIC SIGN THREE SHAR2
U+12425    CUNEIFORM NUMERIC SIGN THREE SHAR2 VARIANT FORM
U+12426    CUNEIFORM NUMERIC SIGN FOUR SHAR2
U+12427    CUNEIFORM NUMERIC SIGN FIVE SHAR2
U+12428    CUNEIFORM NUMERIC SIGN SIX SHAR2
U+12429    CUNEIFORM NUMERIC SIGN SEVEN SHAR2
U+1242A    CUNEIFORM NUMERIC SIGN EIGHT SHAR2
U+1242B    CUNEIFORM NUMERIC SIGN NINE SHAR2
U+1242C    CUNEIFORM NUMERIC SIGN ONE SHARU
U+1242D    CUNEIFORM NUMERIC SIGN TWO SHARU
U+1242E    CUNEIFORM NUMERIC SIGN THREE SHARU
U+1242F    CUNEIFORM NUMERIC SIGN THREE SHARU VARIANT FORM
U+12430    CUNEIFORM NUMERIC SIGN FOUR SHARU
U+12431    CUNEIFORM NUMERIC SIGN FIVE SHARU
U+12432    CUNEIFORM NUMERIC SIGN SHAR2 TIMES GAL PLUS DISH
U+12433    CUNEIFORM NUMERIC SIGN SHAR2 TIMES GAL PLUS MIN
U+12434    CUNEIFORM NUMERIC SIGN ONE BURU
U+12435    CUNEIFORM NUMERIC SIGN TWO BURU
U+12436    CUNEIFORM NUMERIC SIGN THREE BURU
U+12437    CUNEIFORM NUMERIC SIGN THREE BURU VARIANT FORM
U+12438    CUNEIFORM NUMERIC SIGN FOUR BURU
U+12439    CUNEIFORM NUMERIC SIGN FIVE BURU
U+1243A    CUNEIFORM NUMERIC SIGN THREE VARIANT FORM ESH16
U+1243B    CUNEIFORM NUMERIC SIGN THREE VARIANT FORM ESH21
U+1243C    CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU
U+1243D    CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU4
U+1243E    CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU A
U+1243F    CUNEIFORM NUMERIC SIGN FOUR VARIANT FORM LIMMU B
U+12440    CUNEIFORM NUMERIC SIGN SIX VARIANT FORM ASH9
U+12441    CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN3
U+12442    CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN A
U+12443    CUNEIFORM NUMERIC SIGN SEVEN VARIANT FORM IMIN B
U+12444    CUNEIFORM NUMERIC SIGN EIGHT VARIANT FORM USSU
U+12445    CUNEIFORM NUMERIC SIGN EIGHT VARIANT FORM USSU3
U+12446    CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU
U+12447    CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU3
U+12448    CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU4
U+12449    CUNEIFORM NUMERIC SIGN NINE VARIANT FORM ILIMMU A
U+1244A    CUNEIFORM NUMERIC SIGN TWO ASH TENU
U+1244B    CUNEIFORM NUMERIC SIGN THREE ASH TENU
U+1244C    CUNEIFORM NUMERIC SIGN FOUR ASH TENU
U+1244D    CUNEIFORM NUMERIC SIGN FIVE ASH TENU
U+1244E    CUNEIFORM NUMERIC SIGN SIX ASH TENU
U+1244F    CUNEIFORM NUMERIC SIGN ONE BAN2
U+12450    CUNEIFORM NUMERIC SIGN TWO BAN2
U+12451    CUNEIFORM NUMERIC SIGN THREE BAN2
U+12452    CUNEIFORM NUMERIC SIGN FOUR BAN2
U+12453    CUNEIFORM NUMERIC SIGN FOUR BAN2 VARIANT FORM
U+12454    CUNEIFORM NUMERIC SIGN FIVE BAN2
U+12455    CUNEIFORM NUMERIC SIGN FIVE BAN2 VARIANT FORM
U+12456    CUNEIFORM NUMERIC SIGN NIGIDAMIN
U+12457    CUNEIFORM NUMERIC SIGN NIGIDAESH
U+12458    CUNEIFORM NUMERIC SIGN ONE ESHE3
U+12459    CUNEIFORM NUMERIC SIGN TWO ESHE3
U+1245A    CUNEIFORM NUMERIC SIGN ONE THIRD DISH
U+1245B    CUNEIFORM NUMERIC SIGN TWO THIRDS DISH
U+1245C    CUNEIFORM NUMERIC SIGN FIVE SIXTHS DISH
U+1245D    CUNEIFORM NUMERIC SIGN ONE THIRD VARIANT FORM A
U+1245E    CUNEIFORM NUMERIC SIGN TWO THIRDS VARIANT FORM A
U+1245F    CUNEIFORM NUMERIC SIGN ONE EIGHTH ASH
U+12460    CUNEIFORM NUMERIC SIGN ONE QUARTER ASH
U+12461    CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE SIXTH
U+12462    CUNEIFORM NUMERIC SIGN OLD ASSYRIAN ONE QUARTER
U+12463    CUNEIFORM NUMERIC SIGN ONE QUARTER GUR
U+12464    CUNEIFORM NUMERIC SIGN ONE HALF GUR
U+12465    CUNEIFORM NUMERIC SIGN ELAMITE ONE THIRD
U+12466    CUNEIFORM NUMERIC SIGN ELAMITE TWO THIRDS
U+12467    CUNEIFORM NUMERIC SIGN ELAMITE FORTY
U+12468    CUNEIFORM NUMERIC SIGN ELAMITE FIFTY
U+12469    CUNEIFORM NUMERIC SIGN FOUR U VARIANT FORM
U+1246A    CUNEIFORM NUMERIC SIGN FIVE U VARIANT FORM
U+1246B    CUNEIFORM NUMERIC SIGN SIX U VARIANT FORM
U+1246C    CUNEIFORM NUMERIC SIGN SEVEN U VARIANT FORM
U+1246D    CUNEIFORM NUMERIC SIGN EIGHT U VARIANT FORM
U+1246E    CUNEIFORM NUMERIC SIGN NINE U VARIANT FORM
*/
};

}

#endif // UNICODE_NUMBER_LETTER_HPP_INCLUDED
