#ifndef UNICODE_PUNCTUATION_CONNECTOR_HPP_INCLUDED
#define UNICODE_PUNCTUATION_CONNECTOR_HPP_INCLUDED

namespace unicode {

// Pc
class punctuation_connector
{
/*
Character Name
U+005F    LOW LINE
U+203F    UNDERTIE
U+2040    CHARACTER TIE
U+2054    INVERTED UNDERTIE
U+FE33    PRESENTATION FORM FOR VERTICAL LOW LINE
U+FE34    PRESENTATION FORM FOR VERTICAL WAVY LOW LINE
U+FE4D    DASHED LOW LINE
U+FE4E    CENTRELINE LOW LINE
U+FE4F    WAVY LOW LINE
U+FF3F    FULLWIDTH LOW LINE
*/
};

}

#endif // UNICODE_PUNCTUATION_CONNECTOR_HPP_INCLUDED
