#ifndef UNICODE_PUNCTUATION_FINAL_QUOTE_HPP_INCLUDED
#define UNICODE_PUNCTUATION_FINAL_QUOTE_HPP_INCLUDED

namespace unicode {

// Pf
class punctuation_final_quote
{
/*
Character Name
U+00BB    RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
U+2019    RIGHT SINGLE QUOTATION MARK
U+201D    RIGHT DOUBLE QUOTATION MARK
U+203A    SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
U+2E03    RIGHT SUBSTITUTION BRACKET
U+2E05    RIGHT DOTTED SUBSTITUTION BRACKET
U+2E0A    RIGHT TRANSPOSITION BRACKET
U+2E0D    RIGHT RAISED OMISSION BRACKET
U+2E1D    RIGHT LOW PARAPHRASE BRACKET
U+2E21    RIGHT VERTICAL BAR WITH QUILL
*/
};

}

#endif // UNICODE_PUNCTUATION_FINAL_QUOTE_HPP_INCLUDED
