#ifndef UNICODE_PUNCTUATION_INITIAL_QUOTE_HPP_INCLUDED
#define UNICODE_PUNCTUATION_INITIAL_QUOTE_HPP_INCLUDED

namespace unicode {

// Pi
class punctuation_initial_quote
{
/*
Character Name
U+00AB    LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
U+2018    LEFT SINGLE QUOTATION MARK
U+201B    SINGLE HIGH-REVERSED-9 QUOTATION MARK
U+201C    LEFT DOUBLE QUOTATION MARK
U+201F    DOUBLE HIGH-REVERSED-9 QUOTATION MARK
U+2039    SINGLE LEFT-POINTING ANGLE QUOTATION MARK
U+2E02    LEFT SUBSTITUTION BRACKET
U+2E04    LEFT DOTTED SUBSTITUTION BRACKET
U+2E09    LEFT TRANSPOSITION BRACKET
U+2E0C    LEFT RAISED OMISSION BRACKET
U+2E1C    LEFT LOW PARAPHRASE BRACKET
U+2E20    LEFT VERTICAL BAR WITH QUILL
*/
};

}

#endif // UNICODE_PUNCTUATION_INITIAL_QUOTE_HPP_INCLUDED
