#ifndef UNICODE_PUNCTUATION_DASH_HPP_INCLUDED
#define UNICODE_PUNCTUATION_DASH_HPP_INCLUDED

namespace unicode {

// Pd
class punctuation_dash
{
/*
Character Name
U+002D    HYPHEN-MINUS
U+058A    ARMENIAN HYPHEN
U+05BE    HEBREW PUNCTUATION MAQAF
U+1400    CANADIAN SYLLABICS HYPHEN
U+1806    MONGOLIAN TODO SOFT HYPHEN
U+2010    HYPHEN
U+2011    NON-BREAKING HYPHEN
U+2012    FIGURE DASH
U+2013    EN DASH
U+2014    EM DASH
U+2015    HORIZONTAL BAR
U+2E17    DOUBLE OBLIQUE HYPHEN
U+2E1A    HYPHEN WITH DIAERESIS
U+2E3A    TWO-EM DASH
U+2E3B    THREE-EM DASH
U+2E40    DOUBLE HYPHEN
U+301C    WAVE DASH
U+3030    WAVY DASH
U+30A0    KATAKANA-HIRAGANA DOUBLE HYPHEN
U+FE31    PRESENTATION FORM FOR VERTICAL EM DASH
U+FE32    PRESENTATION FORM FOR VERTICAL EN DASH
U+FE58    SMALL EM DASH
U+FE63    SMALL HYPHEN-MINUS
U+FF0D    FULLWIDTH HYPHEN-MINUS
*/
};

}

#endif // UNICODE_PUNCTUATION_DASH_HPP_INCLUDED
